### ISSUE TITLE
Unable to compile on Linux when multiple OpenSSL versions are installed

### ISSUE THREAD

**Issue by shvelo** [sfackler/rust-openssl#1027]
Hello, I'm trying to install `reqwest` on Arch Linux, which depends on `openssl`. I have `openssl-1.1.1` (`/usr/include/openssl`, `/usr/lib`) and `openssl-1.0.2` (`/usr/include/openssl-1.0`, `/usr/lib/openssl-1.0`) installed on my system.  I don't have either `OPENSSL_DIR`, `OPENSSL_LIB_DIR` or `OPENSSL_INCLUDE_DIR` set.

```
process didn't exit successfully: `/tmp/cargo-installRfttYI/release/build/openssl-sys-ad7426892b634977/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=crypto
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-E" "/tmp/cargo-installRfttYI/release/build/openssl-sys-a10b0929b500815e/out/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_SSL3_METHOD

--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.

', /home/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.21/build.rs:486:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:210
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:224
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:487
   5: std::panicking::begin_panic
   6: build_script_build::validate_headers
   7: build_script_build::main
   8: std::rt::lang_start::{{closure}}
   9: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:306
  10: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  11: std::rt::lang_start_internal
             at src/libstd/panicking.rs:285
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  12: main
  13: __libc_start_main
  14: _start

```

**Comment by sfackler** [comment]
You're using a version of openssl-sys that's over a year old. You'll need to update that if you want to link against 1.1.1.

Alternatively, you can use the OPENSSL_INCLUDE_DIR and OPENSSL_LIB_DIR environment variables to point to the 1.0.2 install.
