### ISSUE TITLE
macOS: Homebrew-installed OpenSSL is not automatically found

### ISSUE THREAD

**Issue by Phrohdoh** [sfackler/rust-openssl#1031]
What *did* work was the following:

```shell
$ OPENSSL_DIR=/usr/local/opt/openssl/ cargo build
```

**Comment by sfackler** [comment]
Could you provide some more details? We check for exactly that directory, so I'm not sure how it could be failing: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/main.rs#L145-L155

**Comment by Phrohdoh** [comment]
Interesting!  I am not sure either then.  I'll try to repro later today and report back.

**Comment by Phrohdoh** [comment]
I am unable to reproduce this issue.

**Comment by parasyte** [comment]
I have the same problem running `cargo run --release --example server` on [httpbis](https://crates.io/crates/httpbis). It is fully reproducible, and the workaround provided above fixes it. This could already be fixed in 0.10?

```
$ RUST_BACKTRACE=1 cargo run --release --example server
   Compiling openssl-sys v0.9.40
   Compiling openssl v0.9.24
   Compiling tls-api-openssl v0.1.20
error: failed to run custom build command for `tls-api-openssl v0.1.20`
process didn't exit successfully: `/Users/jay/other-projects/rust-http2/target/release/build/tls-api-openssl-9a8b285352accbce/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/tls-api-openssl-0.1.20/build.rs:14:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: main

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/Users/jay/other-projects/rust-http2/target/release/build/openssl-16f5128169636593/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /Users/jay/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: build_script_build::main
   7: std::rt::lang_start::{{closure}}
   8: std::panicking::try::do_call
   9: __rust_maybe_catch_panic
  10: std::rt::lang_start_internal
  11: main
```

```
$ OPENSSL_DIR=/usr/local/opt/openssl/ cargo run --release --example server
   Compiling openssl-sys v0.9.40
   Compiling openssl v0.9.24
   Compiling tls-api-openssl v0.1.20
   Compiling httpbis v0.8.0 (/Users/jay/other-projects/rust-http2)
    Finished release [optimized] target(s) in 11.59s
     Running `target/release/examples/server`
started server
check it at: https://localhost:8443/
```

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G4015
```

```
$ brew info openssl | head -n 1
openssl: stable 1.0.2q (bottled) [keg-only
```

```
$ brew info pkg-config | head -n 1
pkg-config: stable 0.29.2 (bottled)
```

**Comment by sfackler** [comment]
openssl 0.9 doesn't support OpenSSL 1.1.1, which you presumably have installed (it's the `openssl@1.1` package).

**Comment by parasyte** [comment]
@sfackler Where do you see that? It's 1.02q (see above: `brew info openssl` output)

**Comment by sfackler** [comment]
The cause of the "Unable to detect OpenSSL version" error is due to a version of OpenSSL the library wasn't expecting, but openssl-sys is able to work with. That's 1.1.1.

`brew info openssl@1.1`

**Comment by parasyte** [comment]
```
$ brew ls | grep openssl
openresty-openssl
openssl
openssl@1.1
```

Yep, I have that installed... Thanks.

**Comment by yseyha** [comment]
I've solved with
`brew install openssl@3`
