### ISSUE TITLE
Calls to decrypt doesn't work but call to Crypter does?

### ISSUE THREAD

**Issue by jcmorrow** [sfackler/rust-openssl#1137]
Hi! I'm working on cryptopals and I have discovered a behavior that I'd like to understand better. Below are two functions that I would *expect* are doing the same thing, but one fails and the other does not (with the given inputs).

Working function:
```
use openssl::symm::{decrypt, encrypt, Cipher, Crypter, Mode};

pub fn decrypt_data_1(data: &[u8], key: &[u8]) -> Vec<u8> {
    let cipher = Cipher::aes_128_ecb();

    let mut decrypted = Crypter::new(cipher, Mode::Decrypt, key, None).unwrap();
    let mut output = vec![0 as u8; data.len() + Cipher::aes_128_cbc().block_size()];

    let decrypted_result = decrypted.update(&data, &mut output);

    match decrypted_result {
        Ok(_) => output,
        Err(e) => panic!("Error decrypting text: {}", e),
    }
}

pub fn decrypt_data_2(encrypted: &[u8], key: &[u8]) -> Vec<u8> {
    let cipher = Cipher::aes_128_ecb();

    decrypt(cipher, key, None, encrypted).unwrap()
}

fn main() {
    let key = "YELLOW SUBMARINE";

    let line = vec![
        9, 18, 48, 170, 222, 62, 179, 48, 219, 170, 67, 88, 248, 141, 42, 108,
    ];

    println!(
        "{:?}",
        // This works just fine
        &decrypt_data_1(&line, key.as_bytes())
    );

    // This does *not* work
    println!("{:?}", decrypt_data_2(&line, key.as_bytes()));
}
```

The second call fails with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 101077092, library: "digital envelope routines", function: "EV
P_DecryptFinal_ex", reason: "bad decrypt", file: "crypto/evp/evp_enc.c", line: 570 }])', src/libcore/result.rs:997:5
stack backtrace:                                                                                                                                                
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39                                                                                               
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook                                                                                                                              
             at src/libstd/panicking.rs:215
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt                                        
             at src/libstd/panicking.rs:385  
   6: std::panicking::try::do_call                                                                                                                                           at src/libstd/panicking.rs:312
   7: <T as core::any::Any>::type_id   
             at src/libcore/panicking.rs:85
   8: <alloc::string::String as core::ops::deref::Deref>::deref                                                                                                 
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/macros.rs:17                                                                        
   9: <core::result::Result<T, E>>::unwrap                                                                                                                      
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libcore/result.rs:798                                                                       
  10: challenge_2::decrypt_aes_128_ecb                                                                                                                          
             at src/main.rs:162                                                                                                                                 
  11: challenge_2::main                                                                                                                                         
             at src/main.rs:25                                                                                                                                  
  12: std::rt::lang_start::{{closure}}                                                                                                                          
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64                                                                             
  13: std::panicking::try::do_call                                                                                                                              
             at src/libstd/rt.rs:49                                                                                                                             
             at src/libstd/panicking.rs:297                                                                                                                     
  14: panic_unwind::dwarf::eh::read_encoded_pointer                                                                                                             
             at src/libpanic_unwind/lib.rs:87                                                                                                                   
  15: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get                                                                               
             at src/libstd/panicking.rs:276                                                                                                                     
             at src/libstd/panic.rs:388                                                                                                                         
             at src/libstd/rt.rs:48                                                                                                                             
  16: std::rt::lang_start                                                                                                                                       
             at /rustc/91856ed52c58aa5ba66a015354d1cc69e9779bdf/src/libstd/rt.rs:64                                                                             
  17: challenge_2::decrypt_aes_128_ecb                                          
```

Is there a significant difference between these two calls that I was supposed to understand from the documentation?

Thanks!

**Comment by jcmorrow** [comment]
I've created a Repo with my code in it so you can investigate easily! It's here: https://github.com/jcmorrow/cryptopals_open_ssl_question.

**Comment by sfackler** [comment]
The decrypt function just uses a Crypter, so you should be able to look at what it's doing to see the difference: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/symm.rs#L646-L668

**Comment by jcmorrow** [comment]
Thanks for the suggestion! It looks like something is going wrong in the line `let rest = c.finalize(&mut out[count..]).unwrap();`. I'll see if I can dig deeper and understand what's going on here!

**Comment by tkuriyama** [comment]
For future reference, version 2 (calling `decrypt` directly) appears to fail because `decrypt` assumes the presence of PKCS#7 padding. Version 1 works for me (though in my case I am setting the `pad` property of the [Crypter](https://docs.rs/openssl/0.9.24/openssl/symm/struct.Crypter.html) to `False`, for incremental decrypting of blocks). See also [https://superuser.com/questions/1225752/unable-to-decrypt-aes-with-openssl](https://superuser.com/questions/1225752/unable-to-decrypt-aes-with-openssl
