### ISSUE TITLE
Build script uses host compiler with cross compiling flags when expanding  build/expando.c

### ISSUE THREAD

**Issue by athei** [sfackler/rust-openssl#1141]
I am trying to cross compile a project for arm linux on my macOS that uses rust-openssl with the vendored feature enable. I use the following snippet to build the project:

```
export CROSS_COMPILE=arm-linux-musleabihf-
export CC=$(CROSS_COMPILE)gcc
cargo build --target=arm-unknown-linux-musleabihf
```

This almost works: The build is successful and passes the installation stage. Then it tries to expand `build/expando.c` and fails by calling the host gcc (which is clang) but giving cross compile flags `"-march=armv6" "-marm"`.

This is the error gist:
```
OPT_LEVEL = Some("0")
TARGET = Some("arm-unknown-linux-musleabihf")
HOST = Some("x86_64-apple-darwin")
CC_arm-unknown-linux-musleabihf = None
CC_arm_unknown_linux_musleabihf = None
TARGET_CC = None
CC = Some("gcc")
CFLAGS_arm-unknown-linux-musleabihf = None
CFLAGS_arm_unknown_linux_musleabihf = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("crt-static")
running: "gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-static" "-march=armv6" "-marm" "-mfpu=vfp" "-I" "/Users/alexander/Developer/fritzahalogger/target/arm-unknown-linux-musleabihf/debug/build/openssl-sys-7245c649d3ea2851/out/openssl-build/install/include" "-Wall" "-Wextra" "-E" "build/expando.c"
cargo:warning=clang: warning: argument unused during compilation: '-mno-thumb' [-Wunused-command-line-argument]
cargo:warning=clang: warning: argument unused during compilation: '-mfpu=vfp' [-Wunused-command-line-argument]
cargo:warning=error: unknown target CPU 'armv6'
cargo:warning=note: valid target CPU values are: nocona, core2, penryn, bonnell, atom, silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7, westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell, core-avx2, broadwell, skylake, skylake-avx512, skx, cannonlake, icelake-client, icelake-server, knl, knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3, opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3, bdver4, znver1, x86-64
exit code: 1

--- stderr
arm-linux-musleabihf-ar: creating apps/libapps.a
arm-linux-musleabihf-ar: creating libcrypto.a
arm-linux-musleabihf-ar: creating libssl.a
thread 'main' panicked at '
Header expansion error:
Error { kind: ToolExecError, message: "Command \"gcc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-g\" \"-fno-omit-frame-pointer\" \"-static\" \"-march=armv6\" \"-marm\" \"-mfpu=vfp\" \"-I\" \"/Users/alexander/Developer/fritzahalogger/target/arm-unknown-linux-musleabihf/debug/build/openssl-sys-7245c649d3ea2851/out/openssl-build/install/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"gcc\" did not execute successfully (status code exit code: 1)." }

Failed to find OpenSSL development headers.

You can try fixing this setting the `OPENSSL_DIR` environment variable
pointing to your OpenSSL installation or installing OpenSSL headers package
specific to your distribution:

    # On Ubuntu
    sudo apt-get install libssl-dev
    # On Arch Linux
    sudo pacman -S openssl
    # On Fedora
    sudo dnf install openssl-devel

See rust-openssl README for more information:

    https://github.com/sfackler/rust-openssl#linux
', /Users/alexander/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.47/build/main.rs:126:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:336
   7: build_script_main::validate_headers
             at ./build/main.rs:126
   8: build_script_main::main
             at ./build/main.rs:70
   9: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  10: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  11: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  12: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  13: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  14: build_script_main::determine_mode::{{closure}}

```

**Comment by sfackler** [comment]
From the build output, it looks like the build script sees the value of the `CC` environment variable as `gcc`, not `arm-linux-musleabihf-gcc`:

```
CC = Some("gcc")
```

Are you sure your environment variables are configured correctly?

**Comment by athei** [comment]
You are absolutely right:
`export CC=$(CROSS_COMPILE)gcc -> export CC=${CROSS_COMPILE}gcc`

Now the correct value is in $CC.

**But there is a new error**. It somehow builds the CC path wrongly:
`/bin/sh: arm-linux-musleabihf-arm-linux-musleabihf-gcc: command not found`

This also happens when I delete the CC variable.

**Comment by sfackler** [comment]
All of this is controlled by `cc`.
