### ISSUE TITLE
MacOS: build fails when invoked via IntelliJ CLion (Rust plugin)

### ISSUE THREAD

**Issue by mouse07410** [sfackler/rust-openssl#1212]
- MacOS Mojave 10.14.6
- Xcode-11.3
- rustc-1.40 (stable, installed via `rustup`)
- OpenSSL: Macports-installed `1.1.1d`, available as binary only (include files in `/opt/local/include/`, compiled libraries in `/opt/local/lib/`, `/opt/local/bin/openssl` executable)
- CLion 2019.3.2
    - Rust plugin `0.2.112.2148-193`

Everything else is current as per `crates.io`.

Apparent problem - build is unable to locate OpenSSL despite being  handed **everything**:
- `PKG_CONFIG_PATH=/opt/local/lib/pkgconfig:/opt/local/share/pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig`
- `OPENSSL_DIR=/opt/local`
- `OPENSSL_LIBS=-L/opt/local/lib -lssl -lcrypto`
- `OPENSSL_CFLAGS=-I/opt/local/include`

Here's what the IDE complains about:
```
/Users/uri/.cargo/bin/cargo test --color=always --no-run --all-features -- --nocapture
   Compiling typenum v1.11.2
   Compiling libc v0.2.66
   Compiling cc v1.0.48
   Compiling pkg-config v0.3.17
   Compiling proc-macro2 v0.4.30
   Compiling byteorder v1.3.2
   Compiling autocfg v0.1.7
   Compiling byte-tools v0.3.1
   Compiling unicode-xid v0.1.0
   Compiling syn v0.15.44
   Compiling bitflags v1.2.1
   Compiling gcc v0.3.55
   Compiling openssl v0.10.26
   Compiling subtle v1.0.0
   Compiling opaque-debug v0.2.3
   Compiling foreign-types-shared v0.1.1
   Compiling unicode-segmentation v1.6.0
   Compiling rustc-serialize v0.3.24
   Compiling keccak v0.1.0
   Compiling sha1 v0.2.0
   Compiling cfg-if v0.1.10
   Compiling fake-simd v0.1.2
   Compiling lazy_static v1.4.0
   Compiling hex v0.3.2
   Compiling strum v0.14.0
   Compiling block-padding v0.1.5
   Compiling openssl-sys v0.9.53
   Compiling foreign-types v0.3.2
   Compiling heck v0.3.1
   Compiling hmac-sha1 v0.1.3
   Compiling rust-crypto v0.2.36
   Compiling rand v0.4.6
   Compiling time v0.1.42
error: failed to run custom build command for `openssl-sys v0.9.53`

Caused by:
  process didn't exit successfully: `/Users/uri/src/rust-tst2/target/debug/build/openssl-sys-11c209ef5c2d5297/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
X86_64_APPLE_DARWIN_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR = /opt/local
cargo:rustc-link-search=native=/opt/local/lib
cargo:include=/opt/local/include
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,mmx,sse,sse2,sse3,ssse3")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/opt/local/include" "-Wall" "-Wextra" "-E" "build/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_SSL3_METHOD
cargo:rustc-cfg=ossl101
cargo:rustc-cfg=ossl102
cargo:rustc-cfg=ossl102f
cargo:rustc-cfg=ossl102h
cargo:rustc-cfg=ossl110
cargo:rustc-cfg=ossl110f
cargo:rustc-cfg=ossl110g
cargo:rustc-cfg=ossl111
cargo:rustc-cfg=ossl111b
cargo:rustc-cfg=ossl111c
cargo:version_number=1010104f
cargo:version=111
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIBS
X86_64_APPLE_DARWIN_OPENSSL_LIBS unset
cargo:rerun-if-env-changed=OPENSSL_LIBS
OPENSSL_LIBS = -L/opt/local/lib -lssl -lcrypto
cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_STATIC
X86_64_APPLE_DARWIN_OPENSSL_STATIC unset
cargo:rerun-if-env-changed=OPENSSL_STATIC
OPENSSL_STATIC unset

--- stderr
thread 'main' panicked at 'OpenSSL libdir at `/opt/local/lib` does not contain the required files to either statically or dynamically link OpenSSL', /Users/uri/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.53/build/main.rs:303:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: std::thread::local::fast::Key<T>::try_initialize
  13: build_script_main::determine_mode
             at ./build/main.rs:303
  14: build_script_main::main
             at ./build/main.rs:82
  15: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  16: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  17: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  19: std::panicking::try
             at src/libstd/panicking.rs:265
  20: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  21: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  22: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  23: build_script_main::determine_mode::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

Process finished with exit code 101
```

**Comment by sfackler** [comment]
OPENSSL_LIBS is not supposed to contain a set of command line arguments. It's used to override the name of the libraries in rare weird cases via a colon-separated list of library names.

**Comment by mouse07410** [comment]
It failed without `OPENSSL_LIBS` too.

**Comment by sfackler** [comment]
In what way did it fail? Does `/opt/local/lib` contain `libssl.dylib` and `libcrypto.dylib`?

**Comment by mouse07410** [comment]
> Does /opt/local/lib contain `libssl.dylib` and `libcrypto.dylib`?

```
$ ll /opt/local/lib/libssl.*dylib /opt/local/lib/libcrypto.*dylib
-rwxr-xr-x  1 root  admin  2228352 Dec 10 19:51 /opt/local/lib/libcrypto.1.1.dylib*
lrwxr-xr-x  1 root  admin       19 Sep 15 08:22 /opt/local/lib/libcrypto.dylib@ -> libcrypto.1.1.dylib
-rwxr-xr-x  1 root  admin   512256 Dec 10 19:52 /opt/local/lib/libssl.1.1.dylib*
lrwxr-xr-x  1 root  admin       16 Sep 15 08:22 /opt/local/lib/libssl.dylib@ -> libssl.1.1.dylib
$ 
```

> In what way did it fail?

It was failing on something like "cannot find OpenSSL, either static or dynamic libraries". But now (I wiped **all** the env vars from the IDE build configuration, except for `PATH=/opt/local/bin:/usr/local/bin:/usr/bin:/usr/sbin` that somehow remained) it miraculously works:
```
/Users/uri/.cargo/bin/cargo test --color=always --all-features -- --nocapture
    Finished test [unoptimized + debuginfo] target(s) in 0.13s
     Running target/debug/deps/rustfoo1-af0295cb2ea3aaf3

running 6 tests
HashNames::SHA1
HashNames::SHA256
HashNames::SHA384
HashNames::SHA512
test tests::list_hashes ... ok
test tests::test_len_of_hash ... ok
SHA1("abc") = a9993e364706816aba3e25717850c26c9cd0d89d
OpenSSL SHA1("0123...") = 29b0e7878271645fffb7eec7db4a7473a1c00bc1
OpenSSL SHA1("abc") = a9993e364706816aba3e25717850c26c9cd0d89d
target for SHA1: \x29\xb0\xe7\x87\x82\x71\x64\x5f\xff\xb7\xee\xc7\xdb\x4a\x74\x73\xa1\xc0\xb\xc1
SHA256("abc") = ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
SHA384("abc") = cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed8086072ba1e7cc2358baeca134c825a7
random m1=1621495906 m2=2069712892
OpenSSL SHA256("abc") = ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
OpenSSL SHA256("0123...") = 9cfe7faff7054298ca87557e15a10262de8d3eee77827417fbdfea1c41b9ec23
test tests::test_gen_rand ... ok
SHA512("abc") = ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
target for SHA256: \x9c\xfe\x7f\xaf\xf7\x5\x42\x98\xca\x87\x55\x7e\x15\xa1\x2\x62\xde\x8d\x3e\xee\x77\x82\x74\x17\xfb\xdf\xea\x1c\x41\xb9\xec\x23
test tests::test_do_hash ... ok
OpenSSL SHA384("0123...") = a98d733cacb06e110e0db539287513050860eda5081f2ffdd5aba3f337370518104d109d810f6a139bb5ea5f31bae3a2
OpenSSL SHA384("abc") = cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed8086072ba1e7cc2358baeca134c825a7
target for SHA384: \xa9\x8d\x73\x3c\xac\xb0\x6e\x11\xe\xd\xb5\x39\x28\x75\x13\x5\x8\x60\xed\xa5\x8\x1f\x2f\xfd\xd5\xab\xa3\xf3\x37\x37\x5\x18\x10\x4d\x10\x9d\x81\xf\x6a\x13\x9b\xb5\xea\x5f\x31\xba\xe3\xa2
OpenSSL SHA512("abc") = ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
OpenSSL SHA512("0123...") = 637a16b29ae017ace88d99e2475518144f506d394fc4c9c67788f8589471d3a01356ccb85cc94ea86472d17f093fba0a4dd7c3e326db59bb8181bbfcf1daed10
test tests::test_do_openssl_hash ... ok
target for SHA512: \x63\x7a\x16\xb2\x9a\xe0\x17\xac\xe8\x8d\x99\xe2\x47\x55\x18\x14\x4f\x50\x6d\x39\x4f\xc4\xc9\xc6\x77\x88\xf8\x58\x94\x71\xd3\xa0\x13\x56\xcc\xb8\x5c\xc9\x4e\xa8\x64\x72\xd1\x7f\x9\x3f\xba\xa\x4d\xd7\xc3\xe3\x26\xdb\x59\xbb\x81\x81\xbb\xfc\xf1\xda\xed\x10
test tests::test_pkcs11_tool ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


Process finished with exit code 0
```

No explanation - I had a successful CLI run, but after that I cleaned the directory, and IDE did recompile the crates... Don't know...

**Comment by sfackler** [comment]
Great, glad it's working.

**Comment by mouse07410** [comment]
@sfackler I'd still prefer a more robust OpenSSL detection, and a better documentation - that could, for example, warn against setting `OPENSSL_LIBS` and `OPENSSL_DIR`, and suggesting that if for whatever reason `pkg-config` doesn't locate the right version - set `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` env variable.

It is still unclear to me why it didn't work in the beginning (with or without `OPENSSL_DIR` and `OPENSSL_LIBS`), nor why it started working in the end (though I don't mind success at all ;).

**Comment by sfackler** [comment]
Why would we warn against setting OPENSSL_LIBS and OPENSSL_DIR? They're a totally reasonable (if obscure for OPENSSL_LIBS) way of configuring the detection.

**Comment by mouse07410** [comment]
> Why would we warn against setting `OPENSSL_LIBS` and `OPENSSL_DIR`?

#### Short answer: 
Because they don't work, at the very least don't work as expected.

#### Long answer:

`OPENSSL_DIR` does not seem to have any positive effect when pointed at a binary installation. Example: on my box OpenSSL is installed in `/opt/local/`, with includes in `/opt/local/include/openssl/*.h`, and libraries in `/opt/local/lib/`. Setting `OPENSSL_DIR=/opt/local` did not alleviate the problems, as you can see [above](https://github.com/sfackler/rust-openssl/issues/1212#issue-541929610). 

`OPENSSL_LIBS` appears to require value in format incompatible with what other packages that use this env var expect. Also, it's incompatible with what `pkg-config` returns (and that many people use to determine how to link against OpenSSL):
```
$ pkg-config --libs openssl
-L/opt/local/lib -lssl -lcrypto
$ pkg-config --libs --static openssl
-L/opt/local/lib -lssl -lcrypto -lz
$
```

Also, the order of priority of the env variables if more than one is set, is not specified. 

All of the above should be documented, IMHO.

On the other hand, it's your package - so do as you see fit. So far, I figured that the most reliable way to make your package detect my (Macports-installed) OpenSSL is to set `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` (and make sure no other OpenSSL-related env var is visible to the IDE), so unless/until you break/change those I'm all set.

**Comment by sfackler** [comment]
> Setting OPENSSL_DIR=/opt/local did not alleviate the problems, as you can see above.

It didn't work because you at the same time misused OPENSSL_LIBS by setting it to `-L/opt/local/lib -lssl -lcrypto`. That causes the build script to look for the file `/opt/local/lib/-L/opt/local/lib -lssl -lcrypto`, which does not exist.

> All of the above should be documented, IMHO.

Beyond the documentation right here? https://docs.rs/openssl/0.10.26/openssl/#manual

**Comment by mouse07410** [comment]
> It didn't work because you at the same time misused `OPENSSL_LIBS`...

Hmm, OK.

> Beyond the documentation right here?

Well, somehow I missed that. Yes, the referred manual is pretty good. I would still add the priority description - what happens if two variables contradict each other? "Then the build would fail" is not an attractive answer, especially if in reality one var can override the other.

And again, the reason my environment had `OPENSSL_LIBS` was that other (non-Rust) packages needed it. Perhaps this crate could be a little more conformant wrt. this var...
