### ISSUE TITLE
openssl-sys with vendored doesn't compile on Arch

### ISSUE THREAD

**Issue by nic-hartley** [sfackler/rust-openssl#1218]
Exactly what the title says. I'm running Manjaro Arch, trying to `cargo install cargo-web`, with:

- `pamac info openssl` shows version `1.1.1.d-2` (there's no `openssl-dev` or similar on Arch, AFAIK)
- `rustup --version`: `1.20.2`
- `cargo version`: `1.40.0` (same for `rustc`, etc.)
- `cargo-web` version: 0.6.26
- `openssl-sys` version: 0.9.45 (with the `vendored` feature)

It fails when compiling `openssl-sys`. Both the exact pinned version `0.9.45` and the latest compile just fine without the `vendored` feature; both fail when that feature is enabled. I can't change the version anyway. It works on Windows and, as far as I can tell, Ubuntu, hence mentioning Arch. 

Because this is the dependency of something I'm trying to install which has the specific version pinned, even if it is a bug in this crate and not a misconfiguration on my end, I'd still very much prefer to have a workaround. If there's no workaround, though, I'm happy to open an issue to bump versions.

`RUST_BACKTRACE=full` of the error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x5591593b0d24 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5591593b0d24 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5591593b0d24 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5591593b0d24 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x5591593d30bc - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x5591593ad887 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x5591593b49de - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x5591593b49de - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x5591593b49de - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x5591593b46d1 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x5591593b50db - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x5591593b4c7e - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x5591593b4b66 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x5591593d08ae - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x5591593d09a7 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x5591593886cc - openssl_src::Build::run_command::h071ba6d15eaa3c08
  16:     0x559159387321 - openssl_src::Build::build::hba47a1ec0b7fd556
  17:     0x55915937f54f - build_script_main::find::get_openssl::hbe15c6f910a50950
  18:     0x55915937a64a - build_script_main::main::h462f5d86a97e38a1
  19:     0x55915937db13 - std::rt::lang_start::{{closure}}::h189f4767f1222cf0
  20:     0x5591593b4b03 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  21:     0x5591593b4b03 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  22:     0x5591593bd16a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  23:     0x5591593b55bd - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  24:     0x5591593b55bd - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  25:     0x5591593b55bd - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  26:     0x55915937d252 - main
  27:     0x7f321d02f153 - __libc_start_main
  28:     0x55915937818e - _start
  29:                0x0 - <unknown>
```

**Comment by sfackler** [comment]
It looks like this should be filed on the openssl_src repository: https://github.com/alexcrichton/openssl-src-rs

**Comment by nic-hartley** [comment]
@sfackler Posted the issue there, too. Thanks! Feel free to reopen if it seems like it should actually be here in the end.
