### ISSUE TITLE
"session id context uninitialized" error on second connection (with peer verify)

### ISSUE THREAD

**Issue by krzk** [sfackler/rust-openssl#1235]
Hi All,

I have a pretty straightforward TLS server, almost entirely from example:
https://github.com/krzk/rust-try/blob/master/swss/src/main.rs

It comes with my own CA and certificates for server and client. When using peer verification (so as in the code above), first client connection (from Firefox) works, but second fails with:

```thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:8081), peer: V4(127.0.0.1:44066), fd: 5 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336433429, library: "SSL routines", function: "ssl_get_prev_session", reason: "session id context uninitialized", file: "ssl/ssl_sess.c", line: 578 }]))) } })', src/libcore/result.rs:1165:5```

The failure is on line:
`let stream = acceptor.accept(stream).unwrap();`

The problem does not appear if I turn off peer verification.

With backtrace:
```
Incoming connection #1
Incoming connection #1 accepted
Incoming connection #2
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:8081), peer: V4(127.0.0.1:44164), fd: 5 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336433429, library: "SSL routines", function: "ssl_get_prev_session", reason: "session id context uninitialized", file: "ssl/ssl_sess.c", line: 578 }]))) } })', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16: swss::main::{{closure}}
             at src/main.rs:40
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

* rust-openssl 0.10.28
* Tried with openssl vendored and regular

**Comment by sfackler** [comment]
You need to set a session ID context:

https://docs.rs/openssl/0.10.28/openssl/ssl/struct.SslContextBuilder.html#method.set_session_id_context

**Comment by krzk** [comment]
Ah, indeed. The Firefox was reusing the TLS session. Thank you!
