### ISSUE TITLE
Does not build on fresh macOS Big Sur/Apple Silicon installation

### ISSUE THREAD

**Issue by sdavids** [sfackler/rust-openssl#1409]
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
$ openssl version
LibreSSL 2.8.3
$ rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)
$ cargo --version
cargo 1.49.0 (d00d64df9 2020-12-05)
$ git remote -v
origin	https://github.com/sfackler/rust-openssl.git (fetch)
origin	https://github.com/sfackler/rust-openssl.git (push)
$ git rev-parse --short HEAD
9e29287a
$ RUST_BACKTRACE=1 cargo build
   Compiling openssl-sys v0.9.60 (/Users/dev/ws/github/rust-openssl/openssl-sys)
   Compiling serde_derive v1.0.123
error: failed to run custom build command for `openssl-sys v0.9.60 (/Users/dev/ws/github/rust-openssl/openssl-sys)`

Caused by:
  process didn't exit successfully: `/Users/dev/ws/github/rust-openssl/target/debug/build/openssl-sys-e0f8d2df305985ab/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_LIB_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = aarch64-apple-darwin
  $TARGET = aarch64-apple-darwin
  openssl-sys = 0.9.60

  ', openssl-sys/build/find_normal.rs:173:5
  stack backtrace:
     0: std::panicking::begin_panic
               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:521:12
     1: build_script_main::find_normal::find_openssl_dir
               at ./build/find_normal.rs:173:5
     2: build_script_main::find_normal::get_openssl::{{closure}}
               at ./build/find_normal.rs:15:68
     3: core::option::Option<T>::unwrap_or_else
               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:427:21
     4: build_script_main::find_normal::get_openssl
               at ./build/find_normal.rs:15:31
     5: build_script_main::find_openssl
               at ./build/main.rs:55:5
     6: build_script_main::main
               at ./build/main.rs:63:34
     7: core::ops::function::FnOnce::call_once
               at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I am not sure if this crate should work out of the box on a fresh macOS Big Sur/Apple Silicon installation.

If you have to install _openssl_ via Homebrew/Macports/etc. beforehand then please update the error message and/or mention/link to https://docs.rs/openssl/0.10.32/openssl/#automatic

**Comment by sfackler** [comment]
You do need to install OpenSSL. In the link you posted:

> Thee openssl-sys crate will automatically detect OpenSSL installations via Homebrew on macOS

**Comment by sdavids** [comment]
In that case it would be nice if the error message would be updated or contained the link.

**Comment by conanbatt** [comment]
I'm running into this issue even with openssl installed:

```
brew install openssl
Warning: openssl@1.1 1.1.1i is already installed and up-to-date.
```

In this case installing for linux targets:
```
  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-musl
  openssl-sys = 0.9.60
```

**Comment by sfackler** [comment]
The version of OpenSSL that homebrew installs is not for linux. If you want to cross compile you will need a cross compiled OpenSSL.
