### ISSUE TITLE
Does not compile on Arm64  / Debian

### ISSUE THREAD

**Issue by l1x** [sfackler/rust-openssl#1446]
I am not sure how to tell what is wrong:

```
   Compiling structopt v0.3.21
error: failed to run custom build command for `openssl-sys v0.9.61`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install3ilzXv/release/build/openssl-sys-0665a2a6a85a8129/build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_aarch64-unknown-linux-gnu = None
  CC_aarch64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_aarch64-unknown-linux-gnu = None
  CFLAGS_aarch64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = None
  running "perl" "./Configure" "--prefix=/tmp/cargo-install3ilzXv/release/build/openssl-sys-fa76347495fe3703/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-aarch64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC"
  Configuring OpenSSL version 1.1.1k (0x101010bfL) for linux-aarch64
  Using os-specific seed configuration
  Creating configdata.pm
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL file first)         ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  perl: warning: Setting locale failed.
  perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "UTF-8",
        LC_TERMINAL = "iTerm2",
        LANG = "en_US.utf-8"
      are supported and installed on your system.
  perl: warning: Falling back to the standard locale ("C").
  perl: warning: Setting locale failed.
  perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "UTF-8",
        LC_TERMINAL = "iTerm2",
        LANG = "en_US.utf-8"
      are supported and installed on your system.
  perl: warning: Falling back to the standard locale ("C").
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/l1x/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.15.0+1.1.1k/src/lib.rs:469:39
  stack backtrace:
     0:     0xaaaae1b72fcc - std::backtrace_rs::backtrace::libunwind::trace::h9084dae7a7332a8c
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0xaaaae1b72fcc - std::backtrace_rs::backtrace::trace_unsynchronized::h2377cbb17216fe80
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0xaaaae1b72fcc - std::sys_common::backtrace::_print_fmt::he896a6d420ef4507
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
     3:     0xaaaae1b72fcc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4ed931a697aec4d
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
     4:     0xaaaae1b8d7b8 - core::fmt::write::hce490866ebb7b066
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
     5:     0xaaaae1b6f364 - std::io::Write::write_fmt::hc305428e324737a5
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
     6:     0xaaaae1b759fc - std::sys_common::backtrace::_print::h699e50fd0c0840c8
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
     7:     0xaaaae1b759fc - std::sys_common::backtrace::print::h717bd21ff780b90e
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
     8:     0xaaaae1b759fc - std::panicking::default_hook::{{closure}}::h6874e771e1f74ac7
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
     9:     0xaaaae1b75570 - std::panicking::default_hook::hc618054a7378fa55
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
    10:     0xaaaae1b7617c - std::panicking::rust_panic_with_hook::h75d510e06b5ae0d5
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
    11:     0xaaaae1b75cfc - std::panicking::begin_panic_handler::{{closure}}::h85464207e28d186e
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
    12:     0xaaaae1b73458 - std::sys_common::backtrace::__rust_end_short_backtrace::h84f042552d2bbf2e
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
    13:     0xaaaae1b75c64 - rust_begin_unwind
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
    14:     0xaaaae1b8cb98 - core::panicking::panic_fmt::h34a018aff744b57d
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
    15:     0xaaaae1b8ca64 - core::option::expect_none_failed::hf07bd559510f7ff7
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
    16:     0xaaaae1afc484 - core::result::Result<T,E>::unwrap::h82a2840451c63396
    17:     0xaaaae1afb0c4 - openssl_src::Build::run_command::h73cca469454d2972
    18:     0xaaaae1afa4c0 - openssl_src::Build::build::h415b5073387bd70e
    19:     0xaaaae1ad6d4c - build_script_main::find_vendored::get_openssl::h270cd8a024910a69
    20:     0xaaaae1acd8e0 - build_script_main::find_openssl::hdde9f9e7dc736efb
    21:     0xaaaae1acd9d8 - build_script_main::main::hc748efdfc645846f
    22:     0xaaaae1ad28d0 - core::ops::function::FnOnce::call_once::h888fe3747d157351
    23:     0xaaaae1ad1824 - std::sys_common::backtrace::__rust_begin_short_backtrace::h817baf0d2a1953d0
    24:     0xaaaae1ad7084 - std::rt::lang_start::{{closure}}::h695113ee295483b1
    25:     0xaaaae1b764f8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd34202797d0377fb
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
    26:     0xaaaae1b764f8 - std::panicking::try::do_call::hc0849ce796e43a92
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
    27:     0xaaaae1b764f8 - std::panicking::try::h8a3066153f72d673
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
    28:     0xaaaae1b764f8 - std::panic::catch_unwind::hb68ca084e373d0e1
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
    29:     0xaaaae1b764f8 - std::rt::lang_start_internal::ha7e3915fcdc7c7d8
                                 at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
    30:     0xaaaae1ad7060 - std::rt::lang_start::h4ff0522313d55817
    31:     0xaaaae1ad049c - main
    32:     0xffff9fd05218 - __libc_start_main
    33:     0xaaaae1ac9eb4 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-deny v0.6.2`, intermediate artifacts can be found at `/tmp/cargo-install3ilzXv`

Caused by:
  build failed
```

**Comment by sfackler** [comment]
You need to install make.

**Comment by l1x** [comment]
> You need to install make.

Thanks @sfackler. How do I need to figure that out next time? Is there a way to identify that make is missing or the only indication is:

```
  running "make" "depend"
```

**Comment by sfackler** [comment]
That would be the way currently, but the openssl-src crate's logic could be improved to add the command to the error its throwing.
