### ISSUE TITLE
DTLS Acceptor.accept() panicked at 'source slice length (230) does not match destination slice length (16717)'

### ISSUE THREAD

**Issue by rainerschoe** [sfackler/rust-openssl#1481]
Hi, I am trying to build an DTLS server, however openssl crate panics inside acceptor.accept(client):
```
> RUST_BACKTRACE=full ./server
Hello, world!
new client 127.0.0.1:3400
thread '<unnamed>' panicked at 'source slice length (230) does not match destination slice length (16717)', /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3052:13
stack backtrace:
   0:     0x558d44913110 - std::backtrace_rs::backtrace::libunwind::trace::h1037ca7e6eeef65c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x558d44913110 - std::backtrace_rs::backtrace::trace_unsynchronized::haaefac1bc3669450
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558d44913110 - std::sys_common::backtrace::_print_fmt::h863a6f5e6d995885
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558d44913110 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h767e17e1aa7df6a8
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558d4492e6ac - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/fmt/mod.rs:1110:17
   5:     0x558d4490e025 - std::io::Write::write_fmt::h4c802b6f761026c1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/io/mod.rs:1590:15
   6:     0x558d4491509b - std::sys_common::backtrace::_print::h2769edb26a7eb606
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558d4491509b - std::sys_common::backtrace::print::ha71f3549862b4cb6
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558d4491509b - std::panicking::default_hook::{{closure}}::h95488a3bade217f6
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:208:50
   9:     0x558d44914b71 - std::panicking::default_hook::h290aa602c0fb11df
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:225:9
  10:     0x558d44915741 - std::panicking::rust_panic_with_hook::hf32c4fa635e215f2
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:622:17
  11:     0x558d44915247 - std::panicking::begin_panic_handler::{{closure}}::h95197ccd88846f7a
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:519:13
  12:     0x558d449135ec - std::sys_common::backtrace::__rust_end_short_backtrace::h7641df9566f7b7d0
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558d449151a9 - rust_begin_unwind
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:515:5
  14:     0x558d447cf2f1 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/panicking.rs:92:14
  15:     0x558d447cf5c2 - core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail::h5656d919d719ae34
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3045:13
  16:     0x558d448f6d56 - core::slice::<impl [T]>::copy_from_slice::h7a5b9f3980e49687
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3052:13
  17:     0x558d447deb2e - <[T] as core::slice::CloneFromSpec<T>>::spec_clone_from::h1993d1d5a9fa7bf3
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3511:9
  18:     0x558d447deafd - core::slice::<impl [T]>::clone_from_slice::h89a7bef0fb0fff03
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:2976:9
  19:     0x558d447d9e58 - <server::Client as std::io::Read>::read::hdb532b9011db5358
                               at /home/rainer/projects/svpn/src/bin/server.rs:33:9
  20:     0x558d447d6d8a - openssl::ssl::bio::bread::{{closure}}::h5da6d610125350cb
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/bio.rs:116:44
  21:     0x558d44802133 - core::ops::function::FnOnce::call_once::h09205c196d2f0d86
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/ops/function.rs:227:5
  22:     0x558d447db38b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h092263bfc9535a36
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:346:9
  23:     0x558d447f8b67 - std::panicking::try::do_call::hd13ce476b3db6a71
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:401:40
  24:     0x558d447f91dd - __rust_try
  25:     0x558d447f838f - std::panicking::try::h5b84c657717c24ff
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:365:19
  26:     0x558d447db5da - std::panic::catch_unwind::h9990aca72ab1b547
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:433:14
  27:     0x558d447d6b14 - openssl::ssl::bio::bread::h69a5b7dcf323a9bb
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/bio.rs:116:11
  28:     0x7f99ffce2e7a - <unknown>
  29:     0x7f99ffce1d04 - <unknown>
  30:     0x7f99ffce22e3 - BIO_read
  31:     0x7f99fff3b3f2 - <unknown>
  32:     0x7f99fff40d6a - <unknown>
  33:     0x7f99fff39f74 - <unknown>
  34:     0x7f99fff6e1c6 - <unknown>
  35:     0x7f99fff65e31 - <unknown>
  36:     0x558d4480192c - openssl::ssl::SslStream<S>::accept::h15fc819abbf5f1a2
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/mod.rs:3611:28
  37:     0x558d44801bad - openssl::ssl::SslStreamBuilder<S>::accept::hf455acedeae931b2
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/mod.rs:3940:15
  38:     0x558d44801e8f - openssl::ssl::Ssl::accept::h2beda16cb745c06d
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/mod.rs:2440:9
  39:     0x558d447d944b - openssl::ssl::connector::SslAcceptor::accept::h8ff0f4e5d7ba0693
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.34/src/ssl/connector.rs:321:9
  40:     0x558d447e405d - server::main::{{closure}}::{{closure}}::hf5861b4ea1fdb94c
                               at /home/rainer/projects/svpn/src/bin/server.rs:194:30
  41:     0x558d447e0af0 - std::sys_common::backtrace::__rust_begin_short_backtrace::hbba05e89a2916c58
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:125:18
  42:     0x558d447e90ec - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4332fe3473d8ddd6
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/thread/mod.rs:481:17
  43:     0x558d447db4a0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h68884ef51a405972
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:346:9
  44:     0x558d447f8967 - std::panicking::try::do_call::h2a7345c98e3639a9
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:401:40
  45:     0x558d447f91dd - __rust_try
  46:     0x558d447f84f1 - std::panicking::try::h5fe939d894a9733a
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:365:19
  47:     0x558d447db640 - std::panic::catch_unwind::hf08f97d1661eb7c5
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:433:14
  48:     0x558d447e8f00 - std::thread::Builder::spawn_unchecked::{{closure}}::hc2898e592811ed1d
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/thread/mod.rs:480:30
  49:     0x558d4480208e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h3c58c8c41d9b49d3
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/ops/function.rs:227:5
  50:     0x558d449188e7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h902e2cf6655e1b0c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/alloc/src/boxed.rs:1575:9
  51:     0x558d449188e7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h893a5452154309d1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/alloc/src/boxed.rs:1575:9
  52:     0x558d449188e7 - std::sys::unix::thread::Thread::new::thread_start::hdedcb57c96ab37cd
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys/unix/thread.rs:71:17
  53:     0x7f99ffc08259 - start_thread
  54:     0x7f99ff9e45e3 - __GI___clone
  55:                0x0 - <unknown>
```

My server main code looks like this:
```
#[tokio::main]
async fn main()  -> std::io::Result<()>{
    println!("Hello, world!");
    let socket = Arc::new(tokio::net::UdpSocket::bind("127.0.0.1:5000").await?);
    
    let (sender, receiver) = tokio::sync::mpsc::channel(100);
    let (mut udp_dispatcher, mut client_receiver) = UdpDispatcher::create(socket.clone(), sender);
    let mut udp_transmitter = UdpTransmitter{tx_receiver: receiver, socket: socket};

    tokio::spawn(async move {
            // Process each socket concurrently.
            udp_dispatcher.handle_rx().await
        });

    tokio::spawn(async move {
            // Process each socket concurrently.
            udp_transmitter.handle_tx().await
        });

    let mut acceptor = SslAcceptor::mozilla_intermediate(SslMethod::dtls()).unwrap();
    acceptor.set_private_key_file("../../certs/server_key.pem", SslFiletype::PEM).unwrap();
    acceptor.set_certificate_chain_file("../../certs/server_crt.pem").unwrap();
    acceptor.check_private_key().unwrap();
    let acceptor = Arc::new(acceptor.build());
    
    loop
    {
        if let Some(client) = client_receiver.recv().await
        {
            println!("new client {}", client.addr);
            let acceptor = acceptor.clone();
            thread::spawn(move || {
                let stream = acceptor.accept(client).unwrap();
                handle_client(stream);
            });
        }
    }
}
```

I think the crate should not cause a panic. this looks like a bug.

**Comment by sfackler** [comment]
The panic is coming from your code:

```
  19:     0x558d447d9e58 - <server::Client as std::io::Read>::read::hdb532b9011db5358
                               at /home/rainer/projects/svpn/src/bin/server.rs:33:9
```

**Comment by rainerschoe** [comment]
Thank you for the quick reply.
This is somehow embarrassing.
Sorry for the trouble, I am quite new to rust and seemingly misread the backtrace. Need to read it more carefully and better understand how rust panic handling works.

Sorry again for opening stupid issue :P

**Comment by rainerschoe** [comment]
Ok, I fully understand the backtrace now, I overlooked frame 19 in which openssl crate ic calling my code and was confused by all the panic handling frames :P
This is obviously user-error. Closing this issue. Thanks again @sfackler for pointing this out :P really embarrassing.
