### ISSUE TITLE
Project in MacOS not building for android anymore due to openSSL

### ISSUE THREAD

**Issue by nmpribeiro** [sfackler/rust-openssl#1511]
Hi, I have the following error message when I try to build to android:

```
error: failed to run custom build command for `openssl-sys v0.9.65`

Caused by:
  process didn't exit successfully: `/Users/<USER>/work/rust_sandbox/<PROJECT>/target/debug/build/openssl-sys-01132c0b5e4417cb/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIB_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_INCLUDE_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARMV7_LINUX_ANDROIDEABI_OPENSSL_DIR
  ARMV7_LINUX_ANDROIDEABI_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7-linux-androideabi
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7_linux_androideabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7-linux-androideabi
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7_linux_androideabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7-linux-androideabi
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7_linux_androideabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\n                Install a sysroot for the target platform and configure it via\n                PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\n                cross-compiling wrapper for pkg-config and set it via\n                PKG_CONFIG environment variable."

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-apple-darwin
  $TARGET = armv7-linux-androideabi
  openssl-sys = 0.9.65

  ', /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/find_normal.rs:174:5
  stack backtrace:
     0:        0x108b69424 - std::backtrace_rs::backtrace::libunwind::trace::h4cbd7989526f0637
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:        0x108b69424 - std::backtrace_rs::backtrace::trace_unsynchronized::hdd2d31947a2a25cb
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x108b69424 - std::sys_common::backtrace::_print_fmt::he03430c1369c45a7
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:67:5
     3:        0x108b69424 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf479dd487b623c5f
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:46:22
     4:        0x108b848fc - core::fmt::write::h8160330c41daaf61
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/core/src/fmt/mod.rs:1117:17
     5:        0x108b660aa - std::io::Write::write_fmt::h2c9315db2d27960e
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/io/mod.rs:1667:15
     6:        0x108b6ae3f - std::sys_common::backtrace::_print::hca55aaf1d224df10
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:49:5
     7:        0x108b6ae3f - std::sys_common::backtrace::print::hef9f16de5f26775d
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:36:9
     8:        0x108b6ae3f - std::panicking::default_hook::{{closure}}::h583fb652f5c58b48
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:210:50
     9:        0x108b6a9e6 - std::panicking::default_hook::h1d01fcd3894dae52
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:227:9
    10:        0x108b6b540 - std::panicking::rust_panic_with_hook::h013ca0228b580e94
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:624:17
    11:        0x108b6afe5 - std::panicking::begin_panic_handler::{{closure}}::h851d3f5f9017436b
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:521:13
    12:        0x108b698d8 - std::sys_common::backtrace::__rust_end_short_backtrace::h83695ce1e08cc610
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:141:18
    13:        0x108b6af4a - rust_begin_unwind
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:517:5
    14:        0x108b8c3bb - std::panicking::begin_panic_fmt::hc639b8142a2a7ab1
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:460:5
    15:        0x108abfbdc - build_script_main::find_normal::find_openssl_dir::hfb302c9f0e52d713
                                 at /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/find_normal.rs:174:5
    16:        0x108abeb72 - build_script_main::find_normal::get_openssl::{{closure}}::hf22735764a095f52
                                 at /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/find_normal.rs:15:68
    17:        0x108ac1a19 - core::option::Option<T>::unwrap_or_else::he8386b75c497c330
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/core/src/option.rs:776:21
    18:        0x108abe92f - build_script_main::find_normal::get_openssl::hf659a55087901ce9
                                 at /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/find_normal.rs:15:31
    19:        0x108ab6cfc - build_script_main::find_openssl::h4bee0f6ce6263eb9
                                 at /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/main.rs:55:5
    20:        0x108ab6d90 - build_script_main::main::h026c61719b06aa3f
                                 at /Users/<USER>/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.65/build/main.rs:63:34
    21:        0x108ac068e - core::ops::function::FnOnce::call_once::h294178fc4870c985
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/core/src/ops/function.rs:227:5
    22:        0x108abc7a1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h065056e18d43724f
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/sys_common/backtrace.rs:125:18
    23:        0x108abc054 - std::rt::lang_start::{{closure}}::hf84faf94c8d8f2e1
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/rt.rs:63:18
    24:        0x108b6b989 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf317275e349059d3
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/core/src/ops/function.rs:259:13
    25:        0x108b6b989 - std::panicking::try::do_call::haeee949c270f9273
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:403:40
    26:        0x108b6b989 - std::panicking::try::h8377f9af0f41c7b0
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:367:19
    27:        0x108b6b989 - std::panic::catch_unwind::h08067a92161857d7
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panic.rs:129:14
    28:        0x108b6b989 - std::rt::lang_start_internal::{{closure}}::hcdb4ab2de61cfd3b
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/rt.rs:45:48
    29:        0x108b6b989 - std::panicking::try::do_call::h7f00201ac84d3af5
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:403:40
    30:        0x108b6b989 - std::panicking::try::h4a3d9151b1d0303d
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panicking.rs:367:19
    31:        0x108b6b989 - std::panic::catch_unwind::h1381f1061724b0d8
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/panic.rs:129:14
    32:        0x108b6b989 - std::rt::lang_start_internal::h595027ae4edbf387
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/rt.rs:45:20
    33:        0x108abc01e - std::rt::lang_start::h2efaee907243cfde
                                 at /rustc/ad981d58e1ca16bcf4072577934630deb11c5e14/library/std/src/rt.rs:62:5
    34:        0x108aba456 - _main
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Command `cargo build --target armv7-linux-androideabi` had a non-zero exit code
```

I am using `sentry` version `0.23.0` which in turn uses this package. I have tried to add
```
# export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
# export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib
```
but then I break the linkage, as I suspect it is trying to combine c lib for Mac in an android arch lib. However, this is quite annoying. I can build my app if I comment `sentry`.

**Comment by sfackler** [comment]
If you want to cross compile to Android you will need to have a copy of OpenSSL cross compiled to Android. Alternatively, you can ask the crate to build a copy for you by enabling the `vendored` feature.

**Comment by nmpribeiro** [comment]
@sfackler , thanks! using `openssl = {version = "0.10.35", features = ["vendored"]}` fixed the problem. I love how cargo resolves dependencies 👍
