### ISSUE TITLE
panic on printing SSL error with openssl 3.0

### ISSUE THREAD

**Issue by georgmu** [sfackler/rust-openssl#1659]
the following minimal example triggers a panic when using openssl 3.0:
```
fn main() {
    // IP is from github.com - try to connect via IP to cause a certificate error
    let response = reqwest::blocking::get("https://140.82.121.4/");

    if let Err(e) = response {
        println!("Error: {}", e)
    }
}
```

No problem with openssl 1.1:
```
Error: error sending request for url (https://140.82.121.4/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1914: (IP address mismatch)
```

When running this example with openssl 3, I get the following output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 1, error_len: Some(1) }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.40/src/error.rs:244:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: error sending request for url (https://140.82.121.4/): error trying to connect: error:0A000086:SSL routines:³"TD:certificate verify failed
```

The relevant parts of the backtrace:
```
   0: rust_begin_unwind
             at /build/rustc-60tkWq/rustc-1.59.0+dfsg1/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /build/rustc-60tkWq/rustc-1.59.0+dfsg1/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /build/rustc-60tkWq/rustc-1.59.0+dfsg1/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /build/rustc-60tkWq/rustc-1.59.0+dfsg1/library/core/src/result.rs:1018:23
   4: openssl::error::Error::function
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.40/src/error.rs:223:18
   5: <openssl::error::Error as core::fmt::Display>::fmt
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.40/src/error.rs:289:15
   ...
```

The data is correct when breaking in error.rs:117 (inside ERR_get_error_all match block), but it seems the values for file and func are not owned and get freed .

valgrind also shows invalid read errors
```
Invalid read of size 1
   at 0x484ED16: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x3AA436: std::ffi::c_str::CStr::from_ptr (c_str.rs:1191)
   by 0x3AB9B6: openssl::error::Error::function (error.rs:222)
   by 0x3AC215: <openssl::error::Error as core::fmt::Display>::fmt (error.rs:289)
   by 0x3AD286: <&T as core::fmt::Display>::fmt (mod.rs:2106)
   by 0x64E10B: core::fmt::write (mod.rs:1168)
   by 0x64F023: core::fmt::Formatter::write_fmt (mod.rs:1622)
   by 0x3AB540: <openssl::error::ErrorStack as core::fmt::Display>::fmt (error.rs:70)
   by 0x3AD2B6: <&T as core::fmt::Display>::fmt (mod.rs:2106)
   by 0x64E10B: core::fmt::write (mod.rs:1168)
   by 0x64F023: core::fmt::Formatter::write_fmt (mod.rs:1622)
   by 0x3B2C9F: <openssl::ssl::error::Error as core::fmt::Display>::fmt (error.rs:117)
 Address 0x6b02280 is 0 bytes inside a block of size 36 free'd
   at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4A77D1E: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
   by 0x4AC63A3: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
   by 0x4ACA5F6: ??? (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
   by 0x4EE7710: __nptl_deallocate_tsd (nptl_deallocate_tsd.c:73)
   by 0x4EE7710: __nptl_deallocate_tsd (nptl_deallocate_tsd.c:22)
   by 0x4EEA9C9: start_thread (pthread_create.c:453)
   by 0x4F7BBB3: clone (clone.S:100)
 Block was alloc'd at
   at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x4AC308A: CRYPTO_strdup (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
   by 0x4A78C5F: ERR_set_debug (in /usr/lib/x86_64-linux-gnu/libcrypto.so.3)
   by 0x48CD8CA: ??? (in /usr/lib/x86_64-linux-gnu/libssl.so.3)
   by 0x48CAB8B: ??? (in /usr/lib/x86_64-linux-gnu/libssl.so.3)
   by 0x48CC607: ??? (in /usr/lib/x86_64-linux-gnu/libssl.so.3)
   by 0x38998B: openssl::ssl::SslStream<S>::do_handshake (mod.rs:3229)
   by 0x37C933: openssl::ssl::MidHandshakeSslStream<S>::handshake (mod.rs:3057)
   by 0x311EBF: native_tls::imp::MidHandshakeTlsStream<S>::handshake (openssl.rs:235)
   by 0x2B3E7F: native_tls::MidHandshakeTlsStream<S>::handshake (lib.rs:255)
   by 0x2B3A25: <tokio_native_tls::MidHandshake<S> as core::future::future::Future>::poll (lib.rs:348)
   by 0x2B194B: tokio_native_tls::handshake::{{closure}} (lib.rs:237)
```

**Comment by georgmu** [comment]
I reran valgrind with debug syms installed:
```
Invalid read of size 1
   at 0x484B5F6: strlen (vg_replace_strmem.c:495)
   by 0x3B5226: core::ffi::c_str::CStr::from_ptr (c_str.rs:249)
   by 0x3B13D6: openssl::error::Error::function (error.rs:222)
   by 0x3B1BC7: <openssl::error::Error as core::fmt::Display>::fmt (error.rs:289)
   by 0x3B0016: <&T as core::fmt::Display>::fmt (mod.rs:2134)
   by 0x661DFB: core::fmt::write (mod.rs:1196)
   by 0x662D03: core::fmt::Formatter::write_fmt (mod.rs:1650)
   by 0x3B0F31: <openssl::error::ErrorStack as core::fmt::Display>::fmt (error.rs:70)
   by 0x3B0046: <&T as core::fmt::Display>::fmt (mod.rs:2134)
   by 0x661DFB: core::fmt::write (mod.rs:1196)
   by 0x662D03: core::fmt::Formatter::write_fmt (mod.rs:1650)
   by 0x3B91D1: <openssl::ssl::error::Error as core::fmt::Display>::fmt (error.rs:117)
 Address 0x6a04600 is 0 bytes inside a block of size 36 free'd
   at 0x48480E4: free (vg_replace_malloc.c:872)
   by 0x4A81BCE: UnknownInlinedFun (err_local.h:88)
   by 0x4A81BCE: UnknownInlinedFun (err.c:201)
   by 0x4A81BCE: UnknownInlinedFun (err.c:194)
   by 0x4A81BCE: err_delete_thread_state (err.c:622)
   by 0x4ACE733: init_thread_stop.part.0 (initthread.c:336)
   by 0x4AD44C6: UnknownInlinedFun (initthread.c:317)
   by 0x4AD44C6: init_thread_destructor (initthread.c:196)
   by 0x4ECF010: __nptl_deallocate_tsd (nptl_deallocate_tsd.c:73)
   by 0x4ECF010: __nptl_deallocate_tsd (nptl_deallocate_tsd.c:22)
   by 0x4ED1CAD: start_thread (pthread_create.c:453)
   by 0x4F567D3: clone (clone.S:100)
 Block was alloc'd at
   at 0x484586F: malloc (vg_replace_malloc.c:381)
   by 0x4ACCBE9: CRYPTO_strdup (o_str.c:24)
   by 0x4A82AFF: UnknownInlinedFun (err_local.h:66)
   by 0x4A82AFF: ERR_set_debug (err_blocks.c:37)
   by 0x48DF32A: UnknownInlinedFun (statem_clnt.c:1887)
   by 0x48DF32A: ossl_statem_client_post_process_message (statem_clnt.c:1085)
   by 0x48DBA27: UnknownInlinedFun (statem.c:675)
   by 0x48DBA27: state_machine (statem.c:442)
   by 0x383D2B: openssl::ssl::SslStream<S>::do_handshake (mod.rs:3229)
   by 0x3857E3: openssl::ssl::MidHandshakeSslStream<S>::handshake (mod.rs:3057)
   by 0x2F50FF: native_tls::imp::MidHandshakeTlsStream<S>::handshake (openssl.rs:235)
   by 0x2AB36F: native_tls::MidHandshakeTlsStream<S>::handshake (lib.rs:255)
   by 0x2D120E: <tokio_native_tls::MidHandshake<S> as core::future::future::Future>::poll (lib.rs:348)
   by 0x2B201C: tokio_native_tls::handshake::{{closure}} (lib.rs:237)
   by 0x242154: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (mod.rs:91)
```
