### ISSUE TITLE
Error when trying to build `arm-unknown-linux-gnueabi`

### ISSUE THREAD

**Issue by InfinityDevTech** [sfackler/rust-openssl#1737]
Hello!

When I have openSSL installed and available it still fails to find the directory for some odd reason.

```
Caused by:
  process didn't exit successfully: `S:\FRC\Bot\target\debug\build\openssl-sys-4f8a26e1cbf03225\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_LIB_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_INCLUDE_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_arm-unknown-linux-gnueabi
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_arm_unknown_linux_gnueabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_arm-unknown-linux-gnueabi
  cargo:rerun-if-env-changed=PKG_CONFIG_arm_unknown_linux_gnueabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_arm-unknown-linux-gnueabi
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_arm_unknown_linux_gnueabi
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."
  note: vcpkg did not find openssl: the vcpkg-rs Vcpkg build helper can only find libraries built for the MSVC ABI.

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-pc-windows-msvc
  $TARGET = arm-unknown-linux-gnueabi
  openssl-sys = 0.9.77

  ', C:\Users\jwjoh\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.77\build\find_normal.rs:191:5
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library\core\src\panicking.rs:65
     2: core::panicking::panic_display<alloc::string::String>
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89\library\core\src\panicking.rs:139
     3: build_script_main::find_normal::find_openssl_dir
               at .\build\find_normal.rs:191
     4: build_script_main::find_normal::get_openssl::closure$0
               at .\build\find_normal.rs:15
     5: enum2$<core::option::Option<std::ffi::os_str::OsString> >::unwrap_or_else<std::ffi::os_str::OsString,build_script_main::find_normal::get_openssl::closure_env$0>
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89\library\core\src\option.rs:828
     6: build_script_main::find_normal::get_openssl
               at .\build\find_normal.rs:15
     7: build_script_main::find_openssl
               at .\build\main.rs:60
     8: build_script_main::main
               at .\build\main.rs:80
     9: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89\library\core\src\ops\function.rs:251
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by sfackler** [comment]
If you are cross compiling you need to have a copy of OpenSSL that has been cross compiled.

**Comment by InfinityDevTech** [comment]
Can openSSL even cross compile to that?

**Comment by sfackler** [comment]
Yes, you can run OpenSSL on ARM Linux.

**Comment by InfinityDevTech** [comment]
Ok, time to dig down a rabbit hole of compiling. Thx

**Comment by InfinityDevTech** [comment]
Felt it was unnecessary to create a new issue, so ill post it here instead.

I have built openSSL for my target but now its erroring on the development headers.

```
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_LIB_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_INCLUDE_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_DIR
  ARM_UNKNOWN_LINUX_GNUEABI_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = N:\Downloads\openssl-openssl-3.0.7\openssl-openssl-3.0.7\apps
  cargo:rustc-link-search=native=N:\Downloads\openssl-openssl-3.0.7\openssl-openssl-3.0.7\apps\lib
  cargo:include=N:\Downloads\openssl-openssl-3.0.7\openssl-openssl-3.0.7\apps\include
  cargo:rerun-if-changed=build/expando.c
  OPT_LEVEL = Some("0")
  TARGET = Some("arm-unknown-linux-gnueabi")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_arm-unknown-linux-gnueabi
  CC_arm-unknown-linux-gnueabi = None
  cargo:rerun-if-env-changed=CC_arm_unknown_linux_gnueabi
  CC_arm_unknown_linux_gnueabi = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some("C:\\MinGW\\bin\\gcc.exe")
  cargo:rerun-if-env-changed=CFLAGS_arm-unknown-linux-gnueabi
  CFLAGS_arm-unknown-linux-gnueabi = None
  cargo:rerun-if-env-changed=CFLAGS_arm_unknown_linux_gnueabi
  CFLAGS_arm_unknown_linux_gnueabi = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("aclass,d32,dsp,llvm14-builtins-abi,neon,thumb2,v5te,v6,v6k,v6t2,v7,vfp2,vfp3")
  running: "C:\\MinGW\\bin\\gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-march=armv6" "-marm" "-mfloat-abi=soft" "-I" "N:\\Downloads\\openssl-openssl-3.0.7\\openssl-openssl-3.0.7\\apps\\include" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=gcc.exe: error: unrecognized command line option '-marm'; did you mean '-mabm'?
  cargo:warning=gcc.exe: error: unrecognized command line option '-mfloat-abi=soft'
  exit code: 1

  --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"C:\\\\MinGW\\\\bin\\\\gcc.exe\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-gdwarf-4\" \"-fno-omit-frame-pointer\" \"-march=armv6\" \"-marm\" \"-mfloat-abi=soft\" \"-I\" \"N:\\\\Downloads\\\\openssl-openssl-3.0.7\\\\openssl-openssl-3.0.7\\\\apps\\\\include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"gcc.exe\" did not execute successfully (status code exit code: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel
      # On Alpine Linux
      apk add openssl-dev

  See rust-openssl documentation for more information:

      https://docs.rs/openssl
  ', C:\Users\jwjoh\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.77\build/main.rs:185:13
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89/library\core\src\panicking.rs:65
     2: build_script_main::validate_headers
               at .\build\main.rs:185
     3: build_script_main::postprocess
               at .\build\main.rs:154
     4: build_script_main::main
               at .\build\main.rs:100
     5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/77e57db384aca99444c3b5f6a9c86bc58a804d89\library\core\src\ops\function.rs:251
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by InfinityDevTech** [comment]
Sorry to bother you about this sfackler, there's just so little documentation and I'm kinda new to figuring this out

**Comment by sfackler** [comment]
You need to install a compiler that can target that platform.

**Comment by InfinityDevTech** [comment]
I have one, how do i specify it?

**Comment by InfinityDevTech** [comment]
Because it seems that openssl-sys uses its own settings

**Comment by sfackler** [comment]
The compiler is picked up from the cc crate: https://github.com/rust-lang/cc-rs#external-configuration-via-environment-variables

**Comment by InfinityDevTech** [comment]
Alright, so im using the compiler that is meant for that platform, but it seems to be unable to include the files. 
```
 CARGO_CFG_TARGET_FEATURE = Some("aclass,d32,dsp,llvm14-builtins-abi,neon,thumb2,v5te,v6,v6k,v6t2,v7,vfp2,vfp3")
  running: "C:\\\\roborio\\\\bin\\\\arm-frc2019-linux-gnueabi-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-march=armv6" "-marm" "-mfloat-abi=soft" "-I" "N:\\Downloads\\openssl-openssl-3.0.7\\openssl-openssl-3.0.7\\apps\\include" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=build/expando.c:1:30: fatal error: openssl/opensslv.h: No such file or directory
  cargo:warning= #include <openssl/opensslv.h>
  cargo:warning=                              ^
  cargo:warning=compilation terminated.
  ```

**Comment by InfinityDevTech** [comment]
Im just confused now, everything is compiled for the same target, its all the same dirs and at this point I'm just confused

**Comment by sfackler** [comment]
Does the file `N:\Downloads\openssl-openssl-3.0.7\openssl-openssl-3.0.7\apps\include\openssl\opensslv.h` exist?

**Comment by InfinityDevTech** [comment]
include doesnt have any other dirs 
![explorer_RYENIYkfbp](https://user-images.githubusercontent.com/47366052/203452148-d2118db3-9782-472f-8ae3-39ac9ada49f2.png)

**Comment by sfackler** [comment]
It seems like that is not a standard OpenSSL installation layout then. I'm not sure how you obtained it.
