### ISSUE TITLE
Library Link error on Win10

### ISSUE THREAD

**Issue by dbsxdbsx** [sfackler/rust-openssl#1793]
One of my crates seems to need OpenSSL, then I installed it from here, setting env variable `OPENSSL_DIR` to  `"C:\Program Files\OpenSSL-Win64`, but still it ran into an error:
```
  --- stderr
  thread 'main' panicked at 'OpenSSL libdir at `["C:\\Program Files\\OpenSSL-Win64\\lib"]` does not contain the required files to either statically or dynamically link OpenSSL', C:\Users\dbsx\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.80\build/main.rs:401:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Checking  folder `lib`:

![111](https://user-images.githubusercontent.com/17372655/212672489-4cb6e997-6bcd-41e0-b0ba-4ce52028806d.png)

It seems nothing is wrong.

**Comment by cauedotnet** [comment]
Hi! Any updates on this problem? 
I have the same issue using Win 10 to build an RUST AWS Lambda Function. I've tried a lot of options, reinstalling OpenSSL via exe, choco or StrawberyPerl, setting all env variables, but nothing works. 

![image](https://user-images.githubusercontent.com/10039299/221430377-78a05d15-de47-46dd-a9b6-feda98fef529.png)
![image](https://user-images.githubusercontent.com/10039299/221430362-de10778e-329f-400e-b923-11138b3612fa.png)
 
 --- stderr
  thread 'main' panicked at 'OpenSSL libdir at `["C:\\Program Files\\OpenSSL-Win64\\lib"]` does not contain the required files to either statically or dynamically link OpenSSL', C:\Users\...\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.80\build/main.rs:401:13

Thanks.

**Comment by batleforc** [comment]
In order to fix this problem, I had to directly set **OPENSSL_DIR** in the system property 
- win key
- in the search "environnment" 
- Edit env variable 
- env variable (the last button in the screen) 
- add OPENSSL_DIR has "C:\Program Files\OpenSSL-Win64" in the user var.

**Comment by miaomiaowu0428** [comment]
> 为了解决这个问题，我不得不直接在 system 属性中设置 **OPENSSL_DIR**
> 
> * win 键
> * 在搜索 “environnment”
> * 编辑 env 变量
> * env 变量（屏幕中的最后一个按钮）
> * 添加OPENSSL_DIR在用户变量中具有“C：\Program Files\OpenSSL-Win64”。
> 
> 然后重新启动您的术语。

![image](https://github.com/user-attachments/assets/cc545e27-33e4-4585-b543-bb288e8a06ee)
I do this and "OpenSSL libdir at ["C:\\Program Files\\OpenSSL-Win64\\lib"] does not contain the required files to either statically or dynamically link OpenSSL
" still not solved. Are there any other possible causes?

**Comment by 769344359** [comment]
> > 为了解决这个问题，我不得不直接在 system 属性中设置 **OPENSSL_DIR**
> > 
> > * win 键
> > * 在搜索 “environnment”
> > * 编辑 env 变量
> > * env 变量（屏幕中的最后一个按钮）
> > * 添加OPENSSL_DIR在用户变量中具有“C：\Program Files\OpenSSL-Win64”。
> > 
> > 然后重新启动您的术语。
> 
> ![image](https://private-user-images.githubusercontent.com/103312201/364016345-cc545e27-33e4-4585-b543-bb288e8a06ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc1NDMsIm5iZiI6MTcyNjY0NzI0MywicGF0aCI6Ii8xMDMzMTIyMDEvMzY0MDE2MzQ1LWNjNTQ1ZTI3LTMzZTQtNDU4NS1iNTQzLWJiMjg4ZThhMDZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGEzMWQyZDIxOWQwYmRlZDg5OWFlMTAzNDg5MzIzMWQxNGVlYmU4ZmI1NzA5YWVkMTk0MjEwMTU5ZDMyZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cFz8hmNqhSuE0KqbS8UZ71BVvDW5OIze-GHzNV_FEVo) I do this and "OpenSSL libdir at ["C:\Program Files\OpenSSL-Win64\lib"] does not contain the required files to either statically or dynamically link OpenSSL " still not solved. Are there any other possible causes?
![image](https://github.com/user-attachments/assets/9be62788-0d6e-41d6-bb5a-b0a6ab6664bf)
![image](https://github.com/user-attachments/assets/bbf33b72-d2ff-415a-aaa0-ea430e8a4a31)

try set envirment with 
```
C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD
```

**Comment by davidkhala** [comment]
> > > 为了解决这个问题，我不得不直接在 system 属性中设置 **OPENSSL_DIR**
> > > 
> > > * win 键
> > > * 在搜索 “environnment”
> > > * 编辑 env 变量
> > > * env 变量（屏幕中的最后一个按钮）
> > > * 添加OPENSSL_DIR在用户变量中具有“C：\Program Files\OpenSSL-Win64”。
> > > 
> > > 然后重新启动您的术语。
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/103312201/364016345-cc545e27-33e4-4585-b543-bb288e8a06ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc1NDMsIm5iZiI6MTcyNjY0NzI0MywicGF0aCI6Ii8xMDMzMTIyMDEvMzY0MDE2MzQ1LWNjNTQ1ZTI3LTMzZTQtNDU4NS1iNTQzLWJiMjg4ZThhMDZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGEzMWQyZDIxOWQwYmRlZDg5OWFlMTAzNDg5MzIzMWQxNGVlYmU4ZmI1NzA5YWVkMTk0MjEwMTU5ZDMyZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cFz8hmNqhSuE0KqbS8UZ71BVvDW5OIze-GHzNV_FEVo) I do this and "OpenSSL libdir at ["C:\Program Files\OpenSSL-Win64\lib"] does not contain the required files to either statically or dynamically link OpenSSL " still not solved. Are there any other possible causes?
> > ![image](https://private-user-images.githubusercontent.com/6916712/368482394-9be62788-0d6e-41d6-bb5a-b0a6ab6664bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjMxNTEsIm5iZiI6MTcyNjkyMjg1MSwicGF0aCI6Ii82OTE2NzEyLzM2ODQ4MjM5NC05YmU2Mjc4OC0wZDZlLTQxZDYtYmI1YS1iMGE2YWI2NjY0YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTI0NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFjMDQyNTY0Zjc0MWE5MGQ2MDdjMmVmZDE2MDFmOWFjMzMwYzMyODgzMTkwZmJjNjEzYzhiZjc0ZjYwMjI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NPoJ-Uexl7-DiIzPdt9iuORbrzh3pCcFM4oL4Df4NnU)
> > ![image](https://private-user-images.githubusercontent.com/6916712/368482478-bbf33b72-d2ff-415a-aaa0-ea430e8a4a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjMxNTEsIm5iZiI6MTcyNjkyMjg1MSwicGF0aCI6Ii82OTE2NzEyLzM2ODQ4MjQ3OC1iYmYzM2I3Mi1kMmZmLTQxNWEtYWFhMC1lYTQzMGU4YTRhMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTI0NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlNGEwOTAyMmZiMzJhM2M2ZGRmNDZjYWIwYzU4Mjk5NTkyZWU4NTAxN2IwMmFiODEyMjU1OWM5NDc0MjBlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wA8qlwGoFDBDsXBTwlVbjUnNxXDYsB0G9ao8oc_RdkQ)
> 
> try set envirment with
> 
> ```
> C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD
> ```

This works for me.

**Comment by aarsan** [comment]
This worked for me for my Windows ARM build:

$env:OPENSSL_DIR="C:\Program Files\OpenSSL-Win64-ARM"
$env:OPENSSL_LIB_DIR="C:\Program Files\OpenSSL-Win64-ARM\lib\VC\arm64\MD"

**Comment by cloudhu** [comment]
> > > > 为了解决这个问题，我不得不直接在 system 属性中设置 **OPENSSL_DIR**
> > > > 
> > > > * win 键
> > > > * 在搜索 “environnment”
> > > > * 编辑 env 变量
> > > > * env 变量（屏幕中的最后一个按钮）
> > > > * 添加OPENSSL_DIR在用户变量中具有“C：\Program Files\OpenSSL-Win64”。
> > > > 
> > > > 然后重新启动您的术语。
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/103312201/364016345-cc545e27-33e4-4585-b543-bb288e8a06ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDc1NDMsIm5iZiI6MTcyNjY0NzI0MywicGF0aCI6Ii8xMDMzMTIyMDEvMzY0MDE2MzQ1LWNjNTQ1ZTI3LTMzZTQtNDU4NS1iNTQzLWJiMjg4ZThhMDZlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGEzMWQyZDIxOWQwYmRlZDg5OWFlMTAzNDg5MzIzMWQxNGVlYmU4ZmI1NzA5YWVkMTk0MjEwMTU5ZDMyZjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cFz8hmNqhSuE0KqbS8UZ71BVvDW5OIze-GHzNV_FEVo) I do this and "OpenSSL libdir at ["C:\Program Files\OpenSSL-Win64\lib"] does not contain the required files to either statically or dynamically link OpenSSL " still not solved. Are there any other possible causes?
> > > ![image](https://private-user-images.githubusercontent.com/6916712/368482394-9be62788-0d6e-41d6-bb5a-b0a6ab6664bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjMxNTEsIm5iZiI6MTcyNjkyMjg1MSwicGF0aCI6Ii82OTE2NzEyLzM2ODQ4MjM5NC05YmU2Mjc4OC0wZDZlLTQxZDYtYmI1YS1iMGE2YWI2NjY0YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTI0NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFjMDQyNTY0Zjc0MWE5MGQ2MDdjMmVmZDE2MDFmOWFjMzMwYzMyODgzMTkwZmJjNjEzYzhiZjc0ZjYwMjI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NPoJ-Uexl7-DiIzPdt9iuORbrzh3pCcFM4oL4Df4NnU)
> > > ![image](https://private-user-images.githubusercontent.com/6916712/368482478-bbf33b72-d2ff-415a-aaa0-ea430e8a4a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MjMxNTEsIm5iZiI6MTcyNjkyMjg1MSwicGF0aCI6Ii82OTE2NzEyLzM2ODQ4MjQ3OC1iYmYzM2I3Mi1kMmZmLTQxNWEtYWFhMC1lYTQzMGU4YTRhMzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjFUMTI0NzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRlNGEwOTAyMmZiMzJhM2M2ZGRmNDZjYWIwYzU4Mjk5NTkyZWU4NTAxN2IwMmFiODEyMjU1OWM5NDc0MjBlMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wA8qlwGoFDBDsXBTwlVbjUnNxXDYsB0G9ao8oc_RdkQ)
> > 
> > 
> > try set envirment with
> > ```
> > C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD
> > ```
> 
> This works for me.
> 
> In summary, I [installed the vcpkg from VS 2022](https://devblogs.microsoft.com/cppblog/vcpkg-is-now-included-with-visual-studio/), then set env in powershell:
> 
> ```
> $env:VCPKG_ROOT="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg"
> choco install -y openssl
> $env:OPENSSL_DIR="C:\Program Files\OpenSSL-Win64"
> $env:OPENSSL_LIB_DIR="C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD"
> ```

work For me，thx a lot

**Comment by BadMachine** [comment]
Still doesnt work

`
OpenSSL libdir at `["C:\\Program Files\\OpenSSL-Win64\\lib\\VC\\x64\\MD"]` does not contain the required files to either statically or dynamically link OpenSSL
`

**Comment by poerlang** [comment]
Still doesnt work too
