### ISSUE TITLE
Error Configuring OpenSSL build on Android

### ISSUE THREAD

**Issue by alexandru0-dev** [sfackler/rust-openssl#1833]
Cannot build on android target
(i'm building it on docker and the container has perl installed)

Build file:
```rust
// [build.rs]
// ...
if let Ok(v) = std::env::var("DEP_OPENSSL_VERSION_NUMBER") {
    let version = u64::from_str_radix(&v, 16).unwrap();

    if version >= 0x1_01_01_00_0 {
        println!("cargo:rustc-cfg=openssl111");
    }
}
// ...
```

Cargo.toml
```toml
# ...
[dependencies.openssl]
version = "0.10.45"
features = ["vendored"]
```
Stacktrace:
```rust
running "perl" "./Configure" "--prefix=/app/rust/target/armv7-linux-androideabi/debug/build/openssl-sys-f7833f56ef0c32f8/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer"

  --- stderr
  Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at ./Configure line 15.
  BEGIN failed--compilation aborted at ./Configure line 15.
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=/app/rust/target/armv7-linux-androideabi/debug/build/openssl-sys-f7833f56ef0c32f8/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-stdio" "linux-armv4" "-O2" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer"
      Exit status: exit status: 2


      ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.25.1+1.1.1t/src/lib.rs:509:13
  stack backtrace:
     0:     0x5622bfded3fa - std::backtrace_rs::backtrace::libunwind::trace::h34aec3ef6cd8ad7e
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x5622bfded3fa - std::backtrace_rs::backtrace::trace_unsynchronized::h8035d38698d0f7a8
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x5622bfded3fa - std::sys_common::backtrace::_print_fmt::hff968f6695a1ba22
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x5622bfded3fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7eea0efe77acf1ec
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x5622bfe0e5fe - core::fmt::write::hc553f17407eb0b48
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/fmt/mod.rs:1208:17
     5:     0x5622bfde9a85 - std::io::Write::write_fmt::h62e5f01a089f48c0
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/io/mod.rs:1682:15
     6:     0x5622bfded1c5 - std::sys_common::backtrace::_print::h52d116aff3db4cd1
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x5622bfded1c5 - std::sys_common::backtrace::print::h9e7d2f98fb7af075
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x5622bfdef19f - std::panicking::default_hook::{{closure}}::hf74999dab2d0a95c
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:267:22
     9:     0x5622bfdeeedb - std::panicking::default_hook::hc11ca7d10c44c42f
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:286:9
    10:     0x5622bfdef8ac - std::panicking::rust_panic_with_hook::hdb4da1ae79c845a5
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:688:13
    11:     0x5622bfdef649 - std::panicking::begin_panic_handler::{{closure}}::h02b5b35b126d5cf2
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:579:13
    12:     0x5622bfded8ac - std::sys_common::backtrace::__rust_end_short_backtrace::h6c6853376cf416d1
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:137:18
    13:     0x5622bfdef352 - rust_begin_unwind
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
    14:     0x5622bfd0fa43 - core::panicking::panic_fmt::hfd9e949092070b66
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
    15:     0x5622bfd51afd - openssl_src::Build::run_command::h48bb011ad4ad5a1b
                                 at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.25.1+1.1.1t/src/lib.rs:509:13
    16:     0x5622bfd50ae5 - openssl_src::Build::build::h2cec5c4370a21847
                                 at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.25.1+1.1.1t/src/lib.rs:448:9
    17:     0x5622bfd184c6 - build_script_main::find_vendored::get_openssl::ha67fe606942392d1
                                 at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/find_vendored.rs:5:21
    18:     0x5622bfd11fd2 - build_script_main::find_openssl::h9a8e759d5421ec00
                                 at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/main.rs:57:20
    19:     0x5622bfd12166 - build_script_main::main::h594b07e7be1505ab
                                 at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.80/build/main.rs:80:35
    20:     0x5622bfd1783b - core::ops::function::FnOnce::call_once::he9f02efe6aba7f3a
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
    21:     0x5622bfd15f2e - std::sys_common::backtrace::__rust_begin_short_backtrace::he1e63d98565cafbe
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/sys_common/backtrace.rs:121:18
    22:     0x5622bfd1dca1 - std::rt::lang_start::{{closure}}::hce8751b196fd1ba8
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:166:18
    23:     0x5622bfde530c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h9ab31282e87f134a
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:606:13
    24:     0x5622bfde530c - std::panicking::try::do_call::h42ddf5b01d0b4bc7
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
    25:     0x5622bfde530c - std::panicking::try::hfb70320d7386c61a
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
    26:     0x5622bfde530c - std::panic::catch_unwind::h978c9edbad2bb4d4
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
    27:     0x5622bfde530c - std::rt::lang_start_internal::{{closure}}::h04ede5bd2f26b553
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:48
    28:     0x5622bfde530c - std::panicking::try::do_call::ha6b9da35a0885c93
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
    29:     0x5622bfde530c - std::panicking::try::h3325520cab3a642e
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
    30:     0x5622bfde530c - std::panic::catch_unwind::h160beec6f047175b
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
    31:     0x5622bfde530c - std::rt::lang_start_internal::h79190e3a877a769d
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:148:20
    32:     0x5622bfd1dc7a - std::rt::lang_start::h4d698b0740cc6fca
                                 at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/rt.rs:165:17
    33:     0x5622bfd15f1e - main
    34:     0x7fd4e5454d0a - __libc_start_main
    35:     0x5622bfd0ffaa - _start
    36:                0x0 - <unknown>
```

**Comment by alexandru0-dev** [comment]
Apparently i didn't install lsb-release on the container and this gave me the issue
