### ISSUE TITLE
openssl-sys 0.9.53 fails to build on FreeBSD 14

### ISSUE THREAD

**Issue by yurivict** [sfackler/rust-openssl#2019]
Several Rust ports fail on FreeBSD with the same error:
```
[openssl-sys 0.9.53] running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-O2" "-pipe" "-fstack-protector-strong" "-fno-strict-aliasing" "-I" "/usr/include" "-E" "build/expando.c"
[openssl-sys 0.9.53] cargo:warning=build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
[openssl-sys 0.9.53] cargo:warning=VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
[openssl-sys 0.9.53] cargo:warning=^
[openssl-sys 0.9.53] cargo:warning=build/expando.c:5:23: note: expanded from macro 'VERSION'
[openssl-sys 0.9.53] cargo:warning=#define VERSION(n, v) VERSION2(n, v)
[openssl-sys 0.9.53] cargo:warning=                      ^
[openssl-sys 0.9.53] cargo:warning=build/expando.c:4:43: note: expanded from macro 'VERSION2'
[openssl-sys 0.9.53] cargo:warning=#define VERSION2(n, v) RUST_VERSION_##n##_##v
[openssl-sys 0.9.53] cargo:warning=                                          ^
[openssl-sys 0.9.53] cargo:warning=1 error generated.
[openssl-sys 0.9.53] exit status: 1
[openssl-sys 0.9.53] thread 'main' panicked at '
[openssl-sys 0.9.53] Header expansion error:
[openssl-sys 0.9.53] Error { kind: ToolExecError, message: "Command \"cc\" \"-O2\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-O2\" \"-pipe\" \"-fstack-protector-strong\" \"-fno-strict-aliasing\" \"-I\" \"/usr/include\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }
[openssl-sys 0.9.53] 
[openssl-sys 0.9.53] Failed to find OpenSSL development headers.
[openssl-sys 0.9.53] 
[openssl-sys 0.9.53] You can try fixing this setting the `OPENSSL_DIR` environment variable
[openssl-sys 0.9.53] pointing to your OpenSSL installation or installing OpenSSL headers package
[openssl-sys 0.9.53] specific to your distribution:
[openssl-sys 0.9.53] 
[openssl-sys 0.9.53]     # On Ubuntu
[openssl-sys 0.9.53]     sudo apt-get install libssl-dev
[openssl-sys 0.9.53]     # On Arch Linux
[openssl-sys 0.9.53]     sudo pacman -S openssl
[openssl-sys 0.9.53]     # On Fedora
[openssl-sys 0.9.53]     sudo dnf install openssl-devel
[openssl-sys 0.9.53] 
[openssl-sys 0.9.53] See rust-openssl README for more information:
[openssl-sys 0.9.53] 
[openssl-sys 0.9.53]     https://github.com/sfackler/rust-openssl#linux
[openssl-sys 0.9.53] ', /wrkdirs/usr/ports/www/dot-http/work/dot-http-0.2.0/cargo-crates/openssl-sys-0.9.53/build/main.rs:126:13
[openssl-sys 0.9.53] stack backtrace:
[openssl-sys 0.9.53]    0: rust_begin_unwind
[openssl-sys 0.9.53]    1: core::panicking::panic_fmt
[openssl-sys 0.9.53]    2: build_script_main::validate_headers
[openssl-sys 0.9.53]    3: build_script_main::main
[openssl-sys 0.9.53]    4: core::ops::function::FnOnce::call_once
[openssl-sys 0.9.53] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
The following warnings were emitted during compilation:

warning: build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
warning: VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
warning: ^
warning: build/expando.c:5:23: note: expanded from macro 'VERSION'
warning: #define VERSION(n, v) VERSION2(n, v)
warning:                       ^
warning: build/expando.c:4:43: note: expanded from macro 'VERSION2'
warning: #define VERSION2(n, v) RUST_VERSION_##n##_##v
warning:                                           ^
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.53`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/wrkdirs/usr/ports/www/dot-http/work/target/release/build/openssl-sys-397175a16b52c7c2/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_FREEBSD_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR = /usr/lib
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_FREEBSD_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR = /usr/include
  cargo:rustc-link-search=native=/usr/lib
  cargo:include=/usr/include
  OPT_LEVEL = Some("2")
  TARGET = Some("x86_64-unknown-freebsd")
  HOST = Some("x86_64-unknown-freebsd")
  CC_x86_64-unknown-freebsd = None
  CC_x86_64_unknown_freebsd = None
  HOST_CC = None
  CC = Some("cc")
  CFLAGS_x86_64-unknown-freebsd = None
  CFLAGS_x86_64_unknown_freebsd = None
  HOST_CFLAGS = None
  CFLAGS = Some("-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing ")
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-O2" "-pipe" "-fstack-protector-strong" "-fno-strict-aliasing" "-I" "/usr/include" "-E" "build/expando.c"
  cargo:warning=build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
  cargo:warning=VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
  cargo:warning=^
  cargo:warning=build/expando.c:5:23: note: expanded from macro 'VERSION'
  cargo:warning=#define VERSION(n, v) VERSION2(n, v)
  cargo:warning=                      ^
  cargo:warning=build/expando.c:4:43: note: expanded from macro 'VERSION2'
  cargo:warning=#define VERSION2(n, v) RUST_VERSION_##n##_##v
  cargo:warning=                                          ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O2\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-O2\" \"-pipe\" \"-fstack-protector-strong\" \"-fno-strict-aliasing\" \"-I\" \"/usr/include\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel

  See rust-openssl README for more information:

      https://github.com/sfackler/rust-openssl#linux
  ', /wrkdirs/usr/ports/www/dot-http/work/dot-http-0.2.0/cargo-crates/openssl-sys-0.9.53/build/main.rs:126:13
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: build_script_main::validate_headers
     3: build_script_main::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
warning: `syn` (lib) generated 2 warnings
*** Error code 101
```

For example, the port www/dot-http fails with this error.

**Comment by sfackler** [comment]
What version of OpenSSL is installed? What does `openssl/opensslv.h` look like?

**Comment by durin42** [comment]
`/usr/include/openssl/opensslv.h` from FreeBSD 14.0-RELEASE:
```
/*
 * WARNING: do not edit!
 * Generated by Makefile from include/openssl/opensslv.h.in
 *
 * Copyright 1999-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_OPENSSLV_H
# define OPENSSL_OPENSSLV_H
# pragma once

# ifdef  __cplusplus
extern "C" {
# endif

/*
 * SECTION 1: VERSION DATA.  These will change for each release
 */

/*
 * Base version macros
 *
 * These macros express version number MAJOR.MINOR.PATCH exactly
 */
# define OPENSSL_VERSION_MAJOR  3
# define OPENSSL_VERSION_MINOR  0
# define OPENSSL_VERSION_PATCH  12

/*
 * Additional version information
 *
 * These are also part of the new version scheme, but aren't part
 * of the version number itself.
 */

/* Could be: #define OPENSSL_VERSION_PRE_RELEASE "-alpha.1" */
# define OPENSSL_VERSION_PRE_RELEASE ""
/* Could be: #define OPENSSL_VERSION_BUILD_METADATA "+fips" */
/* Could be: #define OPENSSL_VERSION_BUILD_METADATA "+vendor.1" */
# define OPENSSL_VERSION_BUILD_METADATA ""

/*
 * Note: The OpenSSL Project will never define OPENSSL_VERSION_BUILD_METADATA
 * to be anything but the empty string.  Its use is entirely reserved for
 * others
 */

/*
 * Shared library version
 *
 * This is strictly to express ABI version, which may or may not
 * be related to the API version expressed with the macros above.
 * This is defined in free form.
 */
# define OPENSSL_SHLIB_VERSION 3

/*
 * SECTION 2: USEFUL MACROS
 */

/* For checking general API compatibility when preprocessing */
# define OPENSSL_VERSION_PREREQ(maj,min)                                \
    ((OPENSSL_VERSION_MAJOR << 16) + OPENSSL_VERSION_MINOR >= ((maj) << 16) + (min))

/*
 * Macros to get the version in easily digested string form, both the short
 * "MAJOR.MINOR.PATCH" variant (where MAJOR, MINOR and PATCH are replaced
 * with the values from the corresponding OPENSSL_VERSION_ macros) and the
 * longer variant with OPENSSL_VERSION_PRE_RELEASE_STR and
 * OPENSSL_VERSION_BUILD_METADATA_STR appended.
 */
# define OPENSSL_VERSION_STR "3.0.12"
# define OPENSSL_FULL_VERSION_STR "3.0.12"

/*
 * SECTION 3: ADDITIONAL METADATA
 *
 * These strings are defined separately to allow them to be parsable.
 */
# define OPENSSL_RELEASE_DATE "24 Oct 2023"

/*
 * SECTION 4: BACKWARD COMPATIBILITY
 */

# define OPENSSL_VERSION_TEXT "OpenSSL 3.0.12 24 Oct 2023"

/* Synthesize OPENSSL_VERSION_NUMBER with the layout 0xMNN00PPSL */
# ifdef OPENSSL_VERSION_PRE_RELEASE
#  define _OPENSSL_VERSION_PRE_RELEASE 0x0L
# else
#  define _OPENSSL_VERSION_PRE_RELEASE 0xfL
# endif
# define OPENSSL_VERSION_NUMBER          \
    ( (OPENSSL_VERSION_MAJOR<<28)        \
      |(OPENSSL_VERSION_MINOR<<20)       \
      |(OPENSSL_VERSION_PATCH<<4)        \
      |_OPENSSL_VERSION_PRE_RELEASE )

# ifdef  __cplusplus
}
# endif

# include <openssl/macros.h>
# ifndef OPENSSL_NO_DEPRECATED_3_0
#  define HEADER_OPENSSLV_H
# endif

#endif                          /* OPENSSL_OPENSSLV_H */
```

**Comment by durin42** [comment]
Oh, and that's the OpenSSL from the base OS install - not something from ports or whatever. Happy to do more to help diagnose, I'm just a bit out of my depth with the specific error.

**Comment by sfackler** [comment]
It looks like newer LibreSSL's have switched over to OpenSSL's newer version constant layout - we'll need to update https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/expando.c#L10-L16 to have a VERSION_NEW case for libressl as well.

**Comment by sfackler** [comment]
Ah yeah sorry! I saw BSD and weird build failures and jumped to LibreSSL D:

**Comment by sfackler** [comment]
This is very strange - from the header contents you provided OPENSSL_VERSION_MAJOR is defined, so we should be in the VERSION_NEW case, but the build error clearly shows it sourced from the other case.

Do you see the same error if you just directly run `gcc -E` on https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/expando.c?

**Comment by durin42** [comment]
Well, this is more than a little embarrassing: I had a rogue `gcc` shell script that was in my ~/bin that just did `pwd` and exited nonzero, presumably from some sort of past misadventure trying to debug some haunted build issue. With that gone, I'm able to build both my own project and martinvonz/jj, and both link against libssl and libcrypto, so I suspect this is working.

@yurivict are you still seeing this failure building things from ports?

**Comment by sfackler** [comment]
Ha, that would definitely cause problems!

**Comment by thecaralice** [comment]
Interesting, I get a similar issue on macOS with Nix

<details>
<summary><code>nix log</code></summary>

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/v6lfmz9nb55ic4gj8q5rz4gj11qpigdn-dummy-src
source root is dummy-src
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
[naersk] cargo_version (read): 1.78.0-nightly (7b7af3077 2024-02-17)
[naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
[naersk] cargo_release: --release
[naersk] cargo_options:
[naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
[naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
[naersk] RUST_TEST_THREADS: 8
[naersk] cargo_bins_jq_filter: .
[naersk] cargo_build_output_json (created): /private/tmp/nix-build-silver-deps-2.0.1.drv-0/tmp.5VfQ44zsbV
[naersk] RUSTFLAGS:
[naersk] CARGO_BUILD_RUSTFLAGS:
[naersk] CARGO_BUILD_RUSTFLAGS (updated):  --remap-path-prefix /nix/store/gd18fv10npbjbj91mj51ndvlm235m4vi-crates-io-dependencies=/sources --remap-path-prefix /nix/store/icd6w85y44fc71mid2hiw93fjajgsjx3-git-dependencies=/sources
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
cargo build $cargo_release -j "$NIX_BUILD_CORES" --message-format=$cargo_message_format
warning: `/private/tmp/nix-build-silver-deps-2.0.1.drv-0/dummy-src/.cargo-home/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling autocfg v1.0.0
   Compiling libc v0.2.74
   Compiling cfg-if v0.1.10
   Compiling proc-macro2 v1.0.34
   Compiling unicode-xid v0.2.1
   Compiling pkg-config v0.3.18
   Compiling syn v1.0.82
   Compiling lazy_static v1.4.0
   Compiling maybe-uninit v2.0.0
   Compiling getrandom v0.1.14
   Compiling version_check v0.9.3
   Compiling crossbeam-utils v0.7.2
   Compiling memoffset v0.5.5
   Compiling crossbeam-epoch v0.8.2
   Compiling serde_derive v1.0.114
   Compiling proc-macro-error-attr v1.0.4
   Compiling indexmap v1.6.0
   Compiling ppv-lite86 v0.2.8
   Compiling rayon-core v1.7.1
   Compiling jobserver v0.1.21
   Compiling quote v1.0.10
   Compiling cc v1.0.58
   Compiling rand_core v0.5.1
   Compiling scopeguard v1.1.0
   Compiling tinyvec_macros v0.1.0
   Compiling serde v1.0.114
   Compiling rand_chacha v0.2.2
   Compiling tinyvec v1.6.0
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.12
   Compiling hashbrown v0.7.2
   Compiling log v0.4.11
   Compiling hashbrown v0.9.1
   Compiling memchr v2.4.1
   Compiling bitflags v1.2.1
   Compiling matches v0.1.8
   Compiling openssl-sys v0.9.58
   Compiling libz-sys v1.1.8
   Compiling libssh2-sys v0.2.23
   Compiling unicode-normalization v0.1.21
   Compiling unicode-bidi v0.3.4
   Compiling libgit2-sys v0.14.0+1.5.0
   Compiling crossbeam-deque v0.7.3
   Compiling rand v0.7.3
The following warnings were emitted during compilation:

warning: openssl-sys@0.9.58: build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
warning: openssl-sys@0.9.58: VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
warning: openssl-sys@0.9.58: ^
warning: openssl-sys@0.9.58: build/expando.c:5:23: note: expanded from macro 'VERSION'
warning: openssl-sys@0.9.58: #define VERSION(n, v) VERSION2(n, v)
warning: openssl-sys@0.9.58:                       ^
warning: openssl-sys@0.9.58: build/expando.c:4:43: note: expanded from macro 'VERSION2'
warning: openssl-sys@0.9.58: #define VERSION2(n, v) RUST_VERSION_##n##_##v
warning: openssl-sys@0.9.58:                                           ^
warning: openssl-sys@0.9.58: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.58`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/private/tmp/nix-build-silver-deps-2.0.1.drv-0/dummy-src/target/release/build/openssl-sys-8e282cd4b0bfd191/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_LIB_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=AARCH64_APPLE_DARWIN_OPENSSL_DIR
  AARCH64_APPLE_DARWIN_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-search=native=/nix/store/xz5mqc76y815g71y6fh68f9wld9ddw22-openssl-3.0.13/lib
  cargo:rustc-link-lib=ssl
  cargo:rustc-link-lib=crypto
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("aarch64-apple-darwin")
  CC_aarch64-apple-darwin = None
  CC_aarch64_apple_darwin = None
  HOST_CC = None
  CC = Some("clang")
  CFLAGS_aarch64-apple-darwin = None
  CFLAGS_aarch64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=aarch64-apple-darwin" "-I" "/nix/store/97gixfjyghg4njrylhpzs64m5bhslnd6-openssl-3.0.13-dev/include" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=build/expando.c:10:1: error: pasting formed 'RUST_VERSION_OPENSSL_(', an invalid preprocessing token
  cargo:warning=VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
  cargo:warning=^
  cargo:warning=build/expando.c:5:23: note: expanded from macro 'VERSION'
  cargo:warning=#define VERSION(n, v) VERSION2(n, v)
  cargo:warning=                      ^
  cargo:warning=build/expando.c:4:43: note: expanded from macro 'VERSION2'
  cargo:warning=#define VERSION2(n, v) RUST_VERSION_##n##_##v
  cargo:warning=                                          ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  thread 'main' panicked at /sources/openssl-sys-0.9.58-a842db4709b604f0fe5d1170ae3565899be2ad3d9cbc72dedc789ac0511f78de/build/main.rs:140:13:

  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"clang\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"--target=aarch64-apple-darwin\" \"-I\" \"/nix/store/97gixfjyghg4njrylhpzs64m5bhslnd6-openssl-3.0.13-dev/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"clang\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel

  See rust-openssl README for more information:

      https://github.com/sfackler/rust-openssl#linux

  stack backtrace:
     0: rust_begin_unwind
               at /rustc/2bf78d12d33ae02d10010309a0d85dd04e7cff72/library/std/src/panicking.rs:648:5
     1: core::panicking::panic_fmt
               at /rustc/2bf78d12d33ae02d10010309a0d85dd04e7cff72/library/core/src/panicking.rs:72:14
     2: build_script_main::validate_headers
     3: build_script_main::find_normal::try_pkg_config
     4: build_script_main::find_normal::find_openssl_dir
     5: build_script_main::find_normal::get_openssl::{{closure}}
     6: core::option::Option<T>::unwrap_or_else
     7: build_script_main::find_normal::get_openssl
     8: build_script_main::find_openssl
     9: build_script_main::main
    10: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
[naersk] cargo returned with exit code 101, exiting
```

</details>

**Comment by thecaralice** [comment]
UPD: Seems like support for OpenSSL 3 was only added with openssl-sys 0.9.64

**Comment by fleetingbytes** [comment]
I have this issue with building openssl-sys 0.9.101 on FreeBSD 14, amd64. This one, I think is of a different kind than in the original post:

```
   Compiling openssl-sys v0.9.101
error: failed to run custom build command for `openssl-sys v0.9.101`

Caused by:
  process didn't exit successfully: `/home/tejul/src/leftwm-theme/target/debug/build/openssl-sys-1bc3d667f73a21dd/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_FREEBSD_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_FREEBSD_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=CC_x86_64-unknown-freebsd
  CC_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_freebsd
  CC_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-freebsd
  CFLAGS_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_freebsd
  CFLAGS_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=AR_x86_64-unknown-freebsd
  AR_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_freebsd
  AR_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-freebsd
  ARFLAGS_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_freebsd
  ARFLAGS_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=RANLIB_x86_64-unknown-freebsd
  RANLIB_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=RANLIB_x86_64_unknown_freebsd
  RANLIB_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_RANLIB
  HOST_RANLIB = None
  cargo:rerun-if-env-changed=RANLIB
  RANLIB = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64-unknown-freebsd
  RANLIBFLAGS_x86_64-unknown-freebsd = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64_unknown_freebsd
  RANLIBFLAGS_x86_64_unknown_freebsd = None
  cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
  HOST_RANLIBFLAGS = None
  cargo:rerun-if-env-changed=RANLIBFLAGS
  RANLIBFLAGS = None
  running cd "/home/tejul/src/leftwm-theme/target/debug/build/openssl-sys-d5039d8e4c117168/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/home/tejul/src/leftwm-theme/target/debug/build/openssl-sys-d5039d8e4c117168/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "BSD-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-freebsd"
  Configuring OpenSSL version 3.2.1 for target BSD-x86_64
  Using os-specific seed configuration
  Created configdata.pm
  Running configdata.pm
  Created Makefile.in
  Created Makefile
  Created include/openssl/configuration.h

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL.md file first)      ***
  ***                                                                ***
  **********************************************************************
  running cd "/home/tejul/src/leftwm-theme/target/debug/build/openssl-sys-d5039d8e4c117168/out/openssl-build/build/src" && "gmake" "depend"

  --- stderr
  thread 'main' panicked at /home/tejul/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error building OpenSSL dependencies:
      Command: cd "/home/tejul/src/leftwm-theme/target/debug/build/openssl-sys-d5039d8e4c117168/out/openssl-build/build/src" && "gmake" "depend"
      Failed to execute: No such file or directory (os error 2)


      
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
In my error output I find it suspicious that in the line starting with "running cd"  there is an option `"--openssldir=/usr/local/ssl"` yet on my system the openssl is installed in `/usr/local/openssl` (I installed it manually as a package with `pkg install openssl`). Maybe this path discrepancy is what caused the "No such file or directory" error.
