### ISSUE TITLE
Jumbled Output from Signing X509 Cert

### ISSUE THREAD

**Issue by klercke** [sfackler/rust-openssl#2048]
Hello,

First of all, my apologies if I'm making a simple mistake. I'm pretty far outside of my comfort zone with this project I'm working on.

In short, I am using Windows (certreq -new) to generate a CSR and attempting to sign it with a CA cert generated in my Rust program. Everything seems to work fine (certs are valid) up until trying to import the CSR and sign it. This is what I came up with:

`fn main() {
...

    let mut csr_names_vec: Vec<std::path::PathBuf> = Vec::new();
    for element in std::path::Path::new(r"./").read_dir().unwrap() {
        let path = element.unwrap().path();
        if let Some(extension) = path.extension() {
            if extension == "csr" {
                csr_names_vec.push(path);
            }
        }
    }
    print!("Found the following CSRs: ");
    let mut csr_vec: Vec<X509Req> = Vec::new();
    for csr_name in csr_names_vec {
        print!("{:?} ", csr_name);
        match csr_file_to_x509req(&csr_name) {
            Ok(csr) => {
                fs::write(String::from("./csr.test"), csr.to_text().unwrap()).expect("Error writing CSR test file.");
                csr_vec.push(csr);
            },
            Err(error) => panic!("Problem reading CSR files: {:?}", error)
        }
    }
    // TODO: Pretty print the above
    println!();

    // Sign all CSRs
    for csr in csr_vec {
        match sign_x509req(&csr, &root_cert, &root_keypair) {
            Ok(cert) => {
                let cert_file = cert.to_der().unwrap();
                fs::write("./out.crt", cert_file).expect("Error writing signed cert file");
            },
            Err(error) => panic!("Problem reading signed CSRs: {:?}", error)
        }
    }

...
}

...

fn sign_x509req(csr: &X509Req, root_cert: &X509, private_key: &PKey<Private>) -> Result<X509, ErrorStack> {
    // Create the cert that we will sign
    let mut signed_cert_builder = X509::builder()?;
    signed_cert_builder.set_version(2)?;
    signed_cert_builder.set_subject_name(csr.subject_name())?;
    signed_cert_builder.set_pubkey(&*csr.public_key()?)?;

    let subject_key_identifier = SubjectKeyIdentifier::new().build(&signed_cert_builder.x509v3_context(Some(root_cert), None))?;
    signed_cert_builder.append_extension(subject_key_identifier)?;

    let key_usage = KeyUsage::new().digital_signature().key_encipherment().build()?;
    signed_cert_builder.append_extension(key_usage)?;

    let extended_key_usage = ExtendedKeyUsage::new().server_auth().build()?;
    signed_cert_builder.append_extension(extended_key_usage)?;

    // Prepare to sign the cert
    signed_cert_builder.set_issuer_name(root_cert.subject_name())?;
    signed_cert_builder.sign(private_key, MessageDigest::sha256())?;

    // Sign and return
    Ok(signed_cert_builder.build())
}
`

When I try this, the .crt file comes out full of invalid characters and obviously cannot be imported into Windows. The only parts that seem to be encoded properly are the name, country, state, etc. of the CA and the FQDN of the server the cert is for. If I try to call .to_text() on the cert in the block where I write it to out.crt, the program panics.

If I need to provide more info, please let me know! This has been driving me crazy all day.

**Comment by sfackler** [comment]
You probably want an X509-encoded cert, not a DER-encoded cert.

**Comment by klercke** [comment]
How do I save a X509-encoded cert? If I replace the cert.to_der() in main with cert.to_text(), the program panics (on both Windows and Linux). Here's the backtrace from my WSL machine:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([])', src/main.rs:267:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/result.rs:1076:23
   4: ldapsnap::main
             at ./src/main.rs:267:33
   5: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by sfackler** [comment]
https://docs.rs/openssl/latest/openssl/x509/struct.X509Ref.html#method.to_pem

**Comment by klercke** [comment]
I was using .to_pem() originally. This does generate a file that _looks_ valid, but once I try to import it as a cert, it quickly becomes obvious that it is not valid. Trying to open it with openssl in Ubuntu does not work either:
`Could not read certificate from out.crt
40773902467F0000:error:1608010C:STORE routines:ossl_store_handle_load_result:unsupported:../crypto/store/store_result.c:151:
Unable to load certificate`
