### ISSUE TITLE
Doesn't build on Void Linux Musl. The fact that I'm using LibreSSL is NOT related(tried with OpenSSL too many times).

### ISSUE THREAD

**Issue by xplshn** [sfackler/rust-openssl#2085]
```
[anto@beef intiface-engine]$ RUST_BACKTRACE=full OPENSSL_DIR=/usr/local/etc/ssl/ cargo build
   Compiling openssl-sys v0.9.85
   Compiling libdbus-sys v0.2.4
   Compiling openssl-macros v0.1.0
   Compiling libgit2-sys v0.14.2+1.5.1
error: failed to run custom build command for `openssl-sys v0.9.85`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/anto/Programs/Compiled/intiface-engine/target/debug/build/openssl-sys-942d5cb044095d7b/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /usr/local/etc/ssl/

  --- stderr
  thread 'main' panicked at /home/anto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.85/build/main.rs:86:9:
  OpenSSL include directory does not exist: /usr/local/etc/ssl/include
  stack backtrace:
     0:     0x7fd4fe3af75c - std::backtrace_rs::backtrace::libunwind::trace::h370587616c149a45
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x7fd4fe3af75c - std::backtrace_rs::backtrace::trace_unsynchronized::h4cc55038e4a874cd
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x7fd4fe3af75c - std::sys_common::backtrace::_print_fmt::hc26cc3c2eddc21d7
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x7fd4fe3af75c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb67f6e94152691e9
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x7fd4fe3ecfec - core::fmt::rt::Argument::fmt::h1fd35fc4c88687b8
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
     5:     0x7fd4fe3ecfec - core::fmt::write::h738793984be7f52c
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
     6:     0x7fd4fe3abf5e - std::io::Write::write_fmt::h84056616c47209ca
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
     7:     0x7fd4fe3af544 - std::sys_common::backtrace::_print::h20a11f09f8216cd4
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
     8:     0x7fd4fe3af544 - std::sys_common::backtrace::print::h7b70e260a2475fa3
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
     9:     0x7fd4fe3b1483 - std::panicking::default_hook::{{closure}}::h81c979645f368377
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
    10:     0x7fd4fe3b119c - std::panicking::default_hook::h157ab9bf73bc8932
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
    11:     0x7fd4fe3b1a09 - std::panicking::rust_panic_with_hook::hec9e488e5d9ea17f
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
    12:     0x7fd4fe3b1907 - std::panicking::begin_panic_handler::{{closure}}::h83232311f2354a3d
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
    13:     0x7fd4fe3afc86 - std::sys_common::backtrace::__rust_end_short_backtrace::h8a82556d18c9cf5a
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
    14:     0x7fd4fe3b1652 - rust_begin_unwind
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
    15:     0x7fd4fe2eb983 - core::panicking::panic_fmt::h9fb1cf80aef8bb8a
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
    16:     0x7fd4fe2ef051 - build_script_main::main::hcb0810d0f3b91b68
    17:     0x7fd4fe2f7053 - core::ops::function::FnOnce::call_once::h997bf20e11000903
    18:     0x7fd4fe2f6776 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4d67d40ce3c5a12c
    19:     0x7fd4fe2f1ed9 - std::rt::lang_start::{{closure}}::hd345a8565bdea0b2
    20:     0x7fd4fe3a69c2 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha2637e1997ac7c13
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
    21:     0x7fd4fe3a69c2 - std::panicking::try::do_call::h832fee3c237f1ab9
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    22:     0x7fd4fe3a69c2 - std::panicking::try::h3aa50d7a8c88bc33
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    23:     0x7fd4fe3a69c2 - std::panic::catch_unwind::h18707eb77e45240b
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    24:     0x7fd4fe3a69c2 - std::rt::lang_start_internal::{{closure}}::h3658efd554ecec51
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
    25:     0x7fd4fe3a69c2 - std::panicking::try::do_call::hadd0bdb18c3bc9fa
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
    26:     0x7fd4fe3a69c2 - std::panicking::try::h6186a1bf9b125052
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
    27:     0x7fd4fe3a69c2 - std::panic::catch_unwind::h1cd9e9f03c64dccb
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
    28:     0x7fd4fe3a69c2 - std::rt::lang_start_internal::hc2237e64f4a57445
                                 at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
    29:     0x7fd4fe2f1eb7 - std::rt::lang_start::h4c326499150295e9
    30:     0x7fd4fe2f1ce5 - main
warning: build failed, waiting for other jobs to finish...
[anto@beef intiface-engine]$ openssl version -v
LibreSSL 3.8.2
[anto@beef intiface-engine]$ openssl version -d
OPENSSLDIR: "/usr/local/etc/ssl"
[anto@beef intiface-engine]$ 

```

`Linux beef 6.5.10_1 #1 SMP PREEMPT_DYNAMIC Thu Nov  2 16:51:33 UTC 2023 x86_64 GNU/Linux`

Rust was installed using the install script provided from the web, in minimal mode.

**Comment by Skepfyr** [comment]
The problem your hitting is that you're providing the wrong value for `OPENSSL_DIR` (it confusingly shouldn't match OPENSSLDIR provided by openssl version -d), it should contain a folder called `include` containing the header files and a folder called `lib` containing librcrypto and libssl. Given you've built and by the looks of it installed your own LibreSSL you may want to specify `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` separately (probably to something like `/usr/local/include` and `/usr/local/lib` respectively). I've successfully built a simple crate using openssl-devel in a Void Linux container.

Given this is quite old I'm going to close this issue, feel free to reopen if you'd like help debugging further.
