### ISSUE TITLE
Fail to build on Windows: 'explicit panic'

### ISSUE THREAD

**Issue by betovsky** [sfackler/rust-openssl#215]
On cargo build:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling openssl-sys v0.6.2
failed to run custom build command for `openssl-sys v0.6.2`
Process didn't exit successfully: `D:\Code\projects\badgerGP\target\debug\build\openssl-sys-5040130ff99796a0\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-flags=-l dylib=eay32 -l dylib=ssl32
TARGET = Some("x86_64-pc-windows-gnu")
CARGO_MANIFEST_DIR = Some("C:\\Users\\MB\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\openssl-sys-0.6.2")
OUT_DIR = Some("D:\\Code\\projects\\badgerGP\\target\\debug\\build\\openssl-sys-5040130ff99796a0\\out")
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
running: "gcc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-mwin32" "-m64" "-fPIC" "C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c" "-o" "D:\Code\projects\badgerGP\target\debug\build\openssl-sys-5040130ff99796a0\out\src\old_openssl_shim.o"


command did not execute successfully, got: exit code: 1



--- stderr
C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c:1:0: warning: -fPIC ignored for target (all code is position independent)
C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
compilation terminated.
thread '<main>' panicked at 'explicit panic', C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.5\src\lib.rs:384
```

**Comment by sfackler** [comment]
It looks like it can't find OpenSSL headers - take a look at the Windows section of the README: https://github.com/sfackler/rust-openssl#windows

**Comment by betovsky** [comment]
Thanks for the quick reply.

I used the SET command since I don't have the env command. Don't know if it's because of that, but I still get the error.

```
D:\Code\projects\badgerGP>set OPENSSL
OPENSSL_INCLUDE_DIR=D:\OpenSSL-Win64\include
OPENSSL_LIB_DIR=D:\OpenSSL-Win64

D:\Code\projects\badgerGP>cargo build
   Compiling time v0.1.25
   Compiling openssl-sys v0.6.2
Build failed, waiting for other jobs to finish...
failed to run custom build command for `openssl-sys v0.6.2`
Process didn't exit successfully: `D:\Code\projects\badgerGP\target\debug\build\openssl-sys-5040130ff99796a0\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-flags=-L native=D:\OpenSSL-Win64
cargo:rustc-flags=-l dylib=eay32 -l dylib=ssl32
TARGET = Some("x86_64-pc-windows-gnu")
CARGO_MANIFEST_DIR = Some("C:\\Users\\MB\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\openssl-sys-0.6.2")
OUT_DIR = Some("D:\\Code\\projects\\badgerGP\\target\\debug\\build\\openssl-sys-5040130ff99796a0\\out")
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
debug 0
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
running: "gcc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-mwin32" "-m64" "-fPIC" "-I" "D:\OpenSSL-Win64\include" "C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c" "-o" "D:\Code\projects\badgerGP\target\debug\build\openssl-sys-5040130ff99796a0\out\src\old_openssl_shim.o"


command did not execute successfully, got: exit code: 1



--- stderr
C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c:1:0: warning: -fPIC ignored for target (all code is position independent)
C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.6.2\src/old_openssl_shim.c:1:0: sorry, unimplemented: 64-bit mode not compiled in
thread '<main>' panicked at 'explicit panic', C:\Users\MB\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.5\src\lib.rs:384
```

**Comment by sfackler** [comment]
This line appears to be the culprit: `sorry, unimplemented: 64-bit mode not compiled in`. It looks like the GCC you have installed can only target x86, not x86_64. You can either install an x86 version of Rust or install a version of GCC that can target x86_64.

**Comment by betovsky** [comment]
It's fixed.

You had me thinking. Went digging and noticed that it was using another gcc that I had from an old installation of Haskell Platform.

Thank you
