### ISSUE TITLE
Debian 12 x86_64 - crosscompile Error

### ISSUE THREAD

**Issue by ds2k5** [sfackler/rust-openssl#2189]
Hi,
using Debian 12 on x86_64

libssl-dev is installed and a lot of compiler

```
$ rustc  --version
rustc 1.76.0 (07dca489a 2024-02-04)

```

```
ii  gcc                                                   4:12.2.0-3                              amd64        GNU C compiler
ii  gcc-10                                                10.2.1-6                                amd64        GNU C compiler
ii  gcc-10-base:amd64                                     10.2.1-6                                amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-11-base:amd64                                     11.3.0-12                               amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12                                                12.2.0-14                               amd64        GNU C compiler
ii  gcc-12-aarch64-linux-gnu                              12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for arm64 architecture)
ii  gcc-12-aarch64-linux-gnu-base:amd64                   12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-arm-linux-gnueabi                              12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for armel architecture)
ii  gcc-12-arm-linux-gnueabi-base:amd64                   12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-arm-linux-gnueabihf                            12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for armhf architecture)
ii  gcc-12-arm-linux-gnueabihf-base:amd64                 12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:amd64                                     12.2.0-14                               amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:arm64                                     12.2.0-14                               arm64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:armel                                     12.2.0-14                               armel        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:armhf                                     12.2.0-14                               armhf        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:i386                                      12.2.0-14                               i386         GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:ppc64el                                   12.2.0-14                               ppc64el      GCC, the GNU Compiler Collection (base package)
ii  gcc-12-base:s390x                                     12.2.0-14                               s390x        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-cross-base                                     12.2.0-14cross1                         all          GCC, the GNU Compiler Collection (library base package)
ii  gcc-12-cross-base-ports                               12.2.0-13cross1                         all          GCC, the GNU Compiler Collection (library base package)
ii  gcc-12-i686-linux-gnu                                 12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for i386 architecture)
ii  gcc-12-i686-linux-gnu-base:amd64                      12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-multilib                                       12.2.0-14                               amd64        GNU C compiler (multilib support)
ii  gcc-12-multilib-s390x-linux-gnu                       12.2.0-14cross1                         amd64        GNU C compiler (multilib support) (cross compiler for s390x architecture)
ii  gcc-12-powerpc-linux-gnu                              12.2.0-13cross1                         amd64        GNU C compiler (cross compiler for powerpc architecture)
ii  gcc-12-powerpc-linux-gnu-base:amd64                   12.2.0-13cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-powerpc64-linux-gnu                            12.2.0-13cross1                         amd64        GNU C compiler (cross compiler for ppc64 architecture)
ii  gcc-12-powerpc64-linux-gnu-base:amd64                 12.2.0-13cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-powerpc64le-linux-gnu                          12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for ppc64el architecture)
ii  gcc-12-powerpc64le-linux-gnu-base:amd64               12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-riscv64-linux-gnu                              12.2.0-13cross1                         amd64        GNU C compiler (cross compiler for riscv64 architecture)
ii  gcc-12-riscv64-linux-gnu-base:amd64                   12.2.0-13cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-12-s390x-linux-gnu                                12.2.0-14cross1                         amd64        GNU C compiler (cross compiler for s390x architecture)
ii  gcc-12-s390x-linux-gnu-base:amd64                     12.2.0-14cross1                         amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-9-base:amd64                                      9.3.0-22                                amd64        GCC, the GNU Compiler Collection (base package)
ii  gcc-aarch64-linux-gnu                                 4:12.2.0-3                              amd64        GNU C compiler for the arm64 architecture
ii  gcc-arm-linux-gnueabi                                 4:12.2.0-3                              amd64        GNU C compiler for the armel architecture
ii  gcc-arm-linux-gnueabihf                               4:12.2.0-3                              amd64        GNU C compiler for the armhf architecture
ii  gcc-arm-none-eabi                                     15:12.2.rel1-1                          amd64        GCC cross compiler for ARM Cortex-R/M processors
ii  gcc-avr                                               1:5.4.0+Atmel3.6.2-3                    amd64        GNU C compiler (cross compiler for avr)
ii  gcc-i686-linux-gnu                                    4:12.2.0-3                              amd64        GNU C compiler for the i386 architecture
ii  gcc-mingw-w64                                         12.2.0-14+25.2                          all          GNU C compiler for MinGW-w64
ii  gcc-mingw-w64-base:amd64                              12.2.0-14+25.2                          amd64        GNU Compiler Collection for MinGW-w64 (base package)
ii  gcc-mingw-w64-i686                                    12.2.0-14+25.2                          all          GNU C compiler for MinGW-w64 targeting Win32
ii  gcc-mingw-w64-i686-posix                              12.2.0-14+25.2                          amd64        GNU C compiler for MinGW-w64, Win32/POSIX
ii  gcc-mingw-w64-i686-posix-runtime                      12.2.0-14+25.2                          amd64        GNU Compiler Collection for MinGW-w64, i686/POSIX
ii  gcc-mingw-w64-i686-win32                              12.2.0-14+25.2                          amd64        GNU C compiler for MinGW-w64, Win32/Win32
ii  gcc-mingw-w64-i686-win32-runtime                      12.2.0-14+25.2                          amd64        GNU Compiler Collection for MinGW-w64, i686/Win32
ii  gcc-mingw-w64-x86-64                                  12.2.0-14+25.2                          all          GNU C compiler for MinGW-w64 targeting Win64
ii  gcc-mingw-w64-x86-64-posix                            12.2.0-14+25.2                          amd64        GNU C compiler for MinGW-w64, Win64/POSIX
ii  gcc-mingw-w64-x86-64-posix-runtime                    12.2.0-14+25.2                          amd64        GNU Compiler Collection for MinGW-w64, x86-64/POSIX
ii  gcc-mingw-w64-x86-64-win32                            12.2.0-14+25.2                          amd64        GNU C compiler for MinGW-w64, Win64/Win32
ii  gcc-mingw-w64-x86-64-win32-runtime                    12.2.0-14+25.2                          amd64        GNU Compiler Collection for MinGW-w64, x86-64/Win32
ii  gcc-multilib-s390x-linux-gnu                          4:12.2.0-3                              amd64        GNU C compiler for the s390x architecture
ii  gcc-powerpc-linux-gnu                                 4:12.2.0-5                              amd64        GNU C compiler for the powerpc architecture
ii  gcc-powerpc64-linux-gnu                               4:12.2.0-5                              amd64        GNU C compiler for the ppc64 architecture
ii  gcc-powerpc64le-linux-gnu                             4:12.2.0-3                              amd64        GNU C compiler for the ppc64el architecture
ii  gcc-riscv64-linux-gnu                                 4:12.2.0-5                              amd64        GNU C compiler for the riscv64 architecture
ii  gcc-s390x-linux-gnu                                   4:12.2.0-3                              amd64        GNU C compiler for the s390x architecture
ii  lib32gcc-12-dev                                       12.2.0-14                               amd64        GCC support library (32 bit development files)
ii  lib32gcc-12-dev-s390x-cross                           12.2.0-14cross1                         all          GCC support library (32 bit development files)
ii  lib32gcc-s1                                           12.2.0-14                               amd64        GCC support library (32 bit Version)
ii  lib32gcc-s1-s390x-cross                               12.2.0-14cross1                         all          GCC support library (32 bit Version)
ii  libgcc-10-dev:amd64                                   10.2.1-6                                amd64        GCC support library (development files)
ii  libgcc-12-dev:amd64                                   12.2.0-14                               amd64        GCC support library (development files)
ii  libgcc-12-dev-arm64-cross                             12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-armel-cross                             12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-armhf-cross                             12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-i386-cross                              12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-powerpc-cross                           12.2.0-13cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-ppc64-cross                             12.2.0-13cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-ppc64el-cross                           12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-riscv64-cross                           12.2.0-13cross1                         all          GCC support library (development files)
ii  libgcc-12-dev-s390x-cross                             12.2.0-14cross1                         all          GCC support library (development files)
ii  libgcc-s1:amd64                                       12.2.0-14                               amd64        GCC support library
ii  libgcc-s1:arm64                                       12.2.0-14                               arm64        GCC support library
ii  libgcc-s1:armel                                       12.2.0-14                               armel        GCC support library
ii  libgcc-s1:armhf                                       12.2.0-14                               armhf        GCC support library
ii  libgcc-s1:i386                                        12.2.0-14                               i386         GCC support library
ii  libgcc-s1:ppc64el                                     12.2.0-14                               ppc64el      GCC support library
ii  libgcc-s1:s390x                                       12.2.0-14                               s390x        GCC support library
ii  libgcc-s1-arm64-cross                                 12.2.0-14cross1                         all          GCC support library (arm64)
ii  libgcc-s1-armel-cross                                 12.2.0-14cross1                         all          GCC support library (armel)
ii  libgcc-s1-armhf-cross                                 12.2.0-14cross1                         all          GCC support library (armhf)
ii  libgcc-s1-i386-cross                                  12.2.0-14cross1                         all          GCC support library (i386)
ii  libgcc-s1-powerpc-cross                               12.2.0-13cross1                         all          GCC support library (powerpc)
ii  libgcc-s1-ppc64-cross                                 12.2.0-13cross1                         all          GCC support library (ppc64)
ii  libgcc-s1-ppc64el-cross                               12.2.0-14cross1                         all          GCC support library (ppc64el)
ii  libgcc-s1-riscv64-cross                               12.2.0-13cross1                         all          GCC support library (riscv64)
ii  libgcc-s1-s390x-cross                                 12.2.0-14cross1                         all          GCC support library (s390x)
ii  libuno-cppuhelpergcc3-3                               4:7.4.7-1+deb12u1                       amd64        LibreOffice UNO runtime environment -- CPPU helper library
ii  libuno-purpenvhelpergcc3-3                            4:7.4.7-1+deb12u1                       amd64        LibreOffice UNO runtime environment -- "purpose environment" helper
ii  libuno-salhelpergcc3-3                                4:7.4.7-1+deb12u1                       amd64        LibreOffice UNO runtime environment -- SAL helpers for C++ library
ii  libx32gcc-12-dev                                      12.2.0-14                               amd64        GCC support library (x32 development files)
ii  libx32gcc-s1                                          12.2.0-14                               amd64        GCC support library (x32)
ii  linux-compiler-gcc-12-x86                             6.1.76-1                                amd64        Compiler for Linux on x86 (meta-package)
ii  python3-pygccxml                                      2.2.1-1                                 all          specialized XML reader reads the output from gccxml - python3 lib

```

```
$ dpkg -l | grep libssl
ii  libssl-dev:amd64                                      3.0.11-1~deb12u2                        amd64        Secure Sockets Layer toolkit - development files
ii  libssl1.1:amd64                                       1.1.1n-0+deb11u5                        amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:amd64                                         3.0.11-1~deb12u2                        amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl3:i386                                          3.0.11-1~deb12u2                        i386         Secure Sockets Layer toolkit - shared libraries

```

```
$ dpkg -l | grep gcc-arm-linux-gnueabihf
ii  gcc-arm-linux-gnueabihf                               4:12.2.0-3                              amd64        GNU C compiler for the armhf architecture

```
```

export CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=/usr/bin/arm-linux-gnueabihf-gcc

$ ls -la /usr/bin/arm-linux-gnueabihf-gcc
lrwxrwxrwx 1 root root 26 Jan  8  2023 /usr/bin/arm-linux-gnueabihf-gcc -> arm-linux-gnueabihf-gcc-12


```

```
$ cargo build --target=armv7-unknown-linux-gnueabihf --release
   Compiling openssl-sys v0.9.101
   Compiling socket2 v0.5.6
   Compiling mio v0.8.10
   Compiling num_cpus v1.16.0
   Compiling http v0.2.11
   Compiling slab v0.4.9
   Compiling foreign-types v0.3.2
   Compiling tracing v0.1.40
error: failed to run custom build command for `openssl-sys v0.9.101`

Caused by:
  process didn't exit successfully: `/home/developer/rust/weather/target/release/build/openssl-sys-311e0a0ef7cd49e0/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: pkg-config has not been configured to support cross-compilation.

  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable.

  --- stderr
  thread 'main' panicked at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/find_normal.rs:190:5:


  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = armv7-unknown-linux-gnueabihf
  openssl-sys = 0.9.101


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

```
```

$ RUST_BACKTRACE=1 cargo build --target=armv7-unknown-linux-gnueabihf --release
   Compiling openssl-sys v0.9.101
   Compiling tokio v1.36.0
   Compiling httparse v1.8.0
   Compiling pin-utils v0.1.0
   Compiling tinyvec_macros v0.1.1
   Compiling native-tls v0.2.11
   Compiling futures-io v0.3.30
   Compiling futures-task v0.3.30
   Compiling hashbrown v0.14.3
   Compiling serde v1.0.197
error: failed to run custom build command for `openssl-sys v0.9.101`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/developer/rust/weather/target/release/build/openssl-sys-311e0a0ef7cd49e0/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR
  ARMV7_UNKNOWN_LINUX_GNUEABIHF_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_armv7_unknown_linux_gnueabihf
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: pkg-config has not been configured to support cross-compilation.

  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable.

  --- stderr
  thread 'main' panicked at /home/developer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/find_normal.rs:190:5:


  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = armv7-unknown-linux-gnueabihf
  openssl-sys = 0.9.101


  stack backtrace:
     0: rust_begin_unwind
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
     1: core::panicking::panic_fmt
               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
     2: core::panicking::panic_display
     3: build_script_main::find_normal::find_openssl_dir
     4: build_script_main::find_normal::get_openssl::{{closure}}
     5: core::option::Option<T>::unwrap_or_else
     6: build_script_main::find_normal::get_openssl
     7: build_script_main::find_openssl
     8: build_script_main::main
     9: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

```

**What did I wrong ?**

Have the same issue with other than armv7-unknown-linux-gnueabihf too

for example:
i686-unknown-linux-gnu 
aarch64-unknown-linux-gnu
powerpc64le-unknown-linux-gnu
x86_64-unknown-netbsd
x86_64-unknown-freebsd
aarch64-linux-android
aarch64-linux-android
armv7-unknown-linux-gnueabihf

~/.cargo/config.toml
```

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
runner = "/usr/bin/qemu-aarch64"
[target.armv7-unknown-linux-gnueabihf]
linker = "/usr/bin/arm-linux-gnueabihf-gcc"
runner = "/usr/bin/qemu-arm"
[target.armv7-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"
runner = "/usr/bin/qemu-arm"
[target.armv5te-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"
runner = "/usr/bin/qemu-arm"
[target.i686-unknown-linux-gnu]
linker = "/usr/bin/i686-linux-gnu-gcc"
#runner = Heh. Multiarch.
[target.powerpc64le-unknown-linux-gnu]
linker = "/usr/bin/powerpc64le-linux-gnu-gcc"
runner = "/usr/bin/qemu-ppc64le"
[target.s390x-unknown-linux-gnu]
linker = "/usr/bin/s390x-linux-gnu-gcc"
runner = "/usr/bin/qemu-s390x"
[target.armv7-linux-androideabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"
runner = "/usr/bin/qemu-arm"
[target.x86_64-linux-android]
linker = "/home/developer/x86_64-linux-android/bin/x86_64-linux-android21-clang"
[target.aarch64-linux-android]
linker = "/home/developer/x86_64-linux-android/bin/aarch64-linux-android21-clang"
[target.x86_64-apple-darwin]
linker = "/home/developer/osxcross/target/bin/x86_64-apple-darwin20.4-clang"
ar = "/home/developer/osxcross/target/bin/x86_64-apple-darwin20.4-ar"
rustflags = [ "-C", "link-arg=-fuse-ld=lld"]
#linker = "/home/developer/osxcross/target/bin/o64-gcc"
[target.aarch64-apple-darwin]
linker = "/home/developer/osxcross/target/bin/aarch64-apple-darwin20.4-clang"
ar = "/home/developer/osxcross/target/bin/aarch64-apple-darwin20.4-ar"
rustflags = [ "-C", "link-arg=-fuse-ld=lld"]
[target.x86_64-unknown-freebsd]
# 13.0-RELEASE-p4, FreeBSD clang version 11.0.1
linker="/home/developer/osxcross/build/clang-17/build_stage1/bin/clang-17"
#rustflags = ["-Clink-arg=-s", "-Clink-arg=-v", "-Clink-arg=-fuse-ld=lld", "-Clink-arg=--target=x86_64-unknown-freebsd","-Clink-arg=--sysroot=/opt/x86_64-unknown-freebsd"]
[target.powerpc64-unknown-linux-gnu]
linker = "/usr/bin/powerpc64-linux-gnu-gcc"
[target.powerpc-unknown-linux-gnu]
linker = "/usr/bin/powerpc-linux-gnu-gcc"
[target.riscv64gc-unknown-linux-gnu]
linker = "/usr/bin/riscv64-linux-gnu-gcc"
[target.xtensa-esp32-none-elf]
linker = "/home/developer/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc"
[target.xtensa-esp32-espidf]
linker = "/home/developer/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc"

```

Cargo.toml
```

[dependencies]
chrono = "0.4.34"
current_platform = "0.2.0"
env = "0.0.0"
gettext-ng = "0.4.1"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde_json = "1.0.114"
sys-locale = "0.3.1"
```

```
$ rustup target list | grep inst
aarch64-apple-darwin (installed)
aarch64-linux-android (installed)
aarch64-pc-windows-msvc (installed)
aarch64-unknown-linux-gnu (installed)
aarch64-unknown-linux-musl (installed)
arm-unknown-linux-gnueabihf (installed)
armebv7r-none-eabi (installed)
armebv7r-none-eabihf (installed)
armv5te-unknown-linux-gnueabi (installed)
armv7-linux-androideabi (installed)
armv7-unknown-linux-gnueabi (installed)
armv7-unknown-linux-gnueabihf (installed)
i586-unknown-linux-gnu (installed)
i686-pc-windows-gnu (installed)
i686-unknown-linux-gnu (installed)
i686-unknown-linux-musl (installed)
powerpc-unknown-linux-gnu (installed)
powerpc64-unknown-linux-gnu (installed)
powerpc64le-unknown-linux-gnu (installed)
riscv32imac-unknown-none-elf (installed)
riscv32imc-unknown-none-elf (installed)
riscv64gc-unknown-linux-gnu (installed)
s390x-unknown-linux-gnu (installed)
thumbv6m-none-eabi (installed)
x86_64-apple-darwin (installed)
x86_64-linux-android (installed)
x86_64-pc-windows-gnu (installed)
x86_64-unknown-freebsd (installed)
x86_64-unknown-illumos (installed)
x86_64-unknown-linux-gnu (installed)
x86_64-unknown-linux-gnux32 (installed)
x86_64-unknown-linux-musl (installed)
x86_64-unknown-netbsd (installed)

```

**Comment by sfackler** [comment]
From the error message:

```
  run pkg_config fail: pkg-config has not been configured to support cross-compilation.

  Install a sysroot for the target platform and configure it via
  PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
  cross-compiling wrapper for pkg-config and set it via
  PKG_CONFIG environment variable.
```

**Comment by ds2k5** [comment]
@sfackler 

>Install a sysroot for the target platform

thanks but how ?

**Comment by ds2k5** [comment]
this works for me:

`PKG_CONFIG_ALLOW_CROSS=1 cargo build --target armv7-unknown-linux-gnueabihf --release`

**Comment by suprohub** [comment]
thanks much!!
