### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.101` in windows

### ISSUE THREAD

**Issue by rainliu** [sfackler/rust-openssl#2197]
https://github.com/webrtc-rs/sfu/actions/runs/8120950877/job/22198948874

```
error: failed to run custom build command for `openssl-sys v0.9.101`

Caused by:
  process didn't exit successfully: `D:\a\sfu\sfu\target\debug\build\openssl-sys-6df97338b7e066f3\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'

  --- stderr
  thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\openssl-sys-0.9.101\build\find_normal.rs:190:5:


  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-pc-windows-msvc
  $TARGET = x86_64-pc-windows-msvc
  openssl-sys = 0.9.101


  It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
  installation. If there isn't one installed then you can try the rust-openssl
  README for more information about how to download precompiled binaries of
  OpenSSL:

  https://github.com/sfackler/rust-openssl#windows


  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 1.
```

**Comment by antonyngayo** [comment]
Hi, any workarounds for this, trying to build for a `x86_64-unknown-linux-musl` target but constantly hitting the error below

```
error: failed to run custom build command for `openssl-sys v0.9.101`

Caused by:
  process didn't exit successfully: `/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-6a4a45d05c1acc31/build-script-main` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
  AR_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
  AR_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_AR
  HOST_AR = None
  cargo:rerun-if-env-changed=AR
  AR = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
  ARFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
  ARFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  cargo:rerun-if-env-changed=RANLIB_x86_64-unknown-linux-gnu
  RANLIB_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=RANLIB_x86_64_unknown_linux_gnu
  RANLIB_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_RANLIB
  HOST_RANLIB = None
  cargo:rerun-if-env-changed=RANLIB
  RANLIB = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64-unknown-linux-gnu
  RANLIBFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64_unknown_linux_gnu
  RANLIBFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
  HOST_RANLIBFLAGS = None
  cargo:rerun-if-env-changed=RANLIBFLAGS
  RANLIBFLAGS = None
  running cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64"
  Configuring OpenSSL version 3.2.1 for target linux-x86_64
  Using os-specific seed configuration
  Created configdata.pm
  Running configdata.pm
  Created Makefile.in
  Created Makefile
  Created include/openssl/configuration.h

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL.md file first)      ***
  ***                                                                ***
  **********************************************************************
  running cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && "make" "depend"

  --- stderr
  thread 'main' panicked at /var/lib/jenkins/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:



  Error building OpenSSL dependencies:
      Command: cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && "make" "depend"
      Failed to execute: No such file or directory (os error 2)
```

**Comment by antonyngayo** [comment]
> Hi, any workarounds for this, trying to build for a `x86_64-unknown-linux-musl` target but constantly hitting the error below
> 
> ```
> error: failed to run custom build command for `openssl-sys v0.9.101`
> 
> Caused by:
>   process didn't exit successfully: `/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-6a4a45d05c1acc31/build-script-main` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
>   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
>   OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
>   CC_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
>   CC_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_CC
>   HOST_CC = None
>   cargo:rerun-if-env-changed=CC
>   CC = None
>   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
>   CRATE_CC_NO_DEFAULTS = None
>   DEBUG = Some("true")
>   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
>   cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
>   CFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
>   CFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_CFLAGS
>   HOST_CFLAGS = None
>   cargo:rerun-if-env-changed=CFLAGS
>   CFLAGS = None
>   cargo:rerun-if-env-changed=AR_x86_64-unknown-linux-gnu
>   AR_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=AR_x86_64_unknown_linux_gnu
>   AR_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_AR
>   HOST_AR = None
>   cargo:rerun-if-env-changed=AR
>   AR = None
>   cargo:rerun-if-env-changed=ARFLAGS_x86_64-unknown-linux-gnu
>   ARFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=ARFLAGS_x86_64_unknown_linux_gnu
>   ARFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_ARFLAGS
>   HOST_ARFLAGS = None
>   cargo:rerun-if-env-changed=ARFLAGS
>   ARFLAGS = None
>   cargo:rerun-if-env-changed=RANLIB_x86_64-unknown-linux-gnu
>   RANLIB_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=RANLIB_x86_64_unknown_linux_gnu
>   RANLIB_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_RANLIB
>   HOST_RANLIB = None
>   cargo:rerun-if-env-changed=RANLIB
>   RANLIB = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64-unknown-linux-gnu
>   RANLIBFLAGS_x86_64-unknown-linux-gnu = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS_x86_64_unknown_linux_gnu
>   RANLIBFLAGS_x86_64_unknown_linux_gnu = None
>   cargo:rerun-if-env-changed=HOST_RANLIBFLAGS
>   HOST_RANLIBFLAGS = None
>   cargo:rerun-if-env-changed=RANLIBFLAGS
>   RANLIBFLAGS = None
>   running cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && env -u CROSS_COMPILE AR="ar" CC="cc" RANLIB="ranlib" "perl" "./Configure" "--prefix=/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64"
>   Configuring OpenSSL version 3.2.1 for target linux-x86_64
>   Using os-specific seed configuration
>   Created configdata.pm
>   Running configdata.pm
>   Created Makefile.in
>   Created Makefile
>   Created include/openssl/configuration.h
> 
>   **********************************************************************
>   ***                                                                ***
>   ***   OpenSSL has been successfully configured                     ***
>   ***                                                                ***
>   ***   If you encounter a problem while building, please open an    ***
>   ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
>   ***   and include the output from the following command:           ***
>   ***                                                                ***
>   ***       perl configdata.pm --dump                                ***
>   ***                                                                ***
>   ***   (If you are new to OpenSSL, you might want to consult the    ***
>   ***   'Troubleshooting' section in the INSTALL.md file first)      ***
>   ***                                                                ***
>   **********************************************************************
>   running cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && "make" "depend"
> 
>   --- stderr
>   thread 'main' panicked at /var/lib/jenkins/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.2.3+3.2.1/src/lib.rs:611:9:
> 
> 
> 
>   Error building OpenSSL dependencies:
>       Command: cd "/var/lib/jenkins/workspace/api-webserver_master/target/debug/build/openssl-sys-fbb1f4a8ae47e51d/out/openssl-build/build/src" && "make" "depend"
>       Failed to execute: No such file or directory (os error 2)
> ```

fixed the issue on my end

```
apt install make
```

### Cargo Toml
```
openssl = { version = "0.10.64", features = ["vendored"] } 
```
