### ISSUE TITLE
Failure to find appropriate headers on Ubuntu 24.04 despite having `libssl-dev` installed

### ISSUE THREAD

**Issue by samuela** [sfackler/rust-openssl#2217]
I'm currently seeing an error:
```
  cargo:warning=In file included from /usr/include/openssl/opensslv.h:109,
  cargo:warning=                 from build/expando.c:1:
  cargo:warning=/usr/include/openssl/macros.h:14:10: fatal error: openssl/opensslconf.h: No such file or directory
  cargo:warning=   14 | #include <openssl/opensslconf.h>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/main.rs:186:13:

  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-gdwarf-4\" \"-fno-omit-frame-pointer\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
...
```
Full log available in [this gist](https://gist.github.com/samuela/2e8d606b5b7f1a44f50056bd88391226).

However I have `pkg-config` and `libssl-dev` installed and up to date:
```
root@6b49c5e222e1:/workspaces/sshenanigans# apt-get install pkg-config libssl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pkg-config is already the newest version (1.8.1-2).
libssl-dev is already the newest version (3.0.13-0ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
root@6b49c5e222e1:/workspaces/sshenanigans# 
```
Inspecting `/usr/include`, I can see that `/usr/include/openssl/` has 133 header files, all the usual suspects, and `/usr/include/aarch64-linux-gnu/openssl/` contains two header files: `configuration.h` and `opensslconf.h`.

For reproducibility, I'm attempting to `cargo build` a rust project that depends on `openssl-sys` from within this Docker container:
```dockerfile
FROM ubuntu:24.04
RUN apt-get update \
  # libssl-dev: necessary for the openssl-sys rust crate
  && apt-get install -y curl libssl-dev pkg-config
# See https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#in-a-container.
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --init none --no-confirm
ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
RUN nix profile install nixpkgs#cargo nixpkgs#gcc
```

**Comment by samuela** [comment]
I'm also able to reproduce the same behavior on Ubuntu 22.04

**Comment by samuela** [comment]
Using cargo from a `rustup` installation works however...

**Comment by samuela** [comment]
Ok, using cargo from `rustup`, but `gcc` from nixpkgs (`nix profile install nixpkgs#gcc` instead of `apt-get install build-essential) produces the error. So I suspect something in that `cc` or its configuration is at fault...

**Comment by lee-orr** [comment]
This also happens when utilizing zig as a replacement for cc

**Comment by 0xn4utilus** [comment]
> With `Ubuntu 24` and `libssl-dev` installed, I have solved this problem by symlinking the missing files from `/usr/include/x86_64-linux-gnu/` to `/usr/include/openssl/`
> 
> ```
> sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h
> sudo ln -s /usr/include/x86_64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h
> ```

thanks man, this really helped

**Comment by HKMV** [comment]
> With `Ubuntu 24` and `libssl-dev` installed, I have solved this problem by symlinking the missing files from `/usr/include/x86_64-linux-gnu/` to `/usr/include/openssl/`
> 
> ```
> sudo ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h
> sudo ln -s /usr/include/x86_64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h
> ```

Thank you, you have successfully solved my problem

**Comment by HeenaBansal20** [comment]
I am also facing the same issue on ubuntu22.04 and I added the symlink. But I am facing the same error for <openssl/opensslconf.h> but not for <opensslconf.h>

My include dir is set to /usr/include/openssl where all header files reside. I tried  with include dir set to /usr/include so that cmake find in the path /usr/include/openssl directory but it also didn't help.
Any help will be appreciated.

**Comment by ethanuppal** [comment]
> This also happens when utilizing zig as a replacement for cc

Did the `ln`s above fix it for you?

**Comment by mrchantey** [comment]
> > This also happens when utilizing zig as a replacement for cc
> 
> Did the `ln`s above fix it for you?

For me the `ln`s allowed openssl to compile but then it failed on the linker stage:


<details>
<summary>stack trace</summary>
<code>

error: linking with `/home/pete/.cache/cargo-zigbuild/0.19.7/zigcc-x86_64-unknown-linux-gnu-7d27.sh` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/home/pete/.wasmtime/bin:/home/pete/.nvm/versions/node/v20.18.1/bin:/home/pete/.deno/bin:/home/pete/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/pete/.config/Code/User/globalStorage/github.copilot-chat/debugCommand" VSLANG="1033" "/home/pete/.cache/cargo-zigbuild/0.19.7/zigcc-x86_64-unknown-linux-gnu-7d27.sh" "-m64" "/tmp/rustc2b0EvH/symbols.o" "<257 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "/home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/{libcompiler_builtins-dd545221bb4f4734.rlib}" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-B/home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/gcc-ld" "-fuse-ld=lld" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/pete/.cargo_target/x86_64-unknown-linux-gnu/release/deps/beetmash_site-ca295e9e8f3835b6" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs" "-fuse-ld=/usr/bin/mold"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: warning: ignoring deprecated linker optimization setting '1'
          error: unable to find dynamic system library 'ssl' using strategy 'no_fallback'. searched paths:
            /home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libssl.so
          error: unable to find dynamic system library 'crypto' using strategy 'no_fallback'. searched paths:
            /home/pete/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcrypto.so

</code>
</details>

**Comment by gty3** [comment]
I had this issue with cargo lambda and Ubuntu 24 - resolved with:

export RUSTFLAGS="-L native=/usr/lib/x86_64-linux-gnu" && cargo lambda build`

**Comment by mbana** [comment]
> I'm currently seeing an error:
> 
> ```
>   cargo:warning=In file included from /usr/include/openssl/opensslv.h:109,
>   cargo:warning=                 from build/expando.c:1:
>   cargo:warning=/usr/include/openssl/macros.h:14:10: fatal error: openssl/opensslconf.h: No such file or directory
>   cargo:warning=   14 | #include <openssl/opensslconf.h>
>   cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~~~~~
>   cargo:warning=compilation terminated.
> 
>   --- stderr
>   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/main.rs:186:13:
> 
>   Header expansion error:
>   Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-gdwarf-4\" \"-fno-omit-frame-pointer\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }
> 
>   Failed to find OpenSSL development headers.
> 
>   You can try fixing this setting the `OPENSSL_DIR` environment variable
>   pointing to your OpenSSL installation or installing OpenSSL headers package
>   specific to your distribution:
> 
>       # On Ubuntu
>       sudo apt-get install libssl-dev
> ...
> ```
> 
> Full log available in [this gist](https://gist.github.com/samuela/2e8d606b5b7f1a44f50056bd88391226).
> 
> However I have `pkg-config` and `libssl-dev` installed and up to date:
> 
> ```
> root@6b49c5e222e1:/workspaces/sshenanigans# apt-get install pkg-config libssl-dev
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> pkg-config is already the newest version (1.8.1-2).
> libssl-dev is already the newest version (3.0.13-0ubuntu3).
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> root@6b49c5e222e1:/workspaces/sshenanigans# 
> ```
> 
> Inspecting `/usr/include`, I can see that `/usr/include/openssl/` has 133 header files, all the usual suspects, and `/usr/include/aarch64-linux-gnu/openssl/` contains two header files: `configuration.h` and `opensslconf.h`.
> 
> For reproducibility, I'm attempting to `cargo build` a rust project that depends on `openssl-sys` from within this Docker container:
> 
> FROM ubuntu:24.04
> RUN apt-get update && apt-get install -y curl libssl-dev pkg-config
> # See https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#in-a-container.
> RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux --init none --no-confirm
> ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
> RUN nix profile install nixpkgs#cargo nixpkgs#gcc

At the moment, I can't tell you why but I can tell you that I experienced the same issue with a similar environment - I am using Nix package manager.

My work-around was to simply to remove `/home/mbana/.nix-profile/bin` and `/nix/var/nix/profiles/default/bin` like below (note: I am running in WSL) from `PATH`.

If anyone knows why this made a difference, please do share.

```sh
# PATH before:
$ echo $PATH
# /home/mbana/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/mbana/bin:/home/mbana/.local/bin:/home/mbana/.cargo/env:/home/mbana/go/bin:/home/mbana/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/coreutils/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Tailscale:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program Files/dotnet:/mnt/c/Program Files (x86)/Qualcomm/QIKToolV3/3.0.54.2:/mnt/c/Program Files (x86)/Qualcomm/Qualcomm_Software_Center/1.26.3.0:/mnt/c/Program Files (x86)/Qualcomm/QUTSStatusApp:/mnt/c/Program Files (x86)/Qualcomm/PCAT/bin:/mnt/c/Program Files (Arm)/Qualcomm/QualcommProfiler/CLI/target-wos/bins:/mnt/c/Program Files/usbipd-win/:/mnt/c/Users/moham/AppData/Local/Programs/Python/Python39/Scripts:/mnt/c/Users/moham/AppData/Local/Programs/Python/Python39:/mnt/c/Users/moham/.local/bin:/mnt/c/Users/moham/.cargo/bin:/mnt/c/Users/moham/.bin:/mnt/c/Users/moham/bin:/mnt/c/Program Files (x86)/GnuWin32/bin:/mnt/c/Program Files (x86)/Dr. Memory/bin:/mnt/c/Users/moham/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/moham/AppData/Local/PowerToys/DSCModules:/mnt/c/Users/moham/AppData/Local/Microsoft/WinGet/Links:/mnt/c/Users/moham/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools

PATH='/home/mbana/bin:/home/mbana/.local/bin:/home/mbana/.cargo/env:/home/mbana/go/bin:/home/mbana/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/coreutils/bin:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Tailscale:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files/Microsoft VS Code Insiders/bin:/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit:/mnt/c/Program Files/PowerShell/7:/mnt/c/Program Files/dotnet:/mnt/c/Program Files (x86)/Qualcomm/QIKToolV3/3.0.54.2:/mnt/c/Program Files (x86)/Qualcomm/Qualcomm_Software_Center/1.26.3.0:/mnt/c/Program Files (x86)/Qualcomm/QUTSStatusApp:/mnt/c/Program Files (x86)/Qualcomm/PCAT/bin:/mnt/c/Program Files (Arm)/Qualcomm/QualcommProfiler/CLI/target-wos/bins:/mnt/c/Program Files/usbipd-win/:/mnt/c/Users/moham/AppData/Local/Programs/Python/Python39/Scripts:/mnt/c/Users/moham/AppData/Local/Programs/Python/Python39:/mnt/c/Users/moham/.local/bin:/mnt/c/Users/moham/.cargo/bin:/mnt/c/Users/moham/.bin:/mnt/c/Users/moham/bin:/mnt/c/Program Files (x86)/GnuWin32/bin:/mnt/c/Program Files (x86)/Dr. Memory/bin:/mnt/c/Users/moham/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/moham/AppData/Local/PowerToys/DSCModules:/mnt/c/Users/moham/AppData/Local/Microsoft/WinGet/Links:/mnt/c/Users/moham/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools'
# Now it should work.
cargo build
```
