### ISSUE TITLE
Tests are not passing on OS X

### ISSUE THREAD

**Issue by winding-lines** [sfackler/rust-openssl#228]
I am trying to track down the cause of a compilation error in hyper, this is the issue:
https://github.com/hyperium/hyper/issues/575

When I run cargo test on rust-openssl I get the error at the bottom of this issue. I am trying to track this one down, any pointers appreciated :-)

My rustc version 

```
rustc -V
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
```

OS X version

```
sw_vers
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
```

Libssl

```
ls -l /usr/lib/libssl.*
-rwxr-xr-x  1 root  wheel  400608 Sep  9  2014 /usr/lib/libssl.0.9.7.dylib
-rwxr-xr-x  1 root  wheel  616512 Mar 19 19:16 /usr/lib/libssl.0.9.8.dylib
lrwxr-xr-x  1 root  wheel      18 Feb 22 00:56 /usr/lib/libssl.dylib -> libssl.0.9.8.dylib
```

The cargo test error:

```
 cargo test
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading byteorder v0.3.10
 Downloading connected_socket v0.0.6
 Downloading bitflags v0.2.1
   Compiling byteorder v0.3.10
   Compiling rustc-serialize v0.3.15
   Compiling gcc v0.3.8
   Compiling libc v0.1.8
   Compiling pkg-config v0.3.5
   Compiling bitflags v0.2.1
   Compiling lazy_static v0.1.11
   Compiling time v0.1.26
   Compiling openssl-sys v0.6.2 (file:///Users/user/oss/hyperium/rust-openssl/openssl)
   Compiling openssl v0.6.2 (file:///Users/user/oss/hyperium/rust-openssl/openssl)
   Compiling connected_socket v0.0.6
     Running target/debug/openssl-b3a0b1bcbf1488a6

running 61 tests
test bn::tests::test_to_from_slice ... ok
test bn::tests::test_negation ... ok
test crypto::hash::tests::test_clone ... ok
test crypto::hash::tests::test_finish_twice ... ok
test crypto::hash::tests::test_md5_recycle ... ok
test crypto::hash::tests::test_md5 ... ok
test crypto::hash::tests::test_sha1 ... ok
test crypto::hash::tests::test_ripemd160 ... ok
test crypto::hash::tests::test_sha256 ... ok
test crypto::hmac::tests::test_clone ... ok
test crypto::hmac::tests::test_finish_twice ... ok
test crypto::hmac::tests::test_hmac_md5 ... ok
test crypto::hmac::tests::test_hmac_md5_recycle ... ok
test crypto::hmac::tests::test_hmac_sha1 ... ok
test crypto::hmac::tests::test_hmac_sha1_recycle ... ok
test crypto::hmac::tests::test_hmac_sha224 ... ok
test crypto::hmac::tests::test_hmac_sha256 ... ok
test crypto::memcmp::tests::test_diff_lens ... ok
test crypto::memcmp::tests::test_eq ... ok
test crypto::hmac::tests::test_hmac_sha384 ... ok
test crypto::hmac::tests::test_hmac_sha512 ... ok
test crypto::pkey::tests::test_encrypt ... ok
test crypto::pkey::tests::test_encrypt_pkcs ... ok
test crypto::pkey::tests::test_gen_priv ... ok
test bn::tests::test_prime_numbers ... ok
test crypto::pkey::tests::test_private_key_from_pem ... ok
test crypto::pkey::tests::test_eq ... ok
test crypto::pkey::tests::test_gen_pub ... ok
test crypto::rand::tests::test_rand_bytes ... ok
test crypto::symm::tests::test_aes_256_cbc_decrypt ... ok
test crypto::symm::tests::test_aes_256_ecb ... ok
test crypto::symm::tests::test_rc4 ... ok
test ssl::error::test_uknown_error_should_have_correct_messages ... ok
test ssl::tests::clear_ctx_options::sslv23 ... FAILED
test ssl::tests::get_ctx_options::sslv23 ... FAILED
test ssl::tests::get_peer_certificate::sslv23 ... FAILED
test ssl::tests::new_ctx::sslv23 ... FAILED
test ssl::tests::new_sslstream::sslv23 ... FAILED
test ssl::tests::set_ctx_options::sslv23 ... FAILED
test ssl::tests::test_pending ... FAILED
test ssl::tests::test_read ... FAILED
test crypto::pkey::tests::test_sign_hashes ... ok
test ssl::tests::test_write ... FAILED
test ssl::tests::test_set_certificate_and_private_key ... ok
test ssl::tests::verify_callback_data::sslv23 ... FAILED
test ssl::tests::verify_callback_load_certs::sslv23 ... FAILED
test ssl::tests::verify_trusted::sslv23 ... FAILED
test ssl::tests::verify_trusted_callback_override_bad::sslv23 ... FAILED
test ssl::tests::verify_trusted_callback_override_ok::sslv23 ... FAILED
test ssl::tests::verify_trusted_get_error_err::sslv23 ... FAILED
test ssl::tests::verify_trusted_get_error_ok::sslv23 ... FAILED
test ssl::tests::verify_untrusted::sslv23 ... FAILED
test ssl::tests::verify_untrusted_callback_override_bad::sslv23 ... FAILED
test ssl::tests::verify_untrusted_callback_override_ok::sslv23 ... FAILED
test x509::test_negative_serial ... ok
test ssl::tests::test_write_hits_stream ... ok
test x509::tests::test_cert_loading ... ok
test x509::tests::test_subject_read_cn ... ok
test crypto::pkey::tests::test_sign ... ok
test x509::tests::test_cert_gen ... ok
test crypto::pkcs5::tests::test_pbkdf2_hmac_sha1 ... ok

failures:

---- ssl::tests::clear_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::clear_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::get_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::get_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::get_peer_certificate::sslv23 stdout ----
	thread 'ssl::tests::get_peer_certificate::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::new_ctx::sslv23 stdout ----
	thread 'ssl::tests::new_ctx::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::new_sslstream::sslv23 stdout ----
	thread 'ssl::tests::new_sslstream::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::set_ctx_options::sslv23 stdout ----
	thread 'ssl::tests::set_ctx_options::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_pending stdout ----
	thread 'ssl::tests::test_pending' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_read stdout ----
	thread 'ssl::tests::test_read' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::test_write stdout ----
	thread 'ssl::tests::test_write' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_callback_data::sslv23 stdout ----
	thread 'ssl::tests::verify_callback_data::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_callback_load_certs::sslv23 stdout ----
	thread 'ssl::tests::verify_callback_load_certs::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_callback_override_bad::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_callback_override_bad::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_callback_override_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_callback_override_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_get_error_err::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_get_error_err::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_trusted_get_error_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_trusted_get_error_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted_callback_override_bad::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted_callback_override_bad::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729


---- ssl::tests::verify_untrusted_callback_override_ok::sslv23 stdout ----
	thread 'ssl::tests::verify_untrusted_callback_override_ok::sslv23' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os(61) }', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729



failures:
    ssl::tests::clear_ctx_options::sslv23
    ssl::tests::get_ctx_options::sslv23
    ssl::tests::get_peer_certificate::sslv23
    ssl::tests::new_ctx::sslv23
    ssl::tests::new_sslstream::sslv23
    ssl::tests::set_ctx_options::sslv23
    ssl::tests::test_pending
    ssl::tests::test_read
    ssl::tests::test_write
    ssl::tests::verify_callback_data::sslv23
    ssl::tests::verify_callback_load_certs::sslv23
    ssl::tests::verify_trusted::sslv23
    ssl::tests::verify_trusted_callback_override_bad::sslv23
    ssl::tests::verify_trusted_callback_override_ok::sslv23
    ssl::tests::verify_trusted_get_error_err::sslv23
    ssl::tests::verify_trusted_get_error_ok::sslv23
    ssl::tests::verify_untrusted::sslv23
    ssl::tests::verify_untrusted_callback_override_bad::sslv23
    ssl::tests::verify_untrusted_callback_override_ok::sslv23

test result: FAILED. 42 passed; 19 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libtest/lib.rs:259
```

**Comment by sfackler** [comment]
Did you start the server the tests expect to talk to? https://github.com/sfackler/rust-openssl#testing

**Comment by winding-lines** [comment]
@sfackler I did not read the testing section, sorry about this.

**Comment by winding-lines** [comment]
The tests are passing when following the docs.
