### ISSUE TITLE
compile panic when build openssl-sys-extras

### ISSUE THREAD

**Issue by paomian** [sfackler/rust-openssl#422]
MacOS 10.11.6

rust version
```
rustc --version --verbose
rustc 1.12.0-nightly (27e766d7b 2016-07-19)
binary: rustc
commit-hash: 27e766d7bc84be992c8ddef710affc92ef4a0adf
commit-date: 2016-07-19
host: x86_64-apple-darwin
release: 1.12.0-nightly
```

cargo version
```
cargo --version --verbose
cargo 0.13.0-nightly (664125b 2016-07-19)
```

backtrace

```
 Running `rustc /Users/paomian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-extras-0.7.14/src/lib.rs --crate-name openssl_sys_extras --crate-type lib -C opt-level=3 -C metadata=5206753a3d8bd8ef -C extra-filename=-5206753a3d8bd8ef --out-dir /Users/paomian/work/leancloud/watch_sms/target/release/deps --emit=dep-info,link -L dependency=/Users/paomian/work/leancloud/watch_sms/target/release/deps -L dependency=/Users/paomian/work/leancloud/watch_sms/target/release/deps --extern libc=/Users/paomian/work/leancloud/watch_sms/target/release/deps/liblibc-1f3392fe1afd1313.rlib --extern openssl_sys=/Users/paomian/work/leancloud/watch_sms/target/release/deps/libopenssl_sys-1fd52a993b3834a7.rlib --cap-lints allow -L native=/Users/paomian/work/leancloud/watch_sms/target/release/build/openssl-sys-extras-5c7e4d8925825f00/out -l static=openssl_shim`
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:325
stack backtrace:
   1:        0x11066f4bb - std::sys::backtrace::tracing::imp::write::h29f5fdb9fc0a7395
   2:        0x110685c0a - std::panicking::default_hook::_{{closure}}::h2cc84f0378700526
   3:        0x11067e199 - std::panicking::default_hook::hbbe7fa36a995aca0
   4:        0x11067e8d8 - std::panicking::rust_panic_with_hook::h105c3d42fcd2fb5e
   5:        0x11067e736 - std::panicking::begin_panic::hbf62ea4a5ff3f9de
   6:        0x11067e648 - std::panicking::begin_panic_fmt::h20f5943904e5791d
   7:        0x11067e59f - rust_begin_unwind
   8:        0x1106e56f0 - core::panicking::panic_fmt::h19323e466869c656
   9:        0x1106e55ec - core::panicking::panic::hbfac80217e56ecbe
  10:        0x10bdb7e79 - rustc_trans::back::archive::ArchiveBuilder::build::h1952cdf1b375e1cb
  11:        0x10bdbe077 - rustc_trans::back::link::link_binary::h065439cf7e29e7cb
  12:        0x10b7a2403 - rustc_driver::driver::phase_6_link_output::h5291117a6f0eac61
  13:        0x10b7964f9 - rustc_driver::driver::compile_input::hb4cc34cf85dc1edf
  14:        0x10b7bacd5 - rustc_driver::run_compiler::h50f95674bd902ab5
  15:        0x10b827f10 - rustc_driver::run::_{{closure}}::h578f58fb80a79b9c
  16:        0x10b822b90 - rustc_driver::monitor::_{{closure}}::he296944eac047e81
  17:        0x10b725161 - std::panicking::try::call::h4577500a5284c6ff
  18:        0x11068c57b - __rust_try
  19:        0x11068c435 - __rust_maybe_catch_panic
  20:        0x10b7d1116 - std::thread::Builder::spawn::_{{closure}}::haaf8628155e4305c
  21:        0x10b73fca8 - _<F as alloc..boxed..FnBox<A>>::call_box::h24f3eb0b42327962
  22:        0x11067cc18 - std::sys::thread::Thread::new::thread_start::h8f3bd45211e9f5ea
  23:     0x7fff8d99c99c - _pthread_body
  24:     0x7fff8d99c919 - _pthread_start

error: Could not compile `openssl-sys-extras`.

Caused by:
  Process didn't exit successfully: `rustc /Users/paomian/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-extras-0.7.14/src/lib.rs --crate-name openssl_sys_extras --crate-type lib -C opt-level=3 -C metadata=5206753a3d8bd8ef -C extra-filename=-5206753a3d8bd8ef --out-dir /Users/paomian/work/leancloud/watch_sms/target/release/deps --emit=dep-info,link -L dependency=/Users/paomian/work/leancloud/watch_sms/target/release/deps -L dependency=/Users/paomian/work/leancloud/watch_sms/target/release/deps --extern libc=/Users/paomian/work/leancloud/watch_sms/target/release/deps/liblibc-1f3392fe1afd1313.rlib --extern openssl_sys=/Users/paomian/work/leancloud/watch_sms/target/release/deps/libopenssl_sys-1fd52a993b3834a7.rlib --cap-lints allow -L native=/Users/paomian/work/leancloud/watch_sms/target/release/build/openssl-sys-extras-5c7e4d8925825f00/out -l static=openssl_shim` (exit code: 101)
```

**Comment by paomian** [comment]
It is be ok after my run `cargo clean`

**Comment by caipre** [comment]
I'm seeing this as well, after adding `hyper` as a dependency. Running `cargo clean` did not resolve it for me.

```
$ rustup show
Default host: x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

x86_64-apple-darwin
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.14.0-nightly (9c31d76e9 2016-10-03)

$ RUST_BACKTRACE=1 cargo build
   Compiling winapi-build v0.1.1
   Compiling matches v0.1.2
   Compiling traitobject v0.0.1
   Compiling openssl-sys-extras v0.7.14
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `/Users/nick/code/license/target/debug/build/openssl-sys-extras-5c7e4d8925825f00/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-apple-darwin")
debug=true opt-level=0
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/Users/nick/code/license/target/debug/build/openssl-sys-extras-5c7e4d8925825f00/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c:1:10: fatal error: 'openssl/hmac.h' file not found
cargo:warning=#include <openssl/hmac.h>
cargo:warning=         ^
cargo:warning=1 error generated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /Users/nick/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
stack backtrace:
   1:        0x10c1e49d8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x10c1ea15f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x10c1e91f5 - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x10c1e9746 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x10c1b8993 - std::panicking::begin_panic::hc03e2830c2c89a5f
   6:        0x10c1d6f74 - gcc::fail::h2a055c6cc16590fd
   7:        0x10c1d6bc1 - gcc::run::ha89ebe3476bc7b02
   8:        0x10c1d051e - gcc::Config::compile_object::he228e01cb9943a10
   9:        0x10c1cfe7d - gcc::Config::compile_objects::h0a7b9e9b36a9f195
  10:        0x10c1cf45e - gcc::Config::compile::h41a4c4c4a1f71b1d
  11:        0x10c1accc5 - build_script_build::main::ha50cdac6616508f2
  12:        0x10c1ea71a - __rust_maybe_catch_panic
  13:        0x10c1e8d36 - std::rt::lang_start::h14cbded5fe3cd915
  14:        0x10c1ae099 - main
```

**Comment by caipre** [comment]
Ok, got it working. When `openssl` is installed with `brew`, the headers are in a nonstandard location:

``` shell
$ export LDFLAGS='-L/usr/local/opt/openssl/lib' CPPFLAGS='-I/usr/local/opt/openssl/include' PKG_CONFIG_PATH='/usr/local/opt/openssl/lib/pkgconfig'
$ cargo clean
$ cargo build # works now!
```
