### ISSUE TITLE
SSL_library_init crashes in runtime loaded library

### ISSUE THREAD

**Issue by mkroman** [sfackler/rust-openssl#451]
Hi,

I'm writing an IRC bot in Rust that loads plugins through a single shared library (also Rust) at runtime.

In my shared library I use `hyper`, which in effect uses `openssl`, and when I reload the shared library, the process segfaults, and it seems that the second calls to `SSL_library_init`/`openssl_sys::locking_function` is the cause.

Is there any way that I can preserve the initialized state in a shared library? Or is there a way to have `rust-openssl` know that it's actually initialized (if that's even the case?) - I can try and make a small test project if needed.

Here's the segfault:

```
Thread 1 "zeta" received signal SIGSEGV, Segmentation fault.
-----------------------------------------------------------------------------------------------------------------------[regs]
  RAX: 0x0000000000000000  RBX: 0x00007FFFF4BFF260  RBP: 0x00007FFFFFFFBF20  RSP: 0x00007FFFFFFFBF00  o d I t s z a P c 
  RDI: 0x0000000000000000  RSI: 0x0000000000000010  RDX: 0x00007FFFF79BD884  RCX: 0x00007FFFF79BD884  RIP: 0x00007FFFF4539885
  R8 : 0x00007FFFF660D4B0  R9 : 0x0000000000000002  R10: 0x0000000000000002  R11: 0x00005555559EE340  R12: 0x00007FFFFFFFC322
  R13: 0x0000000000000000  R14: 0x0000000000000000  R15: 0x0000000000000000
  CS: 0033  DS: 0000  ES: 0000  FS: 0000  GS: 0000  SS: 002B                
-----------------------------------------------------------------------------------------------------------------------[code]
=> 0x7ffff4539885 <alloc::raw_vec::{{impl}}::ptr<std::sync::mutex::Mutex<()>>+37>:  mov    rax,QWORD PTR [rax]
   0x7ffff4539888 <alloc::raw_vec::{{impl}}::ptr<std::sync::mutex::Mutex<()>>+40>:  add    rsp,0x20
   0x7ffff453988c <alloc::raw_vec::{{impl}}::ptr<std::sync::mutex::Mutex<()>>+44>:  pop    rbp
   0x7ffff453988d <alloc::raw_vec::{{impl}}::ptr<std::sync::mutex::Mutex<()>>+45>:  ret    
   0x7ffff453988e:  xchg   ax,ax
   0x7ffff4539890 <alloc::raw_vec::{{impl}}::double<std::sync::mutex::Mutex<()>>>:  push   rbp
   0x7ffff4539891 <alloc::raw_vec::{{impl}}::double<std::sync::mutex::Mutex<()>>+1>:    mov    rbp,rsp
   0x7ffff4539894 <alloc::raw_vec::{{impl}}::double<std::sync::mutex::Mutex<()>>+4>:    sub    rsp,0xc0
-----------------------------------------------------------------------------------------------------------------------------
```

And here's the backtrace:

```
#0  0x00007ffff4539885 in alloc::raw_vec::{{impl}}::ptr<std::sync::mutex::Mutex<()>> (self=0x0) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/liballoc/raw_vec.rs:144
#1  0x00007ffff453de5d in collections::vec::{{impl}}::deref<std::sync::mutex::Mutex<()>> (self=0x0) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1383
#2  0x00007ffff453e1d9 in collections::vec::{{impl}}::index<std::sync::mutex::Mutex<()>> (self=0x0, index=0x10) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1265
#3  0x00007ffff453f9b6 in openssl_sys::locking_function (mode=0x5, n=0x10, _file=0x7ffff79bd884 "ssl_ciph.c", _line=0x1db) at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.7.17/src/lib.rs:503
#4  0x00007ffff79b2a6c in SSL_COMP_get_compression_methods () from /usr/lib/libssl.so.1.0.0
#5  0x00007ffff79b8900 in SSL_library_init () from /usr/lib/libssl.so.1.0.0
#6  0x00007ffff4540c1e in openssl_sys::init::{{closure}} () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.7.17/src/lib.rs:517
#7  0x00007ffff4540bde in std::sync::once::{{impl}}::call_once::{{closure}}<closure> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/once.rs:210
#8  0x00007ffff38bea1b in std::sync::once::Once::call_inner::hb0be5feef125689a () from /home/mk/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-411f48d3.so
#9  0x00007ffff4539270 in std::sync::once::{{impl}}::call_once<closure> (self=0x7ffff4bff260 <openssl_sys::init::INIT::hbb89a2ce7afa7ce3>, f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/once.rs:210
#10 0x00007ffff453fb27 in openssl_sys::init () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.7.17/src/lib.rs:515
#11 0x00007ffff4534ffd in openssl::ssl::init::{{closure}} () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.7.14/src/ssl/mod.rs:58
#12 0x00007ffff4534fce in std::sync::once::{{impl}}::call_once::{{closure}}<closure> () at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/once.rs:210
#13 0x00007ffff38bea1b in std::sync::once::Once::call_inner::hb0be5feef125689a () from /home/mk/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-411f48d3.so
#14 0x00007ffff44f8090 in std::sync::once::{{impl}}::call_once<closure> (self=0x7ffff4bff228 <openssl::ssl::init::INIT::h897b1760825a4825>, f=...) at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sync/once.rs:210
#15 0x00007ffff4526677 in openssl::ssl::init () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.7.14/src/ssl/mod.rs:57
#16 0x00007ffff452b8d4 in openssl::ssl::{{impl}}::new (method=Sslv23) at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.7.14/src/ssl/mod.rs:563
#17 0x00007ffff426e8d3 in hyper::net::openssl::{{impl}}::default () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.9.10/src/net.rs:657
#18 0x00007ffff426e155 in hyper::net::{{impl}}::default<hyper::net::openssl::OpensslClient,hyper::net::HttpConnector> () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.9.10/src/net.rs:571
#19 0x00007ffff421ae70 in hyper::client::pool::{{impl}}::new (config=...) at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.9.10/src/client/pool.rs:68
#20 0x00007ffff42210ae in hyper::client::{{impl}}::with_pool_config (config=...) at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.9.10/src/client/mod.rs:123
#21 0x00007ffff4221059 in hyper::client::{{impl}}::new () at /home/mk/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.9.10/src/client/mod.rs:118
#22 0x00007ffff3d62545 in zeta_plugins::google_search::{{impl}}::new () at /home/mk/Projects/Zeta/plugins/src/google_search.rs:13
#23 0x00007ffff3d5d673 in zeta::plugin::{{impl}}::register<zeta_plugins::google_search::GoogleSearch> (self=0x7fffffffdd70) at /home/mk/Projects/Zeta/src/plugin.rs:60
#24 0x00007ffff3d6305d in zeta_plugins::google_search::register (plugins=0x7fffffffdd70) at /home/mk/Projects/Zeta/plugins/src/google_search.rs:38
#25 0x00007ffff3d63396 in zeta_plugins::register_plugins (plugins=0x7fffffffdd70) at /home/mk/Projects/Zeta/plugins/src/lib.rs:46
#26 0x00005555556cf121 in zeta::plugin::{{impl}}::load (self=0x7fffffffdd70) at /home/mk/Projects/Zeta/src/plugin.rs:84
#27 0x00005555556cf297 in zeta::plugin::{{impl}}::reload (self=0x7fffffffdd70) at /home/mk/Projects/Zeta/src/plugin.rs:103
#28 0x00005555556d0065 in zeta::{{impl}}::run (self=0x7fffffffdbb0) at /home/mk/Projects/Zeta/src/lib.rs:85
#29 0x00005555555a7c31 in zeta::main () at /home/mk/Projects/Zeta/src/main.rs:33
#30 0x0000555555910767 in __rust_maybe_catch_panic ()
#31 0x0000555555907422 in std::rt::lang_start::haaae1186de9de8cb ()
#32 0x00005555555b1cd4 in main ()
```

**Comment by sfackler** [comment]
Now that 0.9 supports OpenSSL 1.1, you may want to upgrade to that - it no longer requires explicit initialization.
