### ISSUE TITLE
failed to run custom build command for `openssl v0.7.14`

### ISSUE THREAD

**Issue by szagi3891** [sfackler/rust-openssl#489]
when I try run hyper package crate in mac I get error :

```
Successfully generated ./build/index.elm.js
   Compiling openssl v0.7.14
   Compiling openssl-sys-extras v0.7.14
   Compiling url v1.2.2
Build failed, waiting for other jobs to finish...
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `/Users/grzegorz/Desktop/elmtest/src/server/target/debug/build/openssl-5464f8f6e728c35a/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-apple-darwin")
debug=true opt-level=0
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/Users/grzegorz/Desktop/elmtest/src/server/target/debug/build/openssl-5464f8f6e728c35a/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
cargo:warning=#include <openssl/ssl.h>
cargo:warning=         ^
cargo:warning=1 error generated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /Users/grzegorz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.37/src/lib.rs:952
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-openssl/tree/b8fb29db5c246175a096260eacca38180cd77dd0#osx

**Comment by szagi3891** [comment]
I have installed openssl:

```
iMac-grzegorz:server grzegorz$ openssl version
OpenSSL 0.9.8zh 14 Jan 2016
iMac-grzegorz:server grzegorz$ echo $OPENSSL_INCLUDE_DIR
/usr/local/opt/openssl/include
iMac-grzegorz:server grzegorz$ echo $OPENSSL_LIB_DIR
/usr/local/opt/openssl/lib
iMac-grzegorz:server grzegorz$ cargo build
   Compiling openssl v0.7.14
   Compiling openssl-sys-extras v0.7.14
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `/Users/grzegorz/Desktop/elmtest/src/server/target/debug/build/openssl-5464f8f6e728c35a/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-apple-darwin")
debug=true opt-level=0
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
HOST = Some("x86_64-apple-darwin")
TARGET = Some("x86_64-apple-darwin")
HOST = Some("x86_64-apple-darwin")
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-fPIC" "-o" "/Users/grzegorz/Desktop/elmtest/src/server/target/debug/build/openssl-5464f8f6e728c35a/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c:1:10: fatal error: 'openssl/ssl.h' file not found
cargo:warning=#include <openssl/ssl.h>
cargo:warning=         ^
cargo:warning=1 error generated.
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /Users/grzegorz/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.37/src/lib.rs:952
note: Run with `RUST_BACKTRACE=1` for a backtrace.

iMac-grzegorz:server grzegorz$ 
```

**Comment by sfackler** [comment]
Try a cargo clean and a cargo build.

**Comment by szagi3891** [comment]
Now it worked.

**Comment by martindeegan** [comment]
I was trying to compile for the pi. For me, I had to restart after installing openssl.

**Comment by zm1060** [comment]
You should update your openssl with `sudo apt install libssl-dev`
then `sudo rm -rf Cargo.lock target/`
last  `sudo cargo build`  rebuild it
