### ISSUE TITLE
Tests failing on 1.1.0c

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-openssl#520]
```
---- ssl::tests::connector_valid_hostname stdout ----
	thread 'ssl::tests::connector_valid_hostname' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("BUG: got an ErrorSyscall without an error in the BIO?") }) }', ../src/libcore/result.rs:799

---- ssl::tests::default_verify_paths stdout ----
	thread 'ssl::tests::default_verify_paths' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(10.203.94.100:59085), peer: V4(217.163.64.94:443), fd: 4 }, ssl: Ssl { state: "error", verify_result: X509VerifyError { code: 19, error: "self signed certificate in certificate chain" } } }, error: Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed" }])) })', ../src/libcore/result.rs:799

---- ssl::tests::test_pending stdout ----
	thread 'ssl::tests::test_pending' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("BUG: got an ErrorSyscall without an error in the BIO?") }) }', ../src/libcore/result.rs:799

---- ssl::tests::test_read stdout ----
	thread 'ssl::tests::test_read' panicked at 'read error', ../src/libcore/option.rs:705
```

**Comment by sfackler** [comment]
It appears that the error is popping up when the socket hits EOF. It seems like we're doing the same thing in response to that (just return 0) as OpenSSL's built in socket BIOs, so I'm not sure what's going on yet.

**Comment by sfackler** [comment]
Looks like this commit is the culprit: https://github.com/openssl/openssl/commit/4880672a9b41a09a0984b55e219f02a2de7ab75e

**Comment by sfackler** [comment]
Fixed in https://github.com/sfackler/rust-openssl/commit/898e7f02df5ca722f4b4b42a8e116f96f72b9452
