### ISSUE TITLE
failed to run custom build command for `openssl v0.7.14` on Windows 10 x64

### ISSUE THREAD

**Issue by Borkason** [sfackler/rust-openssl#595]
Preface: I installed [Win64 OpenSSL v1.1.0e](https://slproweb.com/download/Win64OpenSSL-1_1_0e.exe) and set the ENV variable like so `set OPENSSL_DIR=C:\OpenSSL-Win64`.

Trying to run the following code with `cargo clean` and `cargo build` on Windows 10 Pro (x64):

```rust
extern crate irc;

use std::default::Default;
use irc::client::prelude::*;

fn main() {
    let cfg = Config {
        nickname: Some(format!("Borkason-bot")),
        server: Some(format!("irc.mozilla.org")),
        channels: Some(vec![format!("#test")]),
        .. Default::default()
    };
    let server = IrcServer::from_config(cfg).unwrap();
    server.identify().unwrap();
    for message in server.iter() {
        // Do message processing.
    }
}
```

Source: https://github.com/aatxe/irc

Error message with backtrace:

```

C:\Users\Borkason\Documents\programming\rust>cargo build
   Compiling winapi-build v0.1.1
   Compiling libc v0.2.21
   Compiling pkg-config v0.3.9
   Compiling bitflags v0.7.0
   Compiling gcc v0.3.43
   Compiling encoding_index_tests v0.1.4
   Compiling gdi32-sys v0.2.0
   Compiling kernel32-sys v0.2.2
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling user32-sys v0.2.0
   Compiling openssl-sys v0.7.17
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling lazy_static v0.2.4
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling winapi v0.2.8
   Compiling encoding-index-korean v1.20141219.5
   Compiling openssl v0.7.14
   Compiling openssl-sys-extras v0.7.14
   Compiling encoding v0.2.33
Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `C:\Users\Borkason\Documents\programming\rust\target\debug\build\openssl-a0ff3cdd6ccfd560\build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\cl.exe" "/nologo" "/MD" "/Z7" "/FoC:\\Users\\Borkason\\Documents\\programming\\rust\\target\\debug\\build\\openssl-87c538093dbe2342\\out\\src\\c_helpers.o" "/c" "src/c_helpers.c"
ExitStatus(ExitStatus(2))


command did not execute successfully, got: exit code: 2



--- stderr
thread 'main' panicked at 'explicit panic', C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:1127
stack backtrace:
   0:     0x7ff6e005ba3a - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:354
   1:     0x7ff6e005af46 - std::panicking::default_hook
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:365
   2:     0x7ff6e005e8ad - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:553
   3:     0x7ff6e0008ca7 - std::panicking::begin_panic<&str>
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:515
   4:     0x7ff6e00441cf - gcc::fail
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:1127
   5:     0x7ff6e00438d0 - gcc::run
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:1120
   6:     0x7ff6e003a0c4 - gcc::Config::compile_object
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:482
   7:     0x7ff6e0039ae5 - gcc::Config::compile_objects
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:448
   8:     0x7ff6e0038a75 - gcc::Config::compile
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.43\src\lib.rs:398
   9:     0x7ff6dfff37fb - build_script_build::main
                        at C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\build.rs:15
  10:     0x7ff6e0060fd1 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
  11:     0x7ff6e005ee9a - std::rt::lang_start
                        at C:\bot\slave\stable-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
  12:     0x7ff6dfff3a0b - main
  13:     0x7ff6e0065368 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:259
  14:     0x7ffae3ce36f3 - BaseThreadInitThunk


C:\Users\Borkason\Documents\programming\rust>
```

**Comment by Borkason** [comment]
Trying to run the command separately:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe" /nologo /MD /Z7 /I C:\OpenSSL-Win64\include /FoC:\Users\Borkason\Documents\programming\rust\target\debug\build\openssl-87c538093dbe2342\out\src\c_helpers.o /c C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c
c_helpers.c
C:\OpenSSL-Win64\include\openssl/lhash.h(198): warning C4090: "Funktion": different "const" qualifiers
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(4): error C2037: left of "references" specifies undefined struct/union "ssl_st"
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(4): error C2065: "CRYPTO_LOCK_SSL": undeclared identifier
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(8): error C2037: left of "references" specifies undefined struct/union "ssl_ctx_st"
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(8): error C2065: "CRYPTO_LOCK_SSL_CTX": undeclared identifier
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(12): error C2037: left of "references" specifies undefined struct/union "x509_st"
C:\Users\Borkason\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-0.7.14\src\c_helpers.c(12): error C2065: "CRYPTO_LOCK_X509": undeclared identifier

C:\Users\Borkason\Documents\Programmierung\Rust\xbot>echo %errorlevel%
2
```

**Comment by Borkason** [comment]
I just realised that this may have to do because of 0.7.14 being out of date. I'll close this for now.

**Comment by astleychen** [comment]
So did upgrade fix your issue here? I'm running into same issue too and dunno how to fix it...

**Comment by davidpodhola** [comment]
same here

**Comment by kevinw** [comment]
Hitting this issue as well.

**Comment by sfackler** [comment]
rust-openssl 0.7 doesn't support OpenSSL 1.1.0. Upgrade rust-openssl or downgrade OpenSSL.
