### ISSUE TITLE
lock already unlocked

### ISSUE THREAD

**Issue by mmacedoeu** [sfackler/rust-openssl#620]
I am getting this error trying to connect to a PostgreSQL database using diesel crate:

```
thread '<unnamed>' panicked at 'lock already unlocked', /buildslave/rust-buildbo
t/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
stack backtrace:
   1:     0x563eab7a846c - std::sys::imp::backtrace::tracing::imp::write::hf33ae
72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-lin
ux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x563eab7ac91e - std::panicking::default_hook::{{closure}}::h59672b733
cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-lin
ux/build/src/libstd/panicking.rs:351
   3:     0x563eab7ac524 - std::panicking::default_hook::h1670459d2f3f8843
```

What can possibly causing the issue ? And, is it possible to generate a rust Error instead of panic ?

**Comment by sfackler** [comment]
This is happening from OpenSSL's locking callback - if it's trying to unlock a lock that isn't locked, that seems bad: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/ossl10x.rs#L718.

Is that the entire stack trace?

**Comment by mmacedoeu** [comment]
here is the full stack trace:

```
thread '<unnamed>' panicked at 'lock already unlocked', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
stack backtrace:
   1:     0x55800535820c - std::sys::imp::backtrace::tracing::imp::write::hf33ae72d0baa11ed
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55800535c6be - std::panicking::default_hook::{{closure}}::h59672b733cc6a455
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55800535c2c4 - std::panicking::default_hook::h1670459d2f3f8843
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55800535cb5b - std::panicking::rust_panic_with_hook::hcf0ddb069e7beee7
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55800535c9f4 - std::panicking::begin_panic::hd6eb68e27bdf6140
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55800535c919 - std::panicking::begin_panic_fmt::hfea5965948b877f8
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55800535c8a7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55800538946d - core::panicking::panic_fmt::hc0f6d7b2c300cdd9
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x5580053894fd - core::option::expect_failed::h43c73e9bd7dbebbc
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:715
  10:     0x558005271c5b - <core::option::Option<T>>::expect::h77b865cf5b724766
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/option.rs:293
  11:     0x5580052764ba - openssl_sys::ossl10x::locking_function::he902512ccfdfec30
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.11/src/ossl10x.rs:725
  12:     0x7fcfbbd456c8 - <unknown>
  13:     0x7fcfbc0aba1d - SSL_CTX_new
  14:     0x7fcfbc2f4485 - <unknown>
  15:     0x7fcfbc2e53d6 - PQconnectPoll
  16:     0x7fcfbc2e569d - <unknown>
  17:     0x7fcfbc2e6046 - PQconnectdb
  18:     0x558004e7c18b - diesel::pg::connection::raw::RawConnection::establish::ha0f6f21e8876e937
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-0.12.0/src/pg/connection/raw.rs:22
  19:     0x558004e7e97e - <diesel::pg::connection::PgConnection as diesel::connection::Connection>::establish::h985d14f5bd0bf56b
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-0.12.0/src/pg/connection/mod.rs:51
  20:     0x558004b7dff6 - diesel_meta::establish_connection::h4743397aca2ff22a
                        at /home/macedo/w/yourcoin/crates/diesel_meta/src/lib.rs:53
  21:     0x558004afc7f1 - <yourcoin::impls::claim::ClaimClient as yourcoin::traits::claim::Claim>::claim_new::{{closure}}::{{closure}}::hea3730f3753a3657
                        at /home/macedo/w/yourcoin/src/impls/claim.rs:171
  22:     0x558004a2dc7c - <futures::future::lazy::Lazy<F, R>>::get::ha504fb2f0afa8c6b
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/lazy.rs:64
  23:     0x558004ad3b37 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h23d73299dcf89262
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/lazy.rs:82
  24:     0x558004ab1e2b - futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::h0883a15fa8db3c0a
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/catch_unwind.rs:49
  25:     0x558004ae7ee2 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}::he14e63c6a64b6627
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/catch_unwind.rs:32
  26:     0x5580049a0274 - std::panicking::try::do_call::h1b91ee8e07df7838
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  27:     0x558005363b2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  28:     0x55800499da50 - std::panicking::try::h2f8908dd4a8176b3
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
  29:     0x55800499bbc0 - std::panic::catch_unwind::hca4621ea8cd88618
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
  30:     0x558004ae29c2 - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::h3a9c519b728e328a
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/catch_unwind.rs:32
  31:     0x55800495bf54 - <futures_cpupool::MySender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll::h5619330147c2956c
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.5/src/lib.rs:291
  32:     0x558005075181 - <alloc::boxed::Box<F> as futures::future::Future>::poll::h785ffaafa2403c37
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/future/mod.rs:77
  33:     0x55800507613c - <futures::task_impl::Spawn<F>>::poll_future::{{closure}}::ha6c39635054ce25f
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  34:     0x55800507632e - <futures::task_impl::Spawn<T>>::enter::{{closure}}::hb3c1ba7c5f0c1929
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  35:     0x558005075baa - futures::task_impl::set::{{closure}}::h50b50ea5a42df975
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  36:     0x558005070167 - <std::thread::local::LocalKey<T>>::with::hc43db08f46f41955
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/local.rs:253
  37:     0x558005075a53 - futures::task_impl::set::he0e0f4e7e728f9b2
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  38:     0x558005076252 - <futures::task_impl::Spawn<T>>::enter::h14da077b9a7144ff
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  39:     0x5580050760c7 - <futures::task_impl::Spawn<F>>::poll_future::he032bce317e65774
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  40:     0x5580050765ec - futures::task_impl::Run::run::hab7cbbe6c82c7d35
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.13/src/lib.rs:199
  41:     0x558004f758da - futures_cpupool::Inner::work::h450d329faeb0a272
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.5/src/lib.rs:223
  42:     0x558004f76573 - futures_cpupool::Builder::create::{{closure}}::h2fae87a21d4eb7fa
                        at /home/macedo/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.5/src/lib.rs:379
  43:     0x558004f7518c - <std::panic::AssertUnwindSafe<F> as core::ops::FnOnce<()>>::call_once::h384747e419084a1d
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:296
  44:     0x558004f5d5e0 - std::panicking::try::do_call::h4e5e8aa0ebcad753
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:460
  45:     0x558005363b2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  46:     0x558004f5d36f - std::panicking::try::h2fa7a16e2b015237
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panicking.rs:436
  47:     0x558004f5c66b - std::panic::catch_unwind::h7d58d5452764471e
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/panic.rs:361
  48:     0x558004f5d04e - std::thread::Builder::spawn::{{closure}}::hd3a8644fe922a84b
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
  49:     0x558004f6e20b - <F as alloc::boxed::FnBox<A>>::call_box::he4c248a1819ca945
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:614
  50:     0x55800535b9a4 - std::sys::imp::thread::Thread::new::thread_start::he668872ac11287ba
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/liballoc/boxed.rs:624
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  51:     0x7fcfbb6076a9 - start_thread
  52:     0x7fcfbb12613c - __clone
  53:                0x0 - <unknown>

```

**Comment by sfackler** [comment]
Which version of OpenSSL do you have? It'd also be helpful to get a stack trace with OpenSSL debuginfo if that's easy on your end.

**Comment by mmacedoeu** [comment]
```
$openssl version -v
OpenSSL 1.0.2d 9 Jul 2015
```

How can generate OpenSSL debuginfo ?

**Comment by sfackler** [comment]
Assuming that OpenSSL is installed through your system's package manager, there's usually another package you can install which will have it. For example, with RHEL: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/intro.debuginfo.html.

**Comment by mmacedoeu** [comment]
I am on Ubuntu, libssl-dev is installed but don't if it's enough

**Comment by sfackler** [comment]
There's some information here on how to get debuginfo packages for Ubuntu: https://wiki.ubuntu.com/Debug%20Symbol%20Packages

**Comment by mmacedoeu** [comment]
I saw but can't find any libssl-dbg package, for now I will switch to a docker based environment so at least it is easier to reproduce

**Comment by sfackler** [comment]
Ah, I missed something in that stack trace!

Diesel uses libpq, a C library, which itself interacts with OpenSSL. If libpq and rust-openssl are fighting over the initialization here, things could go bad in this kind of way. It looks like there are some methods to control initialization on the libpq side: https://www.postgresql.org/docs/9.0/static/libpq-ssl.html.

@sgrif - what does diesel with regard to OpenSSL initialization?

**Comment by sgrif** [comment]
We defer entirely to libpq for SSL

**Comment by sfackler** [comment]
Ok, my gut feeling is that this is the issue, and calling `openssl::init()` followed by `PQinitSSL(0)` would make things happy. That seems like a real mess though :(

**Comment by sgrif** [comment]
Yay global state! Thanks, C

**Comment by sfackler** [comment]
It is really the best thing. Luckily OpenSSL 1.1.0 doesn't need an explicit init step, so everyone will be fine in 10 or so years when that hits LTS distros.

**Comment by mmacedoeu** [comment]
I have tried it on a docker environment, and error could be reproduced. I am using the following Dockerfile:

```
FROM alpine:edge

RUN echo '@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories

RUN apk add --no-cache \
  cargo@testing \
  g++ \
  rust@testing \
  bash \
  openssl \
  openssl-dev \
  openssl-dbg \
  openssh \
  make \
  libpq \
  postgresql-client \
  git && rm -rf /var/cache/apk/*

RUN ln -s /usr/lib/libpq.so.5.9 /usr/lib/libpq.so

WORKDIR /source

```

**Comment by sfackler** [comment]
Can you try sticking this in your main function?

```rust
extern {
    fn PQinitSSL(do_ssl: c_int);
}

fn main() {
   openssl::init();
   unsafe { PQinitSSL(0) };

   // normal stuff from here...
}
```

If my assumptions above were right, you shouldn't see the panic anymore. Once we've confirmed that we can try to figure out how to make the right thing happen by default.

**Comment by sfackler** [comment]
Ping

**Comment by mmacedoeu** [comment]
The scenario of failure has been compromised as we changed the solution to use a not so performantic sequencial operation instead of parallel. This erased the race but we can't change it back now to test your solution.

**Comment by sfackler** [comment]
Cool, no worries.
