### ISSUE TITLE
Unable to build the openssl-sys-extras crate on archlinux

### ISSUE THREAD

**Issue by vityafx** [sfackler/rust-openssl#631]
Whenever I try to build this crate on archlinux I get these errors:

```rustc
error: Could not compile `openssl-sys-extras`.
Build failed, waiting for other jobs to finish...
error: could not find native static library `_rust_crypto_helpers`, perhaps an -L flag is missing?
```

But it builds good on debian 8. How to build it on archlinux?

**Comment by sfackler** [comment]
Arch recently updated to OpenSSL 1.1.0, which the very old versions of rust-openssl which use `openssl-sys-extras` do not support. You should update to the 0.9 series.

**Comment by vityafx** [comment]
I think, I don't have any way for compile my project if one of it's dependencies use `openssl-sys-extras` 0.7.14 ?

**Comment by sfackler** [comment]
You could build your own copy of OpenSSL 1.0.2 and point rust-openssl towards it with some [environment variables](https://github.com/sfackler/rust-openssl/blob/b8fb29db5c246175a096260eacca38180cd77dd0/README.md#manual-configuration).

**Comment by badboy** [comment]
There's [`openssl-1.0`](https://www.archlinux.org/packages/extra/x86_64/openssl-1.0/) in the `extra` repository.

**Comment by vityafx** [comment]
I have installed it but now I have different errors while compiling `openssl` crate:

```
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `/home/fx/workspace/stonedguy/target/debug/build/openssl-f2d87cfdc2e2aa2f/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/home/fx/workspace/stonedguy/target/debug/build/openssl-1d3ea894fa03cc5a/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c: В функции «rust_SSL_clone»:
cargo:warning=src/c_helpers.c:4:5: предупреждение: неявная декларация функции «CRYPTO_add» [-Wimplicit-function-declaration]
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=     ^~~~~~~~~~
cargo:warning=src/c_helpers.c:4:20: ошибка: dereferencing pointer to incomplete type «SSL {aka struct ssl_st}»
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                    ^~
cargo:warning=src/c_helpers.c:4:37: ошибка: «CRYPTO_LOCK_SSL» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                                     ^~~~~~~~~~~~~~~
cargo:warning=src/c_helpers.c:4:37: замечание: сообщение о каждом неописанном идентификаторе выдается один раз в каждой функции, где он встречается
cargo:warning=src/c_helpers.c: В функции «rust_SSL_CTX_clone»:
cargo:warning=src/c_helpers.c:8:20: ошибка: dereferencing pointer to incomplete type «SSL_CTX {aka struct ssl_ctx_st}»
cargo:warning=     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                    ^~
cargo:warning=src/c_helpers.c:8:35: ошибка: «CRYPTO_LOCK_SSL_CTX» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                                   ^~~~~~~~~~~~~~~~~~~
cargo:warning=src/c_helpers.c: В функции «rust_X509_clone»:
cargo:warning=src/c_helpers.c:12:21: ошибка: dereferencing pointer to incomplete type «X509 {aka struct x509_st}»
cargo:warning=     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                     ^~
cargo:warning=src/c_helpers.c:12:36: ошибка: «CRYPTO_LOCK_X509» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                                    ^~~~~~~~~~~~~~~~
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/fx/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.45/src/lib.rs:1152
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

And
```

error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `/home/fx/workspace/stonedguy/target/debug/build/openssl-sys-extras-f9e8037051c16bfa/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-o" "/home/fx/workspace/stonedguy/target/debug/build/openssl-sys-extras-8e2dc543f8892677/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c: В функции «DH_new_from_params»:
cargo:warning=src/openssl_shim.c:132:7: ошибка: dereferencing pointer to incomplete type «DH {aka struct dh_st}»
cargo:warning=     dh->p = p;
cargo:warning=       ^~
cargo:warning=src/openssl_shim.c: В функции «X509_get_extensions_shim»:
cargo:warning=src/openssl_shim.c:143:13: ошибка: dereferencing pointer to incomplete type «X509 {aka struct x509_st}»
cargo:warning=     return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=             ^~
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/fx/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.45/src/lib.rs:1152
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by vityafx** [comment]
@sfackler Can I have any comments on message above please?

**Comment by sfackler** [comment]
It looks like it's finding the OpenSSL 1.1.0 headers.

**Comment by vityafx** [comment]
@sfackler I have double-checked and it points to 1.0.2 version:

```
error: failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `/home/fx/workspace/stonedguy/target/debug/build/openssl-f2d87cfdc2e2aa2f/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "/usr/include/openssl-1.0/openssl/" "-o" "/home/fx/workspace/stonedguy/target/debug/build/openssl-1d3ea894fa03cc5a/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c: В функции «rust_SSL_clone»:
cargo:warning=src/c_helpers.c:4:5: предупреждение: неявная декларация функции «CRYPTO_add» [-Wimplicit-function-declaration]
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=     ^~~~~~~~~~
cargo:warning=src/c_helpers.c:4:20: ошибка: dereferencing pointer to incomplete type «SSL {aka struct ssl_st}»
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                    ^~
cargo:warning=src/c_helpers.c:4:37: ошибка: «CRYPTO_LOCK_SSL» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=                                     ^~~~~~~~~~~~~~~
cargo:warning=src/c_helpers.c:4:37: замечание: сообщение о каждом неописанном идентификаторе выдается один раз в каждой функции, где он встречается
cargo:warning=src/c_helpers.c: В функции «rust_SSL_CTX_clone»:
cargo:warning=src/c_helpers.c:8:20: ошибка: dereferencing pointer to incomplete type «SSL_CTX {aka struct ssl_ctx_st}»
cargo:warning=     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                    ^~
cargo:warning=src/c_helpers.c:8:35: ошибка: «CRYPTO_LOCK_SSL_CTX» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=                                   ^~~~~~~~~~~~~~~~~~~
cargo:warning=src/c_helpers.c: В функции «rust_X509_clone»:
cargo:warning=src/c_helpers.c:12:21: ошибка: dereferencing pointer to incomplete type «X509 {aka struct x509_st}»
cargo:warning=     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                     ^~
cargo:warning=src/c_helpers.c:12:36: ошибка: «CRYPTO_LOCK_X509» не описан (первое использование в этой функции)
cargo:warning=     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=                                    ^~~~~~~~~~~~~~~~
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/fx/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.45/src/lib.rs:1152
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl-sys-extras v0.7.14`
process didn't exit successfully: `/home/fx/workspace/stonedguy/target/debug/build/openssl-sys-extras-f9e8037051c16bfa/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-I" "/usr/include/openssl-1.0/openssl/" "-o" "/home/fx/workspace/stonedguy/target/debug/build/openssl-sys-extras-8e2dc543f8892677/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c: В функции «DH_new_from_params»:
cargo:warning=src/openssl_shim.c:132:7: ошибка: dereferencing pointer to incomplete type «DH {aka struct dh_st}»
cargo:warning=     dh->p = p;
cargo:warning=       ^~
cargo:warning=src/openssl_shim.c: В функции «X509_get_extensions_shim»:
cargo:warning=src/openssl_shim.c:143:13: ошибка: dereferencing pointer to incomplete type «X509 {aka struct x509_st}»
cargo:warning=     return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=             ^~
ExitStatus(ExitStatus(256))


command did not execute successfully, got: exit code: 1



--- stderr
thread 'main' panicked at 'explicit panic', /home/fx/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.45/src/lib.rs:1152
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by vityafx** [comment]
@sfackler you were right. As @badboy said, there was a openssl-1.0 package for archlinux with old version. Before `cargo build` I must have performed `cargo clean`. Everything works now.

**Comment by sfackler** [comment]
Great!

**Comment by vityafx** [comment]
@sfackler here is some interesting thing. I could compile my crate but I am unable to run it on debian 8. I have checked many times versions of openssl on both systems - they are identical according to the `openssl/opensslv.h` file but when I run my crate on debian I see errors:

$ ./s
./s: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0: version `OPENSSL_1.0.2d' not found (required by ./s)
./s: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.2d' not found (required by ./s)

**Comment by sfackler** [comment]
Are there two versions of `libcrypto.so` on the system? You may need to set `LD_LIBRARY_PATH` to wherever the other one is.

**Comment by vityafx** [comment]
@sfackler yes, on archlinux I have 2 versions - old one and latest one (1.1.0). But there is only one libcrypto on the debian there.

**Comment by sfackler** [comment]
Oh wait, you compiled it on Arch and want to run it on Debian? That's not going to work if those two distro's OpenSSLs aren't binary compatible, which it seems like they aren't based off of that dynamic linker error.

**Comment by vityafx** [comment]
@sfackler so I have to compile on debian?

**Comment by sfackler** [comment]
You could do that, or statically link to OpenSSL. That's what Cargo does, for example, though there are some tricky bits there around tracking down the system trust root.

**Comment by vityafx** [comment]
@sfackler hope one day rust will have a pure-rust crates to substitute openssl.

**Comment by Yamakaky** [comment]
For me, `OPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0 OPENSSL_LIB_DIR=/usr/lib/openssl-1.0 cargo build` works. Could you add it in the README as an arch specific fix?
