### ISSUE TITLE
tests fail with libressl-2.5.4

### ISSUE THREAD

**Issue by Gottox** [sfackler/rust-openssl#632]
System
---------
* System: VoidLinux
* Kernel: Linux 4.11.0 (vanilla)
* rustc version: rustc 1.17.0
* libressl version: 2.5.4

Cargo Test
---------------
```
cargo test
 Downloading hex v0.2.0
 Downloading tempdir v0.3.5
 Downloading ws2_32-sys v0.2.1
 Downloading rand v0.3.15
   Compiling foreign-types v0.2.0
   Compiling openssl v0.9.11 (file:///home/tox/src/rust-openssl/openssl)
   Compiling libc v0.2.22
   Compiling bitflags v0.8.2
   Compiling pkg-config v0.3.9
   Compiling winapi-build v0.1.1
   Compiling ws2_32-sys v0.2.1
   Compiling lazy_static v0.2.8
   Compiling gcc v0.3.45
   Compiling hex v0.2.0
   Compiling winapi v0.2.8
   Compiling rand v0.3.15
   Compiling openssl-sys v0.9.11 (file:///home/tox/src/rust-openssl/openssl-sys)
   Compiling tempdir v0.3.5
    Finished dev [unoptimized + debuginfo] target(s) in 11.10 secs
     Running /home/tox/src/rust-openssl/target/debug/deps/openssl-dc8098ea62ad18e5

running 171 tests
test aes::test::ige_vector_1 ... ok
test bn::tests::test_negation ... ok
test bn::tests::test_pseudo_rand_range ... ok
test bn::tests::test_rand_range ... ok
test bn::tests::test_shift ... ok
test bn::tests::test_prime_numbers ... ok
test bn::tests::test_to_from_slice ... ok
test dh::tests::test_dh ... ok
test dh::tests::test_dh_from_pem ... ok
test dh::tests::test_dh_from_der ... ok
test dsa::test::test_password ... ok
test dsa::test::test_password_callback ... ok
test ec::test::dup ... ok
test ec::test::generate ... ok
test ec::test::key_new_by_curve_name ... ok
test ec::test::key_from_public_key ... ok
test ec::test::point_bytes ... ok
test ec::test::point_new ... ok
test hash::tests::test_clone ... ok
test hash::tests::test_finish_twice ... ok
test hash::tests::test_md5 ... ok
test hash::tests::test_md5_recycle ... ok
test hash::tests::test_ripemd160 ... ok
test hash::tests::test_sha1 ... ok
test hash::tests::test_sha256 ... ok
test memcmp::tests::test_diff_lens ... ok
test memcmp::tests::test_eq ... ok
test ec::test::mul_generator ... ok
test pkcs12::test::parse ... ok
test pkcs12::test::parse_empty_chain ... ok
test pkcs5::tests::bytes_to_key ... ok
test dsa::test::test_generate ... ok
test pkcs5::tests::pbkdf2_hmac_sha512 ... ok
test pkey::tests::test_dh_accessor ... ok
test pkcs12::test::create ... ok
test pkey::tests::test_ec_key_accessor ... ok
test pkey::tests::test_ec_key_derive ... ok
test pkey::tests::test_encrypted_pkcs8_callback ... ok
test pkey::tests::test_encrypted_pkcs8_passphrase ... ok
test pkey::tests::test_pem ... ok
test pkey::tests::test_private_key_from_pem ... ok
test pkey::tests::test_public_key_from_der ... ok
test pkey::tests::test_public_key_from_pem ... ok
test pkcs5::tests::pbkdf2_hmac_sha256 ... ok
test pkey::tests::test_to_password ... ok
test rand::tests::test_rand_bytes ... ok
test rsa::test::test_from_password ... ok
test rsa::test::test_from_password_callback ... ok
test pkey::tests::test_rsa_accessor ... ok
test rsa::test::test_private_encrypt ... ok
test rsa::test::test_public_encrypt ... ok
test rsa::test::test_public_encrypt_private_decrypt_with_padding ... ok
test sha::test::standalone_1 ... ok
test sha::test::standalone_224 ... ok
test sha::test::standalone_256 ... ok
test sha::test::standalone_384 ... ok
test sha::test::standalone_512 ... ok
test sign::test::dsa_sign_verify ... ok
test sign::test::dsa_sign_verify_fail ... ok
test sign::test::ec ... ok
test sign::test::hmac_md5 ... ok
test sign::test::hmac_sha1 ... ok
test sign::test::rsa_sign ... ok
test sign::test::rsa_verify_invalid ... ok
test sign::test::rsa_verify_ok ... ok
test ssl::tests::active_session ... ok
test ssl::tests::add_extra_chain_cert ... ok
test rsa::test::test_to_password ... ok
test ssl::tests::clear_ctx_options::dtlsv1 ... ignored
test ssl::tests::cert_store ... ok
test ssl::tests::client_ca_list ... ok
test ssl::tests::connector_client_server_mozilla_intermediate ... ok
test pkey::tests::test_dsa_accessor ... ok
test ssl::tests::connector_client_server_mozilla_modern ... ok
test ssl::tests::clear_ctx_options::sslv23 ... ok
test ssl::tests::connector_invalid_hostname ... ok
test ssl::tests::connector_invalid_no_hostname_verification ... ok
test ssl::tests::connector_valid_hostname ... ok
test ssl::tests::default_verify_paths ... ok
test ssl::tests::connector_no_hostname_still_verifies ... ok
test ssl::tests::get_ctx_options::dtlsv1 ... ignored
test ssl::tests::connector_no_hostname_can_disable_verify ... ok
test ssl::tests::get_peer_certificate::dtlsv1 ... ignored
test dsa::test::test_to_password ... ok
test ssl::tests::idle_session ... ok
test ssl::tests::new_ctx::dtlsv1 ... ignored
test ssl::tests::get_ctx_options::sslv23 ... ok
test ssl::tests::flush_panic ... ok
test ssl::tests::refcount_ssl_context ... ok
test ssl::tests::set_ctx_options::dtlsv1 ... ignored
test ssl::tests::get_peer_certificate::sslv23 ... ok
test ssl::tests::shutdown ... ok
test ssl::tests::ssl_verify_callback::dtlsv1 ... ignored
test ssl::tests::new_ctx::sslv23 ... ok
test ssl::tests::status_callbacks ... FAILED
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:34979), fd: 5 }, ssl: Ssl { state: "SSLv3 read client key exchange A" } }, error: Stream(Error { repr: Os { code: 104, message: "Connection reset by peer" } }) })', src/libcore/result.rs:859
test ssl::tests::read_panic ... ok
test ssl::tests::set_ctx_options::sslv23 ... ok
test ssl::tests::test_npn_server_advertise_multiple ... ok
test ssl::tests::ssl_verify_callback::sslv23 ... ok
test ssl::tests::test_read_dtlsv1 ... ignored
test ssl::tests::test_read_nonblocking ... ignored
test ssl::tests::test_set_certificate_and_private_key ... ok
test ssl::tests::test_connect_with_unilateral_npn ... ok
test ssl::tests::test_pending ... ok
test ssl::tests::test_write_dtlsv1 ... ignored
test ssl::tests::test_write_hits_stream ... ok
test ssl::tests::test_read ... ok
test ssl::tests::test_state ... ok
test ssl::tests::test_write ... ok
test ssl::tests::verify_callback_data::dtlsv1 ... ignored
test ssl::tests::tmp_dh_callback ... ok
test ssl::tests::verify_callback_load_certs::dtlsv1 ... ignored
test ssl::tests::tmp_dh_callback_ssl ... ok
test ssl::tests::verify_trusted::dtlsv1 ... ignored
test ssl::tests::test_write_nonblocking ... ok
test ssl::tests::verify_trusted_callback_override_bad::dtlsv1 ... ignored
test ssl::tests::verify_callback_data::sslv23 ... ok
test ssl::tests::verify_trusted_callback_override_ok::dtlsv1 ... ignored
test ssl::tests::verify_callback_load_certs::sslv23 ... ok
test ssl::tests::verify_trusted_get_error_err::dtlsv1 ... ignored
test ssl::tests::verify_trusted::sslv23 ... ok
test ssl::tests::verify_trusted_get_error_ok::dtlsv1 ... ignored
test ssl::tests::verify_trusted_callback_override_bad::sslv23 ... ok
test ssl::tests::verify_untrusted::dtlsv1 ... ignored
test ssl::tests::verify_trusted_callback_override_ok::sslv23 ... ok
test ssl::tests::verify_untrusted_callback_override_bad::dtlsv1 ... ignored
test ssl::tests::verify_trusted_get_error_err::sslv23 ... ok
test ssl::tests::verify_untrusted_callback_override_ok::dtlsv1 ... ignored
test ssl::tests::verify_untrusted::sslv23 ... ok
test ssl::tests::verify_trusted_get_error_ok::sslv23 ... ok
test ssl::tests::verify_untrusted_callback_override_bad::sslv23 ... ok
test symm::tests::test_aes128_cfb1 ... ok
test symm::tests::test_aes128_cfb128 ... ok
test symm::tests::test_aes128_cfb8 ... ok
test symm::tests::test_aes128_ctr ... ok
test symm::tests::test_aes128_gcm ... ok
test symm::tests::test_aes256_cfb1 ... ok
test symm::tests::test_aes256_cfb128 ... ok
test symm::tests::test_aes256_cfb8 ... ok
test symm::tests::test_aes256_xts ... ok
test symm::tests::test_aes_256_cbc_decrypt ... ok
test symm::tests::test_aes_256_ecb ... ok
test symm::tests::test_bf_cbc ... ok
test symm::tests::test_bf_cfb64 ... ok
test symm::tests::test_bf_ecb ... ok
test symm::tests::test_bf_ofb ... ok
test symm::tests::test_des_cbc ... ok
test symm::tests::test_des_ecb ... ok
test symm::tests::test_rc4 ... ok
test version::test_versions ... ok
test x509::tests::ecdsa_cert ... ok
test x509::tests::issued ... ok
test x509::tests::signature ... ok
test ssl::tests::verify_untrusted_callback_override_ok::sslv23 ... ok
test ssl::tests::write_panic ... ok
test ssl::tests::zero_length_buffers ... ok
test x509::tests::test_cert_issue_validity ... ok
test x509::tests::test_cert_loading ... ok
test x509::tests::test_nid_uid_value ... ok
test x509::tests::test_nid_values ... ok
test x509::tests::test_cert_gen ... ok
test x509::tests::test_save_der ... ok
test x509::tests::test_stack_from_pem ... ok
test x509::tests::test_req_gen ... ok
test x509::tests::test_subject_alt_name_iter ... ok
test x509::tests::test_subject_read_cn ... ok
test x509::tests::test_subject_alt_name ... ok
test x509::tests::test_cert_gen_extension_bad_ordering ... ok
test x509::tests::x509_builder ... ok
test x509::tests::test_cert_gen_extension_ordering ... ok
test x509::tests::x509_req_builder ... ok

failures:

---- ssl::tests::status_callbacks stdout ----
	thread 'ssl::tests::status_callbacks' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323


failures:
    ssl::tests::status_callbacks

test result: FAILED. 151 passed; 1 failed; 19 ignored; 0 measured

error: test failed
```

**Comment by sfackler** [comment]
It appears that libressl has been messing with its struct layouts, so the refcount bump doesn't actually bump the refcount field anymore:

```
bad SSL size: rust: 648 (0x288) != c 232 (0xe8)
bad field offset server of SSL: rust: 56 (0x38) != c 40 (0x28)
bad field type server of SSL: rust: 0x38 != c 0x28
bad SSL_CTX size: rust: 552 (0x228) != c 120 (0x78)
bad field offset references of SSL_CTX: rust: 148 (0x94) != c 32 (0x20)
bad field type references of SSL_CTX: rust: 0x94 != c 0x20
bad SSL_SESSION size: rust: 296 (0x128) != c 232 (0xe8)
bad field offset references of SSL_SESSION: rust: 176 (0xb0) != c 160 (0xa0)
bad field type references of SSL_SESSION: rust: 0xb0 != c 0xa0
bad X509_VERIFY_PARAM size: rust: 56 (0x38) != c 64 (0x40)
```

**Comment by sfackler** [comment]
@semarie Is it expected that I'm going to have to redefine these structs for every libressl minor version release? That sounds pretty unreasonable.

**Comment by Gottox** [comment]
LibreSSL does not guarantee ABI stability between minor versions. See https://abi-laboratory.pro/tracker/timeline/libressl/

**Comment by Gottox** [comment]
I also found, that the build.rs panics in the build process when using master:

cargo build
---------------
```
cargo build --verbose
   Compiling gcc v0.3.45
   Compiling libc v0.2.22
   Compiling pkg-config v0.3.9
     Running `rustc --crate-name gcc /home/tox/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.45/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=fc74a781854cbb8b -C extra-filename=-fc74a781854cbb8b --out-dir /home/tox/src/rust-openssl/target/debug/deps -L dependency=/home/tox/src/rust-openssl/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name libc /home/tox/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.22/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="use_std"' --cfg 'feature="default"' -C metadata=026076ef8cc90032 -C extra-filename=-026076ef8cc90032 --out-dir /home/tox/src/rust-openssl/target/debug/deps -L dependency=/home/tox/src/rust-openssl/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name pkg_config /home/tox/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.9/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=af8168308ca6d27e -C extra-filename=-af8168308ca6d27e --out-dir /home/tox/src/rust-openssl/target/debug/deps -L dependency=/home/tox/src/rust-openssl/target/debug/deps --cap-lints allow`
   Compiling openssl-sys v0.9.11 (file:///home/tox/src/rust-openssl/openssl-sys)
     Running `rustc --crate-name build_script_build build.rs --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=7968f7750471d06c -C extra-filename=-7968f7750471d06c --out-dir /home/tox/src/rust-openssl/target/debug/build/openssl-sys-7968f7750471d06c -L dependency=/home/tox/src/rust-openssl/target/debug/deps --extern pkg_config=/home/tox/src/rust-openssl/target/debug/deps/libpkg_config-af8168308ca6d27e.rlib --extern gcc=/home/tox/src/rust-openssl/target/debug/deps/libgcc-fc74a781854cbb8b.rlib`
     Running `/home/tox/src/rust-openssl/target/debug/build/openssl-sys-7968f7750471d06c/build-script-build`
     Running `rustc --crate-name openssl_sys src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=f060c39f3a928b46 -C extra-filename=-f060c39f3a928b46 --out-dir /home/tox/src/rust-openssl/target/debug/deps -L dependency=/home/tox/src/rust-openssl/target/debug/deps --extern libc=/home/tox/src/rust-openssl/target/debug/deps/liblibc-026076ef8cc90032.rlib --cfg 'osslconf="OPENSSL_NO_BUF_FREELISTS"' --cfg 'osslconf="OPENSSL_NO_COMP"' --cfg 'osslconf="OPENSSL_NO_KRB5"' --cfg 'osslconf="OPENSSL_NO_PSK"' --cfg 'osslconf="OPENSSL_NO_RFC3779"' --cfg 'osslconf="OPENSSL_NO_SRP"' --cfg 'osslconf="OPENSSL_NO_SSL3_METHOD"' --cfg libressl -l ssl -l crypto`
    Finished dev [unoptimized + debuginfo] target(s) in 2.60 secs
```

build-script-build
----------------------
```
RUST_BACKTRACE=1 /home/tox/src/rust-openssl/target/debug/build/openssl-sys-7968f7750471d06c/build-script-build
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /builddir/rustc-1.17.0-src/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /builddir/rustc-1.17.0-src/src/libcore/result.rs:737
  11: build_script_build::main
             at ./build.rs:38
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start
  15: main
  16: __libc_start_main
             at ../csu/libc-start.c:295
  17: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by sfackler** [comment]
Cargo sets a bunch of environment variables that the build script depends
on.

**Comment by Gottox** [comment]
Sorry, I'm pretty new to rust and cargo. (And I must've known)

**Comment by sfackler** [comment]
Looks like abi-laboratory doesn't track struct layout unfortunately.

**Comment by Gottox** [comment]
Would tools like https://github.com/servo/rust-bindgen help here?

**Comment by sfackler** [comment]
Bindgen would have to run at build time, but it requires a pretty modern version of libclang which is basically a showstopper.
