### ISSUE TITLE
There is something wrong on build "openssl-sys", I need some help

### ISSUE THREAD

**Issue by driftluo** [sfackler/rust-openssl#762]
I want to build with `x86_64-unknow-linux-musl`, but it fail with this output:
```
$ PKG_CONFIG_ALLOW_CROSS=1 RUST_BACKTRACE=1 cargo build --release --target x86_64-unknown-linux-musl
   Compiling openssl-sys v0.9.20
error: failed to run custom build command for `openssl-sys v0.9.20`
process didn't exit successfully: `/home/luoc/Monitor/target/release/build/openssl-sys-ece041a505259e80/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=crypto
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-musl")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-musl = None
CC_x86_64_unknown_linux_musl = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-musl = None
CFLAGS_x86_64_unknown_linux_musl = None
TARGET_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-static" "-Wall" "-Wextra" "-E" "/home/luoc/Monitor/target/x86_64-unknown-linux-musl/release/build/openssl-sys-419237dbdb0230fe/out/expando.c"

--- stderr
thread 'main' panicked at '

Internal error occurred: Failed to find tool. Is `musl-gcc` installed?

', /home/luoc/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.2/src/lib.rs:1818:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: cc::fail
   8: cc::Build::expand
   9: std::panicking::try::do_call
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  11: build_script_build::validate_headers
  12: build_script_build::main
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  15: __libc_start_main
  16: <unknown>
thread 'main' panicked at '
Failed to find OpenSSL development headers.

You can try fixing this setting the `OPENSSL_DIR` environment variable
pointing to your OpenSSL installation or installing OpenSSL headers package
specific to your distribution:

    # On Ubuntu
    sudo apt-get install libssl-dev
    # On Arch Linux
    sudo pacman -S openssl
    # On Fedora
    sudo dnf install openssl-devel

See rust-openssl README for more information:

    https://github.com/sfackler/rust-openssl#linux
', /home/luoc/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.20/build.rs:382:12
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
   6: build_script_build::validate_headers
   7: build_script_build::main
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  10: __libc_start_main
```

but when I buid with `x86_64-unknow-linux-gnu`, it works well. So is there some people can help me?

**Comment by sfackler** [comment]
There are two problems here:

1. The build script is looking for the musl-gcc cross compiler. This comes in the `musl-tools` package on Ubuntu, for example.
2. Trying to link to your system's default OpenSSL libraries in a MUSL build is not going to work. You'll need to build a copy of OpenSSL built against MUSL using musl-gcc.

**Comment by driftluo** [comment]
It means I need to build a `musl-gcc`, and then use `musl-gcc` build an `Openssl`, and then I can continue my work ?

**Comment by sfackler** [comment]
Yes.

**Comment by driftluo** [comment]
Ok, thinks, I will try to do it : )

**Comment by driftluo** [comment]
I have successfully compiled, thank you, but I need to sort out my working environment, the two `openssl` seems a bit messy
