### ISSUE TITLE
Some ecdsa tests fail

### ISSUE THREAD

**Issue by ignatenkobrain** [sfackler/rust-openssl#964]
```rust
---- ecdsa::test::check_private_components stdout ----
	thread 'ecdsa::test::check_private_components' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 269148289, library: "elliptic curve routines", function: "EC_GROUP_new_by_curve_name", reason: "unknown group", file: "ec_curve.c", line: 424 }])', libcore/result.rs:945:5

---- ecdsa::test::sign_and_verify stdout ----
	thread 'ecdsa::test::sign_and_verify' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 269148289, library: "elliptic curve routines", function: "EC_GROUP_new_by_curve_name", reason: "unknown group", file: "ec_curve.c", line: 424 }])', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment]
This is probably because your copy of OpenSSL has some feature disabled that the curve requires. What's the configuration of your openssl install? `openssl version -a` will print the configuration.
